@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry VictoryRoad1fRoom2_Entry0
    ScriptEntry VictoryRoad1fRoom2_Entry1
    ScriptEntry VictoryRoad1fRoom2_Entry2
    ScriptEntry VictoryRoad1fRoom2_Entry3
    ScriptEntryEnd

VictoryRoad1fRoom2_Entry0:
    LockAll
    SetPlayerBike 0
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_0326
    WaitMovement
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 55
    GoToIf 1, VictoryRoad1fRoom2_015E
    CompareVarToValue VAR_0x8005, 56
    GoToIf 1, VictoryRoad1fRoom2_016E
    CompareVarToValue VAR_0x8005, 57
    GoToIf 1, VictoryRoad1fRoom2_017E
    CompareVarToValue VAR_0x8005, 58
    GoToIf 1, VictoryRoad1fRoom2_018E
    CompareVarToValue VAR_0x8005, 59
    GoToIf 1, VictoryRoad1fRoom2_019E
    CompareVarToValue VAR_0x8005, 60
    GoToIf 1, VictoryRoad1fRoom2_01AE
    End
VictoryRoad1fRoom2_Entry1:
    LockAll
    ApplyMovement LOCALID_PLAYER, VictoryRoad1fRoom2_Movement_0332
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_033A
    WaitMovement
    Message 4
    CloseMessage
    SetVarFromValue VAR_VICTORY_ROAD_1F_ROOM_2_FOLLOWER_MARLEY_STATE, 0
    ClearHasPartner
    SetMovementType 28, 14
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 55
    GoToIf 1, VictoryRoad1fRoom2_01BE
    CompareVarToValue VAR_0x8005, 56
    GoToIf 1, VictoryRoad1fRoom2_01CE
    CompareVarToValue VAR_0x8005, 57
    GoToIf 1, VictoryRoad1fRoom2_01DE
    CompareVarToValue VAR_0x8005, 58
    GoToIf 1, VictoryRoad1fRoom2_01EE
    CompareVarToValue VAR_0x8005, 59
    GoToIf 1, VictoryRoad1fRoom2_01FE
    CompareVarToValue VAR_0x8005, 60
    GoToIf 1, VictoryRoad1fRoom2_020E
    End
VictoryRoad1fRoom2_Entry2:
    LockAll
    ClearHasPartner
    SetMovementType 28, 14
    ApplyMovement LOCALID_PLAYER, VictoryRoad1fRoom2_Movement_0342
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_034E
    WaitMovement
    Message 5
    CloseMessage
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8004, 51
    GoToIf 1, VictoryRoad1fRoom2_021E
    CompareVarToValue VAR_0x8004, 52
    GoToIf 1, VictoryRoad1fRoom2_0236
    CompareVarToValue VAR_0x8004, 53
    GoToIf 1, VictoryRoad1fRoom2_024E
    CompareVarToValue VAR_0x8004, 54
    GoToIf 1, VictoryRoad1fRoom2_0266
    End
VictoryRoad1fRoom2_Entry3:
    CheckFlag FLAG_TRAVELED_WITH_MARLEY
    GoToIf 0, VictoryRoad1fRoom2_027E
    End
VictoryRoad1fRoom2_015E:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_035A
    WaitMovement
    GoTo VictoryRoad1fRoom2_0286
VictoryRoad1fRoom2_016E:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_0366
    WaitMovement
    GoTo VictoryRoad1fRoom2_0286
VictoryRoad1fRoom2_017E:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_0372
    WaitMovement
    GoTo VictoryRoad1fRoom2_0286
VictoryRoad1fRoom2_018E:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_037E
    WaitMovement
    GoTo VictoryRoad1fRoom2_0286
VictoryRoad1fRoom2_019E:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_0386
    WaitMovement
    GoTo VictoryRoad1fRoom2_0286
VictoryRoad1fRoom2_01AE:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_0392
    WaitMovement
    GoTo VictoryRoad1fRoom2_0286
VictoryRoad1fRoom2_01BE:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_039E
    WaitMovement
    GoTo VictoryRoad1fRoom2_02D9
VictoryRoad1fRoom2_01CE:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_03AE
    WaitMovement
    GoTo VictoryRoad1fRoom2_02D9
VictoryRoad1fRoom2_01DE:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_03BE
    WaitMovement
    GoTo VictoryRoad1fRoom2_02D9
VictoryRoad1fRoom2_01EE:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_03CE
    WaitMovement
    GoTo VictoryRoad1fRoom2_02D9
VictoryRoad1fRoom2_01FE:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_03D6
    WaitMovement
    GoTo VictoryRoad1fRoom2_02D9
VictoryRoad1fRoom2_020E:
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_03E6
    WaitMovement
    GoTo VictoryRoad1fRoom2_02D9
VictoryRoad1fRoom2_021E:
    ApplyMovement LOCALID_PLAYER, VictoryRoad1fRoom2_Movement_03F6
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_0406
    WaitMovement
    GoTo VictoryRoad1fRoom2_02DD
VictoryRoad1fRoom2_0236:
    ApplyMovement LOCALID_PLAYER, VictoryRoad1fRoom2_Movement_03F6
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_041A
    WaitMovement
    GoTo VictoryRoad1fRoom2_02DD
VictoryRoad1fRoom2_024E:
    ApplyMovement LOCALID_PLAYER, VictoryRoad1fRoom2_Movement_03F6
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_042E
    WaitMovement
    GoTo VictoryRoad1fRoom2_02DD
VictoryRoad1fRoom2_0266:
    ApplyMovement LOCALID_PLAYER, VictoryRoad1fRoom2_Movement_0442
    ApplyMovement 28, VictoryRoad1fRoom2_Movement_0452
    WaitMovement
    GoTo VictoryRoad1fRoom2_02DD
VictoryRoad1fRoom2_027E:
    SetVarFromValue VAR_VICTORY_ROAD_1F_ROOM_2_FOLLOWER_MARLEY_STATE, 0
    End
VictoryRoad1fRoom2_0286:
    BufferPlayerName 0
    CheckFlag FLAG_UNK_0x0A71
    CallIf 0, VictoryRoad1fRoom2_02F9
    CheckFlag FLAG_TALKED_TO_VICTORY_ROAD_1F_ROOM_2_MARLEY
    CallIf 0, VictoryRoad1fRoom2_02EF
    CheckFlag FLAG_TALKED_TO_VICTORY_ROAD_1F_ROOM_2_MARLEY
    CallIf 1, VictoryRoad1fRoom2_02F4
    BufferPlayerName 0
    PlayFanfare SEQ_GONIN_sseq
    Message 1
    WaitFanfare
    SetFlag FLAG_TALKED_TO_VICTORY_ROAD_1F_ROOM_2_MARLEY
    SetVarFromValue VAR_VICTORY_ROAD_1F_ROOM_2_FOLLOWER_MARLEY_STATE, 1
    Message 2
    WaitButton
    CloseMessage
    SetVarFromValue VAR_PARTNER_TRAINER_ID, 610
    SetHasPartner
    SetMovementType 28, 48
    ReleaseAll
    End
VictoryRoad1fRoom2_02D9:
    ReleaseAll
    End
VictoryRoad1fRoom2_02DD:
    RemoveObject 28
    SetFlag FLAG_TRAVELED_WITH_MARLEY
    SetVarFromValue VAR_VICTORY_ROAD_1F_ROOM_2_FOLLOWER_MARLEY_STATE, 2
    ReleaseAll
    End
VictoryRoad1fRoom2_02EF:
    Message 0
    Return
VictoryRoad1fRoom2_02F4:
    Message 3
    Return
VictoryRoad1fRoom2_02F9:
    Message 12
    WaitButton
    CloseMessage
    StartTrainerBattle 610, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VictoryRoad1fRoom2_0320
    SetFlag FLAG_UNK_0x0A71
    BufferPlayerName 0
    Return
VictoryRoad1fRoom2_0320:
    BlackOutFromBattle
    ReleaseAll
    End
VictoryRoad1fRoom2_Movement_0326:
    WalkOnSpotNormalWest 1
    EmoteExclamationMark 1
    EndMovement

VictoryRoad1fRoom2_Movement_0332:
    WalkOnSpotNormalEast 1
    EndMovement

VictoryRoad1fRoom2_Movement_033A:
    FaceWest 1
    EndMovement

VictoryRoad1fRoom2_Movement_0342:
    Delay8 1
    WalkOnSpotNormalSouth 1
    EndMovement

VictoryRoad1fRoom2_Movement_034E:
    WalkOnSpotNormalNorth 1
    EmoteExclamationMark 1
    EndMovement

VictoryRoad1fRoom2_Movement_035A:
    WalkNormalNorth 3
    WalkNormalWest 1
    EndMovement

VictoryRoad1fRoom2_Movement_0366:
    WalkNormalNorth 2
    WalkNormalWest 1
    EndMovement

VictoryRoad1fRoom2_Movement_0372:
    WalkNormalNorth 1
    WalkNormalWest 1
    EndMovement

VictoryRoad1fRoom2_Movement_037E:
    WalkNormalWest 1
    EndMovement

VictoryRoad1fRoom2_Movement_0386:
    WalkNormalSouth 1
    WalkNormalWest 1
    EndMovement

VictoryRoad1fRoom2_Movement_0392:
    WalkNormalSouth 2
    WalkNormalWest 1
    EndMovement

VictoryRoad1fRoom2_Movement_039E:
    WalkNormalEast 2
    WalkNormalSouth 3
    WalkOnSpotNormalEast 1
    EndMovement

VictoryRoad1fRoom2_Movement_03AE:
    WalkNormalEast 2
    WalkNormalSouth 2
    WalkOnSpotNormalEast 1
    EndMovement

VictoryRoad1fRoom2_Movement_03BE:
    WalkNormalEast 2
    WalkNormalSouth 1
    WalkOnSpotNormalEast 1
    EndMovement

VictoryRoad1fRoom2_Movement_03CE:
    WalkNormalEast 2
    EndMovement

VictoryRoad1fRoom2_Movement_03D6:
    WalkNormalEast 2
    WalkNormalNorth 1
    WalkOnSpotNormalEast 1
    EndMovement

VictoryRoad1fRoom2_Movement_03E6:
    WalkNormalEast 2
    WalkNormalNorth 2
    WalkOnSpotNormalEast 1
    EndMovement

VictoryRoad1fRoom2_Movement_03F6:
    Delay8 1
    WalkOnSpotNormalEast 1
    WalkOnSpotNormalNorth 1
    EndMovement

VictoryRoad1fRoom2_Movement_0406:
    WalkNormalEast 1
    WalkNormalNorth 7
    WalkNormalEast 4
    WalkOnSpotNormalEast 1
    EndMovement

VictoryRoad1fRoom2_Movement_041A:
    WalkNormalEast 1
    WalkNormalNorth 7
    WalkNormalEast 3
    WalkOnSpotNormalEast 1
    EndMovement

VictoryRoad1fRoom2_Movement_042E:
    WalkNormalEast 1
    WalkNormalNorth 7
    WalkNormalEast 2
    WalkOnSpotNormalEast 1
    EndMovement

VictoryRoad1fRoom2_Movement_0442:
    Delay8 1
    WalkOnSpotNormalWest 1
    WalkOnSpotNormalNorth 1
    EndMovement

VictoryRoad1fRoom2_Movement_0452:
    WalkNormalWest 1
    WalkNormalNorth 7
    WalkNormalEast 3
    WalkOnSpotNormalEast 1
    EndMovement

