@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry SandgemTown_Entry0
    ScriptEntry SandgemTown_Entry1
    ScriptEntry SandgemTown_Entry2
    ScriptEntry SandgemTown_Entry3
    ScriptEntry SandgemTown_Entry4
    ScriptEntry SandgemTown_Entry5
    ScriptEntry SandgemTown_Entry6
    ScriptEntry SandgemTown_Entry7
    ScriptEntry SandgemTown_Entry8
    ScriptEntry SandgemTown_Entry9
    ScriptEntry SandgemTown_Entry10
    ScriptEntry SandgemTown_Entry11
    ScriptEntry SandgemTown_Entry12
    ScriptEntryEnd

SandgemTown_Entry0:
    CompareVarToValue VAR_SANDGEM_TOWN_STATE, 1
    CallIf 1, SandgemTown_02A0
    GetPlayerGender VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, SandgemTown_02B6
    CompareVarToValue VARS_START, 1
    GoToIf 1, SandgemTown_02BE
    End
SandgemTown_Entry1:
    LockAll
    ApplyMovement 4, SandgemTown_Movement_07C8
    WaitMovement
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 843
    GoToIf 1, SandgemTown_02C6
    CompareVarToValue VAR_0x8005, 844
    GoToIf 1, SandgemTown_02DE
    CompareVarToValue VAR_0x8005, 845
    GoToIf 1, SandgemTown_02EE
    CompareVarToValue VAR_0x8005, 846
    GoToIf 1, SandgemTown_02FE
    CompareVarToValue VAR_0x8005, 847
    GoToIf 1, SandgemTown_0316
    CompareVarToValue VAR_0x8005, 848
    GoToIf 1, SandgemTown_032E
    End
SandgemTown_Entry2:
    LockAll
    LoadDoorAnimation 5, 26, 8, 10, 77
    PlayDoorOpenAnimation 77
    WaitForAnimation 77
    ClearFlag FLAG_HIDE_SANDGEM_TOWN_PROF_ROWAN
    AddObject 14
    ApplyMovement 14, SandgemTown_Movement_07D4
    WaitMovement
    BufferPlayerName 0
    Message 8
    CloseMessage
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_07DC
    ApplyMovement 4, SandgemTown_Movement_07E8
    WaitMovement
    Message 9
    SetVarFromValue VAR_0x8004, 337
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    Message 10
    SetFlag FLAG_UNLOCKED_VS_SEEKER_LVL_1
    SetVarFromValue VAR_0x8004, 443
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    CloseMessage
    ApplyMovement 14, SandgemTown_Movement_07F0
    WaitMovement
    PlayDoorCloseAnimation 77
    WaitForAnimation 77
    UnloadAnimation 77
    RemoveObject 14
    WaitTime 30, VAR_0x800C
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SandgemTown_0346
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SandgemTown_0351
    End
SandgemTown_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 21
    WaitButton
    CloseMessage
    ReleaseAll
    End
SandgemTown_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 22
    WaitButton
    CloseMessage
    ReleaseAll
    End
SandgemTown_Entry5:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 23
    WaitButton
    CloseMessage
    ReleaseAll
    End
SandgemTown_Entry6:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 24
    WaitButton
    CloseMessage
    ReleaseAll
    End
SandgemTown_Entry7:
    DrawSignpostInstantMessage 25, 0, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
SandgemTown_Entry8:
    DrawSignpostInstantMessage 26, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
SandgemTown_Entry9:
    BufferCounterpartName 0
    DrawSignpostInstantMessage 27, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
SandgemTown_Entry10:
    DrawSignpostInstantMessage 28, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
SandgemTown_Entry11:
    DrawSignpostInstantMessage 29, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
SandgemTown_Entry12:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A8A
    GoToIf 0, SandgemTown_035C
    Message 31
    InitLocalTextListMenu 1, 1, 0, VAR_0x800C, 1
    AddListMenuEntry 32, 0, 255
    CheckFlag FLAG_UNK_0x0A89
    CallIf 1, SandgemTown_0369
    CheckFlag FLAG_UNK_0x0A83
    CallIf 1, SandgemTown_0373
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, SandgemTown_037D
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, SandgemTown_03AF
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, SandgemTown_03E1
    GoTo SandgemTown_0413
SandgemTown_02A0:
    SetObjectEventPos 4, 168, 845
    SetObjectEventDir 4, 0
    SetObjectEventMovementType 4, 14
    Return
SandgemTown_02B6:
    SetVarFromValue OBJ_GFX_VARS_START, 97
    End
SandgemTown_02BE:
    SetVarFromValue OBJ_GFX_VARS_START, 0
    End
SandgemTown_02C6:
    ApplyMovement 4, SandgemTown_Movement_07FC
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0808
    WaitMovement
    GoTo SandgemTown_0419
SandgemTown_02DE:
    ApplyMovement 4, SandgemTown_Movement_0814
    WaitMovement
    GoTo SandgemTown_0419
SandgemTown_02EE:
    ApplyMovement 4, SandgemTown_Movement_0824
    WaitMovement
    GoTo SandgemTown_0419
SandgemTown_02FE:
    ApplyMovement 4, SandgemTown_Movement_082C
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0838
    WaitMovement
    GoTo SandgemTown_0419
SandgemTown_0316:
    ApplyMovement 4, SandgemTown_Movement_0844
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0850
    WaitMovement
    GoTo SandgemTown_0419
SandgemTown_032E:
    ApplyMovement 4, SandgemTown_Movement_085C
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0868
    WaitMovement
    GoTo SandgemTown_0419
SandgemTown_0346:
    Message 11
    CloseMessage
    GoTo SandgemTown_0439
SandgemTown_0351:
    Message 12
    CloseMessage
    GoTo SandgemTown_0439
SandgemTown_035C:
    Message 30
    SetFlag FLAG_UNK_0x0A8A
    CloseMessage
    ReleaseAll
    End
SandgemTown_0369:
    AddListMenuEntry 33, 1, 255
    Return
SandgemTown_0373:
    AddListMenuEntry 34, 2, 255
    Return
SandgemTown_037D:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 411, 116, 886, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SandgemTown_03AF:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 3, 180, 777, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SandgemTown_03E1:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 392, 308, 914, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SandgemTown_0413:
    CloseMessage
    ReleaseAll
    End
SandgemTown_0419:
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SandgemTown_046B
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SandgemTown_0477
    End
SandgemTown_0439:
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0874
    ApplyMovement 4, SandgemTown_Movement_087C
    WaitMovement
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SandgemTown_0483
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SandgemTown_0492
    End
SandgemTown_046B:
    BufferCounterpartName 0
    Message 0
    GoTo SandgemTown_04A1
SandgemTown_0477:
    BufferCounterpartName 0
    Message 2
    GoTo SandgemTown_04A1
SandgemTown_0483:
    BufferCounterpartName 0
    BufferPlayerName 1
    Message 13
    GoTo SandgemTown_04F3
SandgemTown_0492:
    BufferCounterpartName 0
    BufferPlayerName 1
    Message 17
    GoTo SandgemTown_04F3
SandgemTown_04A1:
    CloseMessage
    CompareVarToValue VAR_0x8005, 843
    GoToIf 1, SandgemTown_052B
    CompareVarToValue VAR_0x8005, 844
    GoToIf 1, SandgemTown_0543
    CompareVarToValue VAR_0x8005, 845
    GoToIf 1, SandgemTown_055B
    CompareVarToValue VAR_0x8005, 846
    GoToIf 1, SandgemTown_0573
    CompareVarToValue VAR_0x8005, 847
    GoToIf 1, SandgemTown_058B
    CompareVarToValue VAR_0x8005, 848
    GoToIf 1, SandgemTown_05A3
    End
SandgemTown_04F3:
    CloseMessage
    CallCommonScript 2048
    ApplyMovement 4, SandgemTown_Movement_0884
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0890
    WaitMovement
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SandgemTown_05BB
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SandgemTown_05CA
    End
SandgemTown_052B:
    ApplyMovement 4, SandgemTown_Movement_08A0
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_08AC
    WaitMovement
    GoTo SandgemTown_05D9
SandgemTown_0543:
    ApplyMovement 4, SandgemTown_Movement_08BC
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_08C8
    WaitMovement
    GoTo SandgemTown_05D9
SandgemTown_055B:
    ApplyMovement 4, SandgemTown_Movement_08D8
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_08E8
    WaitMovement
    GoTo SandgemTown_05D9
SandgemTown_0573:
    ApplyMovement 4, SandgemTown_Movement_08FC
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0910
    WaitMovement
    GoTo SandgemTown_05D9
SandgemTown_058B:
    ApplyMovement 4, SandgemTown_Movement_0928
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0938
    WaitMovement
    GoTo SandgemTown_05D9
SandgemTown_05A3:
    ApplyMovement 4, SandgemTown_Movement_0948
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0958
    WaitMovement
    GoTo SandgemTown_05D9
SandgemTown_05BB:
    BufferCounterpartName 0
    BufferPlayerName 1
    Message 14
    GoTo SandgemTown_05F9
SandgemTown_05CA:
    BufferCounterpartName 0
    BufferPlayerName 1
    Message 18
    GoTo SandgemTown_05F9
SandgemTown_05D9:
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SandgemTown_062D
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SandgemTown_0636
    End
SandgemTown_05F9:
    CloseMessage
    ApplyMovement 4, SandgemTown_Movement_0968
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0974
    WaitMovement
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SandgemTown_063F
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SandgemTown_064B
    End
SandgemTown_062D:
    Message 1
    GoTo SandgemTown_0657
SandgemTown_0636:
    Message 3
    GoTo SandgemTown_0657
SandgemTown_063F:
    BufferPlayerName 0
    Message 15
    GoTo SandgemTown_06E6
SandgemTown_064B:
    BufferPlayerName 0
    Message 19
    GoTo SandgemTown_06E6
SandgemTown_0657:
    LoadDoorAnimation 5, 26, 8, 10, 77
    PlayDoorOpenAnimation 77
    WaitForAnimation 77
    ClearFlag FLAG_HIDE_SANDGEM_TOWN_RIVAL
    AddObject 3
    ApplyMovement 3, SandgemTown_Movement_0980
    WaitMovement
    ApplyMovement 3, SandgemTown_Movement_0988
    WaitMovement
    PlaySE SEQ_SE_DP_WALL_HIT2_sseq
    Message 4
    ApplyMovement 3, SandgemTown_Movement_0990
    WaitMovement
    CallCommonScript 2042
    BufferRivalName 0
    BufferPlayerName 1
    Message 5
    CloseMessage
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0998
    ApplyMovement 4, SandgemTown_Movement_09A4
    ApplyMovement 3, SandgemTown_Movement_09B0
    WaitMovement
    RemoveObject 3
    CallCommonScript 2043
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SandgemTown_0724
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SandgemTown_0730
    End
SandgemTown_06E6:
    CloseMessage
    ApplyMovement 4, SandgemTown_Movement_09C0
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_09C8
    WaitMovement
    ApplyMovement 4, SandgemTown_Movement_09D0
    WaitMovement
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SandgemTown_073C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SandgemTown_0748
    End
SandgemTown_0724:
    BufferCounterpartName 0
    Message 6
    GoTo SandgemTown_0754
SandgemTown_0730:
    BufferCounterpartName 0
    Message 7
    GoTo SandgemTown_0754
SandgemTown_073C:
    BufferPlayerName 1
    Message 16
    GoTo SandgemTown_07A1
SandgemTown_0748:
    BufferPlayerName 1
    Message 20
    GoTo SandgemTown_07A1
SandgemTown_0754:
    CloseMessage
    ApplyMovement 4, SandgemTown_Movement_09D8
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_09EC
    WaitMovement
    PlayDoorCloseAnimation 77
    WaitForAnimation 77
    UnloadAnimation 77
    RemoveObject 4
    SetVarFromValue VAR_SANDGEM_TOWN_STATE, 1
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 422, 7, 15, 0
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    End
SandgemTown_07A1:
    CloseMessage
    ApplyMovement 4, SandgemTown_Movement_0A04
    ApplyMovement LOCALID_PLAYER, SandgemTown_Movement_0A14
    WaitMovement
    CallCommonScript 2049
    RemoveObject 4
    SetVarFromValue VAR_SANDGEM_TOWN_STATE, 2
    ReleaseAll
    End
    .balign 4, 0

SandgemTown_Movement_07C8:
    EmoteExclamationMark 1
    Delay16 1
    EndMovement

SandgemTown_Movement_07D4:
    WalkOnSpotNormalSouth 1
    EndMovement

SandgemTown_Movement_07DC:
    EmoteExclamationMark 1
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_07E8:
    EmoteExclamationMark 1
    EndMovement

SandgemTown_Movement_07F0:
    WalkOnSpotNormalNorth 1
    SetInvisible 1
    EndMovement

SandgemTown_Movement_07FC:
    WalkNormalWest 4
    WalkNormalNorth 1
    EndMovement

SandgemTown_Movement_0808:
    Delay8 3
    FaceSouth 1
    EndMovement

SandgemTown_Movement_0814:
    WalkNormalWest 2
    WalkNormalNorth 1
    WalkNormalWest 1
    EndMovement

SandgemTown_Movement_0824:
    WalkNormalWest 3
    EndMovement

SandgemTown_Movement_082C:
    WalkNormalWest 4
    FaceSouth 1
    EndMovement

SandgemTown_Movement_0838:
    Delay8 3
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0844:
    WalkNormalWest 4
    WalkNormalSouth 1
    EndMovement

SandgemTown_Movement_0850:
    Delay8 3
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_085C:
    WalkNormalWest 4
    WalkNormalSouth 2
    EndMovement

SandgemTown_Movement_0868:
    Delay8 3
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0874:
    WalkOnSpotNormalSouth 1
    EndMovement

SandgemTown_Movement_087C:
    WalkNormalNorth 1
    EndMovement

SandgemTown_Movement_0884:
    WalkNormalEast 10
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0890:
    WalkNormalSouth 1
    WalkNormalEast 9
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_08A0:
    WalkNormalEast 5
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_08AC:
    WalkNormalSouth 1
    WalkNormalEast 4
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_08BC:
    WalkNormalEast 4
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_08C8:
    WalkNormalEast 2
    WalkNormalEast 2
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_08D8:
    WalkNormalNorth 1
    WalkNormalEast 4
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_08E8:
    WalkNormalEast 1
    WalkNormalNorth 1
    WalkNormalEast 3
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_08FC:
    WalkNormalEast 2
    WalkNormalNorth 1
    WalkNormalEast 3
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0910:
    WalkNormalNorth 1
    WalkNormalEast 2
    WalkNormalNorth 1
    WalkNormalEast 2
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0928:
    WalkNormalNorth 2
    WalkNormalEast 5
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0938:
    WalkNormalNorth 3
    WalkNormalEast 4
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0948:
    WalkNormalNorth 2
    WalkNormalEast 5
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0958:
    WalkNormalNorth 4
    WalkNormalEast 4
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0968:
    WalkNormalEast 10
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0974:
    WalkNormalEast 10
    WalkOnSpotNormalNorth 1
    EndMovement

SandgemTown_Movement_0980:
    WalkFastSouth 1
    EndMovement

SandgemTown_Movement_0988:
    WalkOnSpotFastSouth 2
    EndMovement

SandgemTown_Movement_0990:
    EmoteExclamationMark 1
    EndMovement

SandgemTown_Movement_0998:
    Delay8 1
    WalkOnSpotNormalEast 1
    EndMovement

SandgemTown_Movement_09A4:
    Delay4 1
    WalkOnSpotNormalEast 1
    EndMovement

SandgemTown_Movement_09B0:
    WalkFastEast 2
    WalkFastSouth 1
    WalkFastEast 7
    EndMovement

SandgemTown_Movement_09C0:
    WalkOnSpotNormalWest 1
    EndMovement

SandgemTown_Movement_09C8:
    WalkOnSpotNormalEast 1
    EndMovement

SandgemTown_Movement_09D0:
    EmoteExclamationMark 1
    EndMovement

SandgemTown_Movement_09D8:
    WalkNormalNorth 1
    WalkNormalWest 1
    WalkNormalNorth 1
    SetInvisible 1
    EndMovement

SandgemTown_Movement_09EC:
    Delay8 1
    WalkOnSpotNormalNorth 1
    Delay8 2
    WalkNormalNorth 2
    SetInvisible 1
    EndMovement

SandgemTown_Movement_0A04:
    WalkNormalSouth 1
    WalkNormalWest 5
    WalkNormalNorth 10
    EndMovement

SandgemTown_Movement_0A14:
    Delay8 1
    WalkOnSpotNormalSouth 1
    Delay4 1
    WalkOnSpotNormalWest 1
    EndMovement

