@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry SpearPillarDialga_Entry0
    ScriptEntry SpearPillarDialga_Entry1
    ScriptEntryEnd

SpearPillarDialga_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CompareVarToValue VAR_SPEAR_PILLAR_DIALGA_STATE, 1
    GoToIf 4, SpearPillarDialga_0083
    CheckFlag FLAG_CAUGHT_DIALGA
    GoToIf 1, SpearPillarDialga_0083
    Message 0
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SpearPillarDialga_008E
    PlayCry SPECIES_DIALGA, 0
    Message 1
    WaitCry
    CloseMessage
    StartLegendaryBattle SPECIES_DIALGA, 70
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SpearPillarDialga_0094
    SetVarFromValue VAR_SPEAR_PILLAR_DIALGA_STATE, 1
    CheckDidNotCapture VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    CallIf 1, SpearPillarDialga_009A
    ReleaseAll
    End
SpearPillarDialga_Entry1:
    Call SpearPillarDialga_00A0
    End
SpearPillarDialga_0083:
    Message 2
    WaitButton
    GoTo SpearPillarDialga_008E
SpearPillarDialga_008E:
    CloseMessage
    ReleaseAll
    End
SpearPillarDialga_0094:
    BlackOutFromBattle
    ReleaseAll
    End
SpearPillarDialga_009A:
    SetFlag FLAG_CAUGHT_DIALGA
    Return
SpearPillarDialga_00A0:
    CheckGameCompleted VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, SpearPillarDialga_00EF
    GetSetNationalDexEnabled 2, VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, SpearPillarDialga_00EF
    CheckItem ITEM_AZURE_FLUTE, 1, VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, SpearPillarDialga_00EF
    CheckFlag FLAG_CAUGHT_ARCEUS
    GoToIf 1, SpearPillarDialga_00EF
    SetVarFromValue VAR_HALL_OF_ORIGIN_STATE, 1
    GoTo SpearPillarDialga_00EF
SpearPillarDialga_00EF:
    Return
    .byte 0

