@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry SnowpointCity_Entry0
    ScriptEntry SnowpointCity_Entry1
    ScriptEntry SnowpointCity_Entry2
    ScriptEntry SnowpointCity_Entry3
    ScriptEntry SnowpointCity_Entry4
    ScriptEntry SnowpointCity_Entry5
    ScriptEntry SnowpointCity_Entry6
    ScriptEntry SnowpointCity_Entry7
    ScriptEntry SnowpointCity_Entry8
    ScriptEntry SnowpointCity_Entry9
    ScriptEntry SnowpointCity_Entry10
    ScriptEntry SnowpointCity_Entry11
    ScriptEntry SnowpointCity_Entry12
    ScriptEntry SnowpointCity_Entry13
    ScriptEntry SnowpointCity_Entry14
    ScriptEntryEnd

SnowpointCity_Entry0:
    CompareVarToValue VAR_SNOWPOINT_CITY_STATE, 1
    GoToIf 4, SnowpointCity_02DF
    End
SnowpointCity_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    GetSetNationalDexEnabled 2, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SnowpointCity_02E5
    GoTo SnowpointCity_0308
SnowpointCity_Entry2:
    LockAll
    ApplyMovement 6, SnowpointCity_Movement_068A
    WaitMovement
    Message 0
    CloseMessage
    GetSetNationalDexEnabled 2, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SnowpointCity_0313
    GoTo SnowpointCity_0324
SnowpointCity_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 4
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 5
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_Entry5:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 6
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_Entry6:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 9
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_Entry7:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CompareVarToValue VAR_SNOWPOINT_CITY_STATE, 1
    GoToIf 4, SnowpointCity_033A
    Message 7
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_Entry8:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 14
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_Entry9:
    DrawSignpostInstantMessage 18, 0, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
SnowpointCity_Entry10:
    DrawSignpostTextBox 3, 0
    SetSignpostCommand 3
    WaitForSignpostDone
    DrawSignpostScrollingMessage 19, VAR_0x800C
    CallCommonScript 2000
    End
SnowpointCity_Entry11:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_GAME_COMPLETED
    GoToIf 0, SnowpointCity_0345
    Message 10
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SnowpointCity_0350
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SnowpointCity_037A
    End
SnowpointCity_Entry12:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A7F
    GoToIf 0, SnowpointCity_0385
    Message 21
    InitLocalTextListMenu 1, 1, 0, VAR_0x800C, 1
    CheckFlag FLAG_UNK_0x0A88
    CallIf 1, SnowpointCity_0392
    CheckFlag FLAG_UNK_0x0A86
    CallIf 1, SnowpointCity_039C
    CheckFlag FLAG_UNK_0x0A85
    CallIf 1, SnowpointCity_03A6
    CheckFlag FLAG_UNK_0x0A81
    CallIf 1, SnowpointCity_03B0
    CheckFlag FLAG_UNK_0x0A7B
    CallIf 1, SnowpointCity_03BA
    CheckFlag FLAG_UNK_0x0A7A
    CallIf 1, SnowpointCity_03C4
    CheckFlag FLAG_UNK_0x0A79
    CallIf 1, SnowpointCity_03CE
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, SnowpointCity_03D8
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, SnowpointCity_040A
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, SnowpointCity_043C
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, SnowpointCity_046E
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, SnowpointCity_04A0
    CompareVarToValue VAR_0x8008, 5
    GoToIf 1, SnowpointCity_04D2
    CompareVarToValue VAR_0x8008, 6
    GoToIf 1, SnowpointCity_0504
    GoTo SnowpointCity_0536
SnowpointCity_Entry13:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 29
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SnowpointCity_053C
    GetPartyCount VAR_0x8001
    CountPartyMonsBelowLevelThreshold VAR_0x8002, 55
    SubVar VAR_0x8001, VAR_0x8002
    CompareVarToValue VAR_0x8001, 0
    GoToIf 2, SnowpointCity_0547
    Message 30
    CloseMessage
    Call SnowpointCity_0552
    End
SnowpointCity_Entry14:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    BufferItemName 0, ITEM_SUPER_ROD
    CheckFlag FLAG_RECEIVED_SUPER_ROD
    GoToIf 1, SnowpointCity_0674
    Message 34
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SnowpointCity_067F
    Message 35
    SetVarFromValue VAR_0x8004, 447
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetFlag FLAG_RECEIVED_SUPER_ROD
    Message 36
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_02DF:
    SetFlag FLAG_HIDE_SNOWPOINT_CITY_CANDICE
    End
SnowpointCity_02E5:
    CheckFlag FLAG_GAME_COMPLETED
    GoToIf 0, SnowpointCity_0308
    CompareVarToValue VAR_SNOWPOINT_CITY_STATE, 0
    GoToIf 1, SnowpointCity_056F
    Message 2
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_0308:
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_0313:
    CheckFlag FLAG_GAME_COMPLETED
    GoToIf 0, SnowpointCity_0324
    GoTo SnowpointCity_057E
SnowpointCity_0324:
    ApplyMovement 6, SnowpointCity_Movement_0692
    ApplyMovement LOCALID_PLAYER, SnowpointCity_Movement_069A
    WaitMovement
    ReleaseAll
    End
SnowpointCity_033A:
    Message 8
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_0345:
    Message 13
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_0350:
    CheckFlag FLAG_SAILED_TO_BATTLE_ZONE
    CallIf 0, SnowpointCity_0588
    Message 11
    CloseMessage
    Call SnowpointCity_05F1
    Call SnowpointCity_060B
    PlayBoatCutscene 2, 3, 188, 623, 434
    ReleaseAll
    End
SnowpointCity_037A:
    Message 12
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_0385:
    Message 20
    SetFlag FLAG_UNK_0x0A7F
    CloseMessage
    ReleaseAll
    End
SnowpointCity_0392:
    AddListMenuEntry 22, 0, 255
    Return
SnowpointCity_039C:
    AddListMenuEntry 23, 1, 255
    Return
SnowpointCity_03A6:
    AddListMenuEntry 24, 2, 255
    Return
SnowpointCity_03B0:
    AddListMenuEntry 25, 3, 255
    Return
SnowpointCity_03BA:
    AddListMenuEntry 26, 4, 255
    Return
SnowpointCity_03C4:
    AddListMenuEntry 27, 5, 255
    Return
SnowpointCity_03CE:
    AddListMenuEntry 28, 6, 255
    Return
SnowpointCity_03D8:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 45, 303, 757, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SnowpointCity_040A:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 65, 305, 531, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SnowpointCity_043C:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 86, 465, 698, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SnowpointCity_046E:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 442, 472, 539, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SnowpointCity_04A0:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 188, 647, 430, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SnowpointCity_04D2:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 450, 659, 339, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SnowpointCity_0504:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 457, 802, 473, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SnowpointCity_0536:
    CloseMessage
    ReleaseAll
    End
SnowpointCity_053C:
    Message 31
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_0547:
    Message 33
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_0552:
    StartTrainerBattle 214, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SnowpointCity_0625
    GoTo SnowpointCity_062B
SnowpointCity_056F:
    Message 0
    CloseMessage
    Call SnowpointCity_0636
    ReleaseAll
    End
SnowpointCity_057E:
    Call SnowpointCity_0636
    ReleaseAll
    End
SnowpointCity_0588:
    ClearFlag FLAG_HIDE_SNOWPOINT_CITY_CYNTHIA
    AddObject 10
    LockObject 10
    CloseMessage
    ApplyMovement 10, SnowpointCity_Movement_06A2
    WaitMovement
    Message 15
    ApplyMovement LOCALID_PLAYER, SnowpointCity_Movement_06B6
    WaitMovement
    CloseMessage
    ApplyMovement 10, SnowpointCity_Movement_06C2
    WaitMovement
    WaitTime 15, VAR_0x800C
    Message 16
    CloseMessage
    ApplyMovement 10, SnowpointCity_Movement_06CA
    WaitMovement
    Message 17
    CloseMessage
    ApplyMovement 10, SnowpointCity_Movement_06D6
    WaitMovement
    RemoveObject 10
    ApplyMovement LOCALID_PLAYER, SnowpointCity_Movement_06EA
    WaitMovement
    SetFlag FLAG_SAILED_TO_BATTLE_ZONE
    Return
SnowpointCity_05F1:
    ApplyMovement 8, SnowpointCity_Movement_06F2
    WaitMovement
    PlaySE SEQ_SE_DP_KAIDAN2_sseq
    ApplyMovement 8, SnowpointCity_Movement_06FE
    WaitMovement
    Return
SnowpointCity_060B:
    ApplyMovement LOCALID_PLAYER, SnowpointCity_Movement_0706
    WaitMovement
    PlaySE SEQ_SE_DP_KAIDAN2_sseq
    ApplyMovement LOCALID_PLAYER, SnowpointCity_Movement_06FE
    WaitMovement
    Return
SnowpointCity_0625:
    BlackOutFromBattle
    ReleaseAll
    End
SnowpointCity_062B:
    Message 32
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_0636:
    WaitTime 30, VAR_0x800C
    ClearFlag FLAG_HIDE_SNOWPOINT_CITY_CANDICE
    AddObject 7
    ApplyMovement 7, SnowpointCity_Movement_0712
    WaitMovement
    Message 3
    CloseMessage
    ApplyMovement LOCALID_PLAYER, SnowpointCity_Movement_071A
    ApplyMovement 6, SnowpointCity_Movement_0722
    WaitMovement
    SetVarFromValue VAR_SNOWPOINT_CITY_STATE, 1
    Message 4
    WaitButton
    CloseMessage
    Return
SnowpointCity_0674:
    Message 38
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_067F:
    Message 37
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCity_Movement_068A:
    WalkOnSpotNormalWest 1
    EndMovement

SnowpointCity_Movement_0692:
    WalkOnSpotNormalSouth 1
    EndMovement

SnowpointCity_Movement_069A:
    WalkNormalSouth 1
    EndMovement

SnowpointCity_Movement_06A2:
    WalkNormalWest 4
    WalkNormalSouth 2
    WalkNormalWest 6
    WalkNormalSouth 2
    EndMovement

SnowpointCity_Movement_06B6:
    EmoteExclamationMark 1
    WalkOnSpotNormalNorth 1
    EndMovement

SnowpointCity_Movement_06C2:
    WalkNormalEast 1
    EndMovement

SnowpointCity_Movement_06CA:
    WalkNormalWest 1
    WalkOnSpotNormalSouth 1
    EndMovement

SnowpointCity_Movement_06D6:
    WalkNormalNorth 2
    WalkNormalEast 3
    WalkNormalNorth 2
    WalkNormalEast 7
    EndMovement

SnowpointCity_Movement_06EA:
    WalkOnSpotNormalSouth 1
    EndMovement

SnowpointCity_Movement_06F2:
    FaceSouth 1
    Delay15 1
    EndMovement

SnowpointCity_Movement_06FE:
    SetInvisible 1
    EndMovement

SnowpointCity_Movement_0706:
    WalkNormalSouth 1
    Delay15 1
    EndMovement

SnowpointCity_Movement_0712:
    WalkNormalNorth 7
    EndMovement

SnowpointCity_Movement_071A:
    WalkOnSpotNormalSouth 1
    EndMovement

SnowpointCity_Movement_0722:
    FaceSouth 1
    EndMovement

