@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry CanalaveCity_Entry0
    ScriptEntry CanalaveCity_Entry1
    ScriptEntry CanalaveCity_Entry2
    ScriptEntry CanalaveCity_Entry3
    ScriptEntry CanalaveCity_Entry4
    ScriptEntry CanalaveCity_Entry5
    ScriptEntry CanalaveCity_Entry6
    ScriptEntry CanalaveCity_Entry7
    ScriptEntry CanalaveCity_Entry8
    ScriptEntry CanalaveCity_Entry9
    ScriptEntry CanalaveCity_Entry10
    ScriptEntry CanalaveCity_Entry11
    ScriptEntry CanalaveCity_Entry12
    ScriptEntry CanalaveCity_Entry13
    ScriptEntry CanalaveCity_Entry14
    ScriptEntry CanalaveCity_Entry15
    ScriptEntry CanalaveCity_Entry16
    ScriptEntry CanalaveCity_Entry17
    ScriptEntry CanalaveCity_Entry18
    ScriptEntry CanalaveCity_Entry19
    ScriptEntry CanalaveCity_Entry20
    ScriptEntry CanalaveCity_Entry21
    ScriptEntry CanalaveCity_Entry22
    ScriptEntry CanalaveCity_Entry23
    ScriptEntry CanalaveCity_Entry24
    ScriptEntry CanalaveCity_Entry25
    ScriptEntry CanalaveCity_Entry26
    ScriptEntryEnd

CanalaveCity_Entry0:
    SetFlag FLAG_HIDE_CELESTIC_TOWN_CYNTHIA
    CompareVarToValue VAR_DARKRAI_EVENT_STATE, 2
    CallIf 1, CanalaveCity_0580
    CompareVarToValue VAR_DARKRAI_EVENT_STATE, 3
    CallIf 1, CanalaveCity_0588
    Call CanalaveCity_059E
    CompareVarToValue VARS_START, 0
    CallIf 1, CanalaveCity_05EE
    CompareVarToValue VARS_START, 1
    CallIf 1, CanalaveCity_0600
    CompareVarToValue VAR_CANALAVE_CITY_STATE, 1
    CallIf 1, CanalaveCity_0606
    CompareVarToValue VAR_CANALAVE_CITY_STATE, 2
    CallIf 1, CanalaveCity_0606
    CompareVarToValue VAR_CANALAVE_CITY_STATE, 4
    CallIf 1, CanalaveCity_061C
    CompareVarToValue VAR_CANALAVE_CITY_STATE, 5
    CallIf 1, CanalaveCity_0632
    GetPlayerGender VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, CanalaveCity_0642
    CompareVarToValue VARS_START, 1
    GoToIf 1, CanalaveCity_064A
    End
CanalaveCity_Entry1:
    LockAll
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 723
    GoToIf 1, CanalaveCity_0652
    CompareVarToValue VAR_0x8005, 724
    GoToIf 1, CanalaveCity_0660
    CompareVarToValue VAR_0x8005, 725
    GoToIf 1, CanalaveCity_066E
    CompareVarToValue VAR_0x8005, 726
    GoToIf 1, CanalaveCity_067C
    CompareVarToValue VAR_0x8005, 727
    GoToIf 1, CanalaveCity_068A
    End
CanalaveCity_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_Entry3:
    LockAll
    BufferRivalName 0
    BufferPlayerName 1
    Message 2
    CloseMessage
    ApplyMovement 11, CanalaveCity_Movement_0A32
    ApplyMovement LOCALID_PLAYER, CanalaveCity_Movement_0A42
    WaitMovement
    RemoveObject 11
    SetVarFromValue VAR_CANALAVE_CITY_STATE, 3
    SetVarFromValue VAR_CANALAVE_LIBRARY_STATE, 1
    ReleaseAll
    End
CanalaveCity_Entry4:
    LockAll
    ApplyMovement 13, CanalaveCity_Movement_0A4E
    WaitMovement
    Message 5
    CloseMessage
    ClearFlag FLAG_HIDE_CANALAVE_CITY_SAILOR
    AddObject 14
    LockObject 14
    ApplyMovement 14, CanalaveCity_Movement_0A56
    WaitMovement
    Message 6
    CloseMessage
    ApplyMovement 14, CanalaveCity_Movement_0A62
    WaitMovement
    RemoveObject 14
    ApplyMovement 11, CanalaveCity_Movement_0A6A
    WaitMovement
    BufferRivalName 0
    Message 7
    CloseMessage
    ApplyMovement 11, CanalaveCity_Movement_0A72
    WaitMovement
    RemoveObject 11
    ApplyMovement 13, CanalaveCity_Movement_0A7E
    WaitMovement
    BufferRivalName 0
    BufferPlayerName 1
    Message 8
    CloseMessage
    ApplyMovement 12, CanalaveCity_Movement_0A8A
    WaitMovement
    WaitTime 15, VAR_0x800C
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveCity_0698
    GoTo CanalaveCity_06A4
CanalaveCity_Entry5:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 13
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_Entry6:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveCity_06AD
    GoTo CanalaveCity_06B6
CanalaveCity_Entry7:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_LAKE_VALOR_EXPLODED
    GoToIf 1, CanalaveCity_06BF
    Message 14
    GoTo CanalaveCity_06C8
CanalaveCity_Entry8:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_LAKE_VALOR_EXPLODED
    GoToIf 1, CanalaveCity_06D0
    CheckBadgeAcquired 5, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveCity_06D9
    GoTo CanalaveCity_06EF
CanalaveCity_Entry9:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_LAKE_VALOR_EXPLODED
    GoToIf 1, CanalaveCity_06F8
    Message 19
    GoTo CanalaveCity_06C8
CanalaveCity_Entry10:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_LAKE_VALOR_EXPLODED
    GoToIf 1, CanalaveCity_0701
    Message 21
    GoTo CanalaveCity_06C8
CanalaveCity_Entry11:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_LAKE_VALOR_EXPLODED
    GoToIf 1, CanalaveCity_070A
    PlayCry SPECIES_PSYDUCK, 0
    Message 23
    GoTo CanalaveCity_06C8
CanalaveCity_Entry12:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_LAKE_VALOR_EXPLODED
    GoToIf 1, CanalaveCity_0719
    Message 25
    GoTo CanalaveCity_06C8
CanalaveCity_Entry13:
    DrawSignpostInstantMessage 36, 0, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
CanalaveCity_Entry14:
    DrawSignpostTextBox 3, 0
    SetSignpostCommand 3
    WaitForSignpostDone
    DrawSignpostScrollingMessage 37, VAR_0x800C
    CallCommonScript 2000
    End
CanalaveCity_Entry15:
    DrawSignpostInstantMessage 38, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
CanalaveCity_Entry16:
    DrawSignpostInstantMessage 39, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
CanalaveCity_Entry17:
    DrawSignpostInstantMessage 40, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
CanalaveCity_Entry18:
    Call CanalaveCity_059E
    CompareVarToValue VARS_START, 0
    GoToIf 1, CanalaveCity_0722
    DrawSignpostTextBox 3, 0
    SetSignpostCommand 3
    WaitForSignpostDone
    DrawSignpostScrollingMessage 42, VAR_0x800C
    CallCommonScript 2000
    End
CanalaveCity_Entry19:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    GetPlayerDir VAR_0x8004
    FacePlayer
    CompareVarToValue VAR_LUNAR_WING_EVENT_STATE, 2
    GoToIf 1, CanalaveCity_Entry21
    Message 27
    InitGlobalTextMenu 1, 1, 0, VAR_0x800C, 1
    AddMenuEntryImm 213, 0
    CheckFlag FLAG_TALKED_TO_CANALAVE_CITY_SAILOR_ELDRITCH_HOUSE_LITTLE_BOY
    CallIf 1, CanalaveCity_0737
    CheckFlag FLAG_TRAVELED_TO_NEWMOON_ISLAND
    CallIf 1, CanalaveCity_073D
    AddMenuEntryImm 218, 4
    ShowMenu
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveCity_0743
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveCity_077E
    CompareVarToValue VAR_0x800C, 2
    GoToIf 1, CanalaveCity_07B9
    CompareVarToValue VAR_0x800C, 3
    GoToIf 1, CanalaveCity_07F4
    GoTo CanalaveCity_07F4
CanalaveCity_Entry20:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 43
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_Entry21:
    CheckItem ITEM_LUNAR_WING, 1, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveCity_07FF
    Message 31
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveCity_080A
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveCity_0815
    End
CanalaveCity_Entry22:
    LockAll
    ApplyMovement 16, CanalaveCity_Movement_0A92
    WaitMovement
    Message 35
    CloseMessage
    ApplyMovement 16, CanalaveCity_Movement_0AA2
    WaitMovement
    RemoveObject 16
    SetObjectEventPos 16, 45, 750
    SetObjectEventDir 16, 2
    SetObjectEventMovementType 16, 16
    AddObject 16
    SetVarFromValue VAR_DARKRAI_EVENT_STATE, 4
    ReleaseAll
    End
CanalaveCity_Entry23:
    Call CanalaveCity_059E
    CompareVarToValue VARS_START, 0
    CallIf 1, CanalaveCity_05EE
    End
CanalaveCity_Entry24:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckItem ITEM_HM04, 1, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveCity_0820
    FindPartySlotWithMove VAR_0x800C, MOVE_STRENGTH
    CompareVarToValue VAR_0x800C, 6
    GoToIf 5, CanalaveCity_0820
    BufferRivalName 0
    Message 3
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_Entry25:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A80
    GoToIf 0, CanalaveCity_085E
    Message 45
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveCity_086B
    GoTo CanalaveCity_089D
CanalaveCity_Entry26:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 46
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveCity_09EE
    GetPartyCount VAR_0x8001
    CountPartyMonsBelowLevelThreshold VAR_0x8002, 52
    SubVar VAR_0x8001, VAR_0x8002
    CompareVarToValue VAR_0x8001, 0
    GoToIf 2, CanalaveCity_0A27
    Message 47
    CloseMessage
    Call CanalaveCity_09F9
    End
CanalaveCity_0580:
    SetVarFromValue VAR_DARKRAI_EVENT_STATE, 0
    Return
CanalaveCity_0588:
    SetObjectEventPos 16, 55, 716
    SetObjectEventDir 16, 3
    SetObjectEventMovementType 16, 17
    Return
CanalaveCity_059E:
    CheckFlag FLAG_CAUGHT_DARKRAI
    GoToIf 1, CanalaveCity_08A3
    CheckFlag FLAG_GAME_COMPLETED
    GoToIf 0, CanalaveCity_08A3
    GetSetNationalDexEnabled 2, VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, CanalaveCity_08A3
    CheckItem ITEM_MEMBER_CARD, 1, VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, CanalaveCity_08A3
    CheckFlag FLAG_WOKE_UP_CANALAVE_CITY_SAILOR_ELDRITCH_HOUSE_LITTLE_BOY
    GoToIf 0, CanalaveCity_08A3
    SetVarFromValue VARS_START, 1
    Return
CanalaveCity_05EE:
    SetBgEventPos 0, 58, 713
    SetWarpEventPos 5, 59, 712
    Return
CanalaveCity_0600:
    ClearFlag FLAG_HIDE_NEWMOON_ISLAND_FOREST_DARKRAI
    Return
CanalaveCity_0606:
    SetObjectEventPos 11, 39, 733
    SetObjectEventDir 11, 0
    SetObjectEventMovementType 11, 14
    Return
CanalaveCity_061C:
    SetObjectEventPos 11, 37, 721
    SetObjectEventDir 11, 1
    SetObjectEventMovementType 11, 15
    Return
CanalaveCity_0632:
    SetFlag FLAG_HIDE_CANALAVE_CITY_PROF_ROWAN
    SetFlag FLAG_HIDE_CANALAVE_CITY_COUNTERPART
    SetVarFromValue VAR_CANALAVE_CITY_STATE, 6
    Return
CanalaveCity_0642:
    SetVarFromValue OBJ_GFX_VARS_START, 97
    End
CanalaveCity_064A:
    SetVarFromValue OBJ_GFX_VARS_START, 0
    End
CanalaveCity_0652:
    SetObjectEventPos 11, 38, 723
    GoTo CanalaveCity_08AB
CanalaveCity_0660:
    SetObjectEventPos 11, 38, 724
    GoTo CanalaveCity_08AB
CanalaveCity_066E:
    SetObjectEventPos 11, 38, 725
    GoTo CanalaveCity_08AB
CanalaveCity_067C:
    SetObjectEventPos 11, 38, 726
    GoTo CanalaveCity_08AB
CanalaveCity_068A:
    SetObjectEventPos 11, 38, 727
    GoTo CanalaveCity_08AB
CanalaveCity_0698:
    BufferPlayerName 0
    Message 9
    GoTo CanalaveCity_0900
CanalaveCity_06A4:
    Message 10
    GoTo CanalaveCity_0900
CanalaveCity_06AD:
    Message 11
    GoTo CanalaveCity_091A
CanalaveCity_06B6:
    Message 12
    GoTo CanalaveCity_091A
CanalaveCity_06BF:
    Message 15
    GoTo CanalaveCity_06C8
CanalaveCity_06C8:
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_06D0:
    Message 17
    GoTo CanalaveCity_06C8
CanalaveCity_06D9:
    CompareVarToValue VAR_CANALAVE_CITY_STATE, 5
    GoToIf 4, CanalaveCity_06EF
    Message 18
    GoTo CanalaveCity_06C8
CanalaveCity_06EF:
    Message 16
    GoTo CanalaveCity_06C8
CanalaveCity_06F8:
    Message 20
    GoTo CanalaveCity_06C8
CanalaveCity_0701:
    Message 22
    GoTo CanalaveCity_06C8
CanalaveCity_070A:
    PlayCry SPECIES_PSYDUCK, 0
    Message 24
    GoTo CanalaveCity_06C8
CanalaveCity_0719:
    Message 26
    GoTo CanalaveCity_06C8
CanalaveCity_0722:
    DrawSignpostTextBox 3, 0
    SetSignpostCommand 3
    WaitForSignpostDone
    DrawSignpostScrollingMessage 41, VAR_0x800C
    CallCommonScript 2000
    End
CanalaveCity_0737:
    AddMenuEntryImm 214, 1
    Return
CanalaveCity_073D:
    AddMenuEntryImm 215, 2
    Return
CanalaveCity_0743:
    Call CanalaveCity_0922
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, CanalaveCity_0941
    CompareVarToValue VAR_0x8004, 3
    CallIf 1, CanalaveCity_095B
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, CanalaveCity_0975
    PlayBoatCutscene 3, 3, 288, 100, 502
    ReleaseAll
    End
CanalaveCity_077E:
    Call CanalaveCity_0922
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, CanalaveCity_0941
    CompareVarToValue VAR_0x8004, 3
    CallIf 1, CanalaveCity_095B
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, CanalaveCity_0975
    PlayBoatCutscene 3, 2, 260, 39, 277
    ReleaseAll
    End
CanalaveCity_07B9:
    Call CanalaveCity_0922
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, CanalaveCity_0941
    CompareVarToValue VAR_0x8004, 3
    CallIf 1, CanalaveCity_095B
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, CanalaveCity_0975
    PlayBoatCutscene 3, 3, 320, 152, 277
    ReleaseAll
    End
CanalaveCity_07F4:
    Message 29
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_07FF:
    Message 34
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_080A:
    Message 32
    CloseMessage
    GoTo CanalaveCity_077E
CanalaveCity_0815:
    Message 33
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_0820:
    BufferRivalName 0
    Message 4
    CloseMessage
    ApplyMovement 18, CanalaveCity_Movement_0AB2
    WaitMovement
    LoadDoorAnimation 1, 22, 5, 14, 77
    PlayDoorOpenAnimation 77
    WaitForAnimation 77
    ApplyMovement 18, CanalaveCity_Movement_0ABA
    WaitMovement
    PlayDoorCloseAnimation 77
    WaitForAnimation 77
    UnloadAnimation 77
    RemoveObject 18
    ReleaseAll
    End
CanalaveCity_085E:
    Message 44
    SetFlag FLAG_UNK_0x0A80
    CloseMessage
    ReleaseAll
    End
CanalaveCity_086B:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 3, 180, 777, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
CanalaveCity_089D:
    CloseMessage
    ReleaseAll
    End
CanalaveCity_08A3:
    SetVarFromValue VARS_START, 0
    Return
CanalaveCity_08AB:
    SetObjectEventMovementType 11, 17
    ClearFlag FLAG_HIDE_CANALAVE_CITY_RIVAL_BRIDGE
    AddObject 11
    ApplyMovement 11, CanalaveCity_Movement_0AC6
    WaitMovement
    CallCommonScript 2042
    ApplyMovement 11, CanalaveCity_Movement_0ADA
    WaitMovement
    BufferRivalName 0
    BufferPlayerName 1
    Message 0
    CloseMessage
    GetPlayerStarterSpecies VAR_0x800C
    CompareVarToValue VAR_0x800C, 387
    GoToIf 1, CanalaveCity_098F
    CompareVarToValue VAR_0x800C, 390
    GoToIf 1, CanalaveCity_099B
    GoTo CanalaveCity_09A7
CanalaveCity_0900:
    WaitButton
    CloseMessage
    SetVarFromValue VAR_CANALAVE_CITY_STATE, 5
    ClearFlag FLAG_HIDE_LAKE_VERITY_LOW_WATER_COUNTERPART
    ClearFlag FLAG_HIDE_LAKE_VERITY_LOW_WATER_PROF_ROWAN
    ClearFlag FLAG_HIDE_LAKE_ACUITY_LOW_WATER_RIVAL
    ReleaseAll
    End
CanalaveCity_091A:
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_0922:
    Message 28
    CloseMessage
    ApplyMovement 16, CanalaveCity_Movement_0AE2
    WaitMovement
    PlaySE SEQ_SE_DP_KAIDAN2_sseq
    ApplyMovement 16, CanalaveCity_Movement_0AEE
    WaitMovement
    Return
CanalaveCity_0941:
    ApplyMovement LOCALID_PLAYER, CanalaveCity_Movement_0AF6
    WaitMovement
    PlaySE SEQ_SE_DP_KAIDAN2_sseq
    ApplyMovement LOCALID_PLAYER, CanalaveCity_Movement_0AEE
    WaitMovement
    Return
CanalaveCity_095B:
    ApplyMovement LOCALID_PLAYER, CanalaveCity_Movement_0B06
    WaitMovement
    PlaySE SEQ_SE_DP_KAIDAN2_sseq
    ApplyMovement LOCALID_PLAYER, CanalaveCity_Movement_0AEE
    WaitMovement
    Return
CanalaveCity_0975:
    ApplyMovement LOCALID_PLAYER, CanalaveCity_Movement_0B12
    WaitMovement
    PlaySE SEQ_SE_DP_KAIDAN2_sseq
    ApplyMovement LOCALID_PLAYER, CanalaveCity_Movement_0AEE
    WaitMovement
    Return
CanalaveCity_098F:
    StartTrainerBattle 477, 0
    GoTo CanalaveCity_09B3
CanalaveCity_099B:
    StartTrainerBattle 478, 0
    GoTo CanalaveCity_09B3
CanalaveCity_09A7:
    StartTrainerBattle 476, 0
    GoTo CanalaveCity_09B3
CanalaveCity_09B3:
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveCity_09E4
    BufferRivalName 0
    Message 1
    CloseMessage
    ApplyMovement 11, CanalaveCity_Movement_0B22
    WaitMovement
    RemoveObject 11
    SetVarFromValue VAR_CANALAVE_CITY_STATE, 1
    ReleaseAll
    End
CanalaveCity_09E4:
    SetFlag FLAG_HIDE_CANALAVE_CITY_RIVAL_BRIDGE
    BlackOutFromBattle
    ReleaseAll
    End
CanalaveCity_09EE:
    Message 48
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_09F9:
    StartTrainerBattle 213, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveCity_0A16
    GoTo CanalaveCity_0A1C
CanalaveCity_0A16:
    BlackOutFromBattle
    ReleaseAll
    End
CanalaveCity_0A1C:
    Message 49
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_0A27:
    Message 50
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveCity_Movement_0A32:
    WalkFastSouth 1
    WalkFastWest 5
    WalkFastNorth 10
    EndMovement

CanalaveCity_Movement_0A42:
    Delay8 1
    WalkOnSpotNormalWest 1
    EndMovement

CanalaveCity_Movement_0A4E:
    WalkOnSpotNormalSouth 1
    EndMovement

CanalaveCity_Movement_0A56:
    WalkFastWest 5
    WalkFastNorth 2
    EndMovement

CanalaveCity_Movement_0A62:
    WalkFastSouth 6
    EndMovement

CanalaveCity_Movement_0A6A:
    WalkOnSpotNormalNorth 1
    EndMovement

CanalaveCity_Movement_0A72:
    WalkFastSouth 3
    WalkFastEast 9
    EndMovement

CanalaveCity_Movement_0A7E:
    Delay8 2
    WalkOnSpotNormalNorth 1
    EndMovement

CanalaveCity_Movement_0A8A:
    WalkOnSpotNormalWest 1
    EndMovement

CanalaveCity_Movement_0A92:
    EmoteExclamationMark 1
    WalkNormalEast 3
    WalkNormalNorth 1
    EndMovement

CanalaveCity_Movement_0AA2:
    WalkNormalSouth 1
    WalkNormalWest 3
    WalkNormalSouth 8
    EndMovement

CanalaveCity_Movement_0AB2:
    WalkOnSpotNormalNorth 1
    EndMovement

CanalaveCity_Movement_0ABA:
    WalkNormalNorth 1
    SetInvisible 1
    EndMovement

CanalaveCity_Movement_0AC6:
    WalkFastEast 4
    Delay8 1
    EmoteExclamationMark 1
    Delay8 1
    EndMovement

CanalaveCity_Movement_0ADA:
    WalkFastEast 4
    EndMovement

CanalaveCity_Movement_0AE2:
    FaceEast 1
    Delay15 1
    EndMovement

CanalaveCity_Movement_0AEE:
    SetInvisible 1
    EndMovement

CanalaveCity_Movement_0AF6:
    WalkNormalSouth 1
    FaceEast 1
    Delay15 1
    EndMovement

CanalaveCity_Movement_0B06:
    WalkNormalEast 1
    Delay15 1
    EndMovement

CanalaveCity_Movement_0B12:
    WalkNormalNorth 1
    FaceEast 1
    Delay15 1
    EndMovement

CanalaveCity_Movement_0B22:
    WalkFastWest 9
    EndMovement

