@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry JubilifeCitySouthHouse1f_Entry0
    ScriptEntry JubilifeCitySouthHouse1f_Entry1
    ScriptEntry JubilifeCitySouthHouse1f_Entry2
    ScriptEntryEnd

@ Oxide: the gift clown that stood here is gone (Ian, 2026-09-27; the encounter track's
@ clown-replacements.md): its object, its script entry and its lines, with the
@ orphaned pick-menu names. Where the town had no other capture, new grass
@ outside takes its place.

JubilifeCitySouthHouse1f_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 0
    WaitButton
    CloseMessage
    ReleaseAll
    End
JubilifeCitySouthHouse1f_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
JubilifeCitySouthHouse1f_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    WaitSE SE_CONFIRM_sseq_3
    PlayCry SPECIES_PACHIRISU, 0
    Message 2
    WaitCry
    WaitButton
    CloseMessage
    ReleaseAll
    End

    .balign 4, 0

