@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry TwinleafTownPlayerHouse1f_Entry0
    ScriptEntry TwinleafTownPlayerHouse1f_Entry1
    ScriptEntry TwinleafTownPlayerHouse1f_Entry2
    ScriptEntry TwinleafTownPlayerHouse1f_Entry3
    ScriptEntry TwinleafTownPlayerHouse1f_Entry4
    ScriptEntry TwinleafTownPlayerHouse1f_Entry5
    ScriptEntry TwinleafTownPlayerHouse1f_Entry6
    ScriptEntry TwinleafTownPlayerHouse1f_Entry7
    ScriptEntry TwinleafTownPlayerHouse1f_Entry8
    ScriptEntry TwinleafTownPlayerHouse1f_Entry9
    ScriptEntry TwinleafTownPlayerHouse1f_Entry10
    ScriptEntryEnd

TwinleafTownPlayerHouse1f_Entry0:
    CompareVarToValue VAR_PLAYER_HOUSE_STATE, 3
    CallIf 1, TwinleafTownPlayerHouse1f_026C
    CheckFlag FLAG_RECEIVED_PARCEL
    CallIf 1, TwinleafTownPlayerHouse1f_0282
    End
TwinleafTownPlayerHouse1f_Entry1:
    LockAll
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_07BC
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_07C8
    WaitMovement
    SetFlag FLAG_TALKED_TO_MOM
    BufferPlayerName 0
    BufferRivalName 1
    Message 0
    CloseMessage
    WaitTime 15, VAR_0x800C
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_07E4
    WaitMovement
    SetVarFromValue VAR_PLAYER_HOUSE_STATE, 1
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_Entry2:
    LockAll
    WaitTime 30, VAR_0x800C
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_07F8
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_081C
    WaitMovement
    WaitTime 30, VAR_0x800C
    BufferRivalName 0
    BufferPlayerName 1
    Message 6
    CloseMessage
    WaitTime 30, VAR_0x800C
    BufferPlayerName 0
    Message 7
    GiveRunningShoes
    BufferPlayerName 0
    Message 8
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    Message 9
    WaitButton
    CloseMessage
    SetVarFromValue VAR_PLAYER_HOUSE_STATE, 4
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_MAP_LOCAL_0x02
    GoToIf 1, TwinleafTownPlayerHouse1f_0288
    CompareVarToValue VAR_PLAYER_HOUSE_STATE, 7
    GoToIf 4, TwinleafTownPlayerHouse1f_029B
    CompareVarToValue VAR_PLAYER_HOUSE_STATE, 6
    GoToIf 1, TwinleafTownPlayerHouse1f_02A5
    CheckFlag FLAG_HAS_POKEDEX
    GoToIf 1, TwinleafTownPlayerHouse1f_02B3
    CompareVarToValue VAR_PLAYER_HOUSE_STATE, 5
    GoToIf 4, TwinleafTownPlayerHouse1f_02EB
    CompareVarToValue VAR_PLAYER_HOUSE_STATE, 4
    GoToIf 4, TwinleafTownPlayerHouse1f_02F5
    CheckFlag FLAG_MOM_WARNED_PLAYER
    GoToIf 1, TwinleafTownPlayerHouse1f_0300
    CompareVarToValue VAR_PLAYER_HOUSE_STATE, 2
    GoToIf 4, TwinleafTownPlayerHouse1f_030E
    CheckFlag FLAG_TALKED_TO_MOM
    GoToIf 1, TwinleafTownPlayerHouse1f_0320
    SetFlag FLAG_TALKED_TO_MOM
    BufferPlayerName 0
    BufferRivalName 1
    Message 0
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_Entry4:
    LockAll
    GoTo TwinleafTownPlayerHouse1f_032E
TwinleafTownPlayerHouse1f_Entry5:
    BufferRivalName 1
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 26
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_Entry6:
    GetTimeOfDay VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, TwinleafTownPlayerHouse1f_0346
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, TwinleafTownPlayerHouse1f_0357
    CompareVarToValue VAR_0x800C, 2
    GoToIf 1, TwinleafTownPlayerHouse1f_0357
    CompareVarToValue VAR_0x800C, 3
    GoToIf 1, TwinleafTownPlayerHouse1f_0368
    CompareVarToValue VAR_0x800C, 4
    GoToIf 1, TwinleafTownPlayerHouse1f_0368
    End
TwinleafTownPlayerHouse1f_Entry7:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 32
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_Entry8:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 33
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_Entry9:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 34
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_Entry10:
    LockAll
    SetVarFromValue VAR_PLAYER_HOUSE_POSTGAME_STATE, 2
    CheckFlag FLAG_TALKED_TO_MOM_ABOUT_RIVAL_SNOWPOINT_CITY
    GoToIf 1, TwinleafTownPlayerHouse1f_0379
    CheckFlag FLAG_TALKED_TO_MOM_ABOUT_NATIONAL_DEX_PROGRESS
    GoToIf 0, TwinleafTownPlayerHouse1f_037D
    GetSetNationalDexEnabled 2, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, TwinleafTownPlayerHouse1f_0379
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_0838
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_0844
    WaitMovement
    BufferPlayerName 0
    BufferRivalName 1
    GetSetNationalDexEnabled 2, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    CallIf 1, TwinleafTownPlayerHouse1f_03BC
    CompareVarToValue VAR_0x800C, 0
    CallIf 1, TwinleafTownPlayerHouse1f_03C5
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_026C:
    SetObjectEventPos 0, 2, 4
    SetObjectEventDir 0, 0
    SetObjectEventMovementType 0, 14
    Return
TwinleafTownPlayerHouse1f_0282:
    SetFlag FLAG_HIDE_TWINLEAF_TOWN_PLAYER_HOUSE_1F_RIVAL_MOM
    Return
TwinleafTownPlayerHouse1f_0288:
    CompareVarToValue VAR_CANALAVE_LIBRARY_STATE, 2
    GoToIf 4, TwinleafTownPlayerHouse1f_03CE
    GoTo TwinleafTownPlayerHouse1f_03E7
TwinleafTownPlayerHouse1f_029B:
    Call TwinleafTownPlayerHouse1f_0423
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_02A5:
    BufferPlayerName 0
    Message 28
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_02B3:
    Call TwinleafTownPlayerHouse1f_0423
    BufferPlayerName 0
    Message 15
    SetVarFromValue VAR_0x8004, 433
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    GiveJournal
    Message 16
    GetPlayerDir VAR_0x8007
    CompareVarToValue VAR_0x8007, 1
    GoToIf 1, TwinleafTownPlayerHouse1f_0493
    GoTo TwinleafTownPlayerHouse1f_04A3
TwinleafTownPlayerHouse1f_02EB:
    Call TwinleafTownPlayerHouse1f_0423
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_02F5:
    Message 10
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_0300:
    BufferRivalName 0
    Message 5
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_030E:
    SetFlag FLAG_MOM_WARNED_PLAYER
    BufferPlayerName 0
    Message 2
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_0320:
    BufferRivalName 0
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_032E:
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_0850
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_085C
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_04B3
TwinleafTownPlayerHouse1f_0346:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 29
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_0357:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 30
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_0368:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 31
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_0379:
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_037D:
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_0838
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_0844
    WaitMovement
    BufferPlayerName 0
    BufferRivalName 1
    GetSetNationalDexEnabled 2, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    CallIf 1, TwinleafTownPlayerHouse1f_03BC
    CompareVarToValue VAR_0x800C, 0
    CallIf 1, TwinleafTownPlayerHouse1f_03C5
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_03BC:
    SetFlag FLAG_TALKED_TO_MOM_ABOUT_RIVAL_SNOWPOINT_CITY
    Message 35
    Return
TwinleafTownPlayerHouse1f_03C5:
    SetFlag FLAG_TALKED_TO_MOM_ABOUT_NATIONAL_DEX_PROGRESS
    Message 36
    Return
TwinleafTownPlayerHouse1f_03CE:
    CompareVarToValue VAR_EXITED_DISTORTION_WORLD_STATE, 2
    GoToIf 4, TwinleafTownPlayerHouse1f_03E7
    BufferPlayerName 0
    Message 41
    GoTo TwinleafTownPlayerHouse1f_04C7
TwinleafTownPlayerHouse1f_03E7:
    GetRandom VAR_0x800C, 4
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, TwinleafTownPlayerHouse1f_04CF
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, TwinleafTownPlayerHouse1f_04DB
    CompareVarToValue VAR_0x800C, 2
    GoToIf 1, TwinleafTownPlayerHouse1f_04E7
    CompareVarToValue VAR_0x800C, 3
    GoToIf 1, TwinleafTownPlayerHouse1f_04F3
    End
TwinleafTownPlayerHouse1f_0423:
    BufferPlayerName 0
    GetTimeOfDay VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    CallIf 1, TwinleafTownPlayerHouse1f_0502
    CompareVarToValue VAR_0x800C, 1
    CallIf 1, TwinleafTownPlayerHouse1f_0507
    CompareVarToValue VAR_0x800C, 2
    CallIf 1, TwinleafTownPlayerHouse1f_050C
    CompareVarToValue VAR_0x800C, 3
    CallIf 1, TwinleafTownPlayerHouse1f_0511
    CompareVarToValue VAR_0x800C, 4
    CallIf 1, TwinleafTownPlayerHouse1f_0516
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    PlayFanfare SEQ_ASA_sseq
    WaitFanfare
    HealParty
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    SetFlag FLAG_MAP_LOCAL_0x02
    Return
TwinleafTownPlayerHouse1f_0493:
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_0864
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_051B
TwinleafTownPlayerHouse1f_04A3:
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_086C
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_051B
TwinleafTownPlayerHouse1f_04B3:
    SetVarFromValue VAR_PLAYER_HOUSE_STATE, 2
    BufferPlayerName 0
    Message 4
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_04C7:
    WaitButton
    CloseMessage
    ReleaseAll
    End
TwinleafTownPlayerHouse1f_04CF:
    BufferPlayerName 0
    Message 37
    GoTo TwinleafTownPlayerHouse1f_04C7
TwinleafTownPlayerHouse1f_04DB:
    BufferPlayerName 0
    Message 38
    GoTo TwinleafTownPlayerHouse1f_04C7
TwinleafTownPlayerHouse1f_04E7:
    BufferPlayerName 0
    Message 39
    GoTo TwinleafTownPlayerHouse1f_04C7
TwinleafTownPlayerHouse1f_04F3:
    BufferPlayerName 0
    BufferRivalName 1
    Message 40
    GoTo TwinleafTownPlayerHouse1f_04C7
TwinleafTownPlayerHouse1f_0502:
    Message 11
    Return
TwinleafTownPlayerHouse1f_0507:
    Message 12
    Return
TwinleafTownPlayerHouse1f_050C:
    Message 12
    Return
TwinleafTownPlayerHouse1f_0511:
    Message 13
    Return
TwinleafTownPlayerHouse1f_0516:
    Message 14
    Return
TwinleafTownPlayerHouse1f_051B:
    Message 17
    FacePlayer
    BufferPlayerName 0
    Message 18
    CloseMessage
    PlaySE SEQ_SE_DP_DOOR_OPEN_sseq
    ClearFlag FLAG_HIDE_TWINLEAF_TOWN_PLAYER_HOUSE_1F_RIVAL_MOM
    AddObject 1
    WaitSE SEQ_SE_DP_DOOR_OPEN_sseq
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_0874
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_0880
    WaitMovement
    ApplyMovement 1, TwinleafTownPlayerHouse1f_Movement_0888
    WaitMovement
    CompareVarToValue VAR_0x8007, 0
    CallIf 1, TwinleafTownPlayerHouse1f_05B6
    BufferRivalName 1
    Message 19
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_0894
    WaitMovement
    Message 20
    BufferRivalName 1
    Message 21
    BufferPlayerName 0
    Message 22
    CompareVarToValue VAR_0x8007, 0
    GoToIf 1, TwinleafTownPlayerHouse1f_05C2
    CompareVarToValue VAR_0x8007, 1
    GoToIf 1, TwinleafTownPlayerHouse1f_05DA
    CompareVarToValue VAR_0x8007, 2
    GoToIf 1, TwinleafTownPlayerHouse1f_05F2
    CompareVarToValue VAR_0x8007, 3
    GoToIf 1, TwinleafTownPlayerHouse1f_060A
    End
TwinleafTownPlayerHouse1f_05B6:
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_089C
    WaitMovement
    Return
TwinleafTownPlayerHouse1f_05C2:
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_08A4
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_08AC
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_0622
TwinleafTownPlayerHouse1f_05DA:
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_08B4
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_08BC
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_0622
TwinleafTownPlayerHouse1f_05F2:
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_08C4
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_08CC
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_0622
TwinleafTownPlayerHouse1f_060A:
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_08D4
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_08DC
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_0622
TwinleafTownPlayerHouse1f_0622:
    Message 23
    CloseMessage
    CompareVarToValue VAR_0x8007, 0
    GoToIf 1, TwinleafTownPlayerHouse1f_065D
    CompareVarToValue VAR_0x8007, 1
    GoToIf 1, TwinleafTownPlayerHouse1f_0675
    CompareVarToValue VAR_0x8007, 2
    GoToIf 1, TwinleafTownPlayerHouse1f_068D
    CompareVarToValue VAR_0x8007, 3
    GoToIf 1, TwinleafTownPlayerHouse1f_06A5
    End
TwinleafTownPlayerHouse1f_065D:
    ApplyMovement 1, TwinleafTownPlayerHouse1f_Movement_08E4
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_08EC
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_06BD
TwinleafTownPlayerHouse1f_0675:
    ApplyMovement 1, TwinleafTownPlayerHouse1f_Movement_08F4
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_0900
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_06BD
TwinleafTownPlayerHouse1f_068D:
    ApplyMovement 1, TwinleafTownPlayerHouse1f_Movement_090C
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_0918
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_06BD
TwinleafTownPlayerHouse1f_06A5:
    ApplyMovement 1, TwinleafTownPlayerHouse1f_Movement_0924
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_092C
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_06BD
TwinleafTownPlayerHouse1f_06BD:
    BufferPlayerName 0
    BufferRivalName 1
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, TwinleafTownPlayerHouse1f_06DA
    GoTo TwinleafTownPlayerHouse1f_06E3
TwinleafTownPlayerHouse1f_06DA:
    Message 24
    GoTo TwinleafTownPlayerHouse1f_06EC
TwinleafTownPlayerHouse1f_06E3:
    Message 25
    GoTo TwinleafTownPlayerHouse1f_06EC
TwinleafTownPlayerHouse1f_06EC:
    SetVarFromValue VAR_0x8004, 459
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetFlag FLAG_RECEIVED_PARCEL
    Message 27
    BufferRivalName 1
    Message 26
    CloseMessage
    CompareVarToValue VAR_0x8007, 0
    GoToIf 1, TwinleafTownPlayerHouse1f_0741
    CompareVarToValue VAR_0x8007, 1
    GoToIf 1, TwinleafTownPlayerHouse1f_0759
    CompareVarToValue VAR_0x8007, 2
    GoToIf 1, TwinleafTownPlayerHouse1f_0779
    CompareVarToValue VAR_0x8007, 3
    GoToIf 1, TwinleafTownPlayerHouse1f_0791
    End
TwinleafTownPlayerHouse1f_0741:
    ApplyMovement 1, TwinleafTownPlayerHouse1f_Movement_0934
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_0940
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_07A9
TwinleafTownPlayerHouse1f_0759:
    ApplyMovement 1, TwinleafTownPlayerHouse1f_Movement_0948
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_0954
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_095C
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_07A9
TwinleafTownPlayerHouse1f_0779:
    ApplyMovement 1, TwinleafTownPlayerHouse1f_Movement_0968
    ApplyMovement 0, TwinleafTownPlayerHouse1f_Movement_0978
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_07A9
TwinleafTownPlayerHouse1f_0791:
    ApplyMovement 1, TwinleafTownPlayerHouse1f_Movement_0980
    ApplyMovement LOCALID_PLAYER, TwinleafTownPlayerHouse1f_Movement_098C
    WaitMovement
    GoTo TwinleafTownPlayerHouse1f_07A9
TwinleafTownPlayerHouse1f_07A9:
    PlaySE SEQ_SE_DP_KAIDAN2_sseq
    RemoveObject 1
    SetVarFromValue VAR_PLAYER_HOUSE_STATE, 6
    ReleaseAll
    End
    .balign 4, 0

TwinleafTownPlayerHouse1f_Movement_07BC:
    Delay4 1
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_07C8:
    WalkOnSpotNormalNorth 1
    EmoteExclamationMark 1
    Delay8 1
    WalkNormalNorth 1
    WalkNormalEast 3
    WalkNormalNorth 3
    EndMovement

TwinleafTownPlayerHouse1f_Movement_07E4:
    WalkNormalSouth 2
    WalkNormalWest 3
    WalkNormalSouth 2
    WalkOnSpotNormalNorth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_07F8:
    WalkNormalWest 1
    FaceNorth 1
    Delay8 2
    WalkNormalEast 3
    WalkNormalSouth 2
    WalkNormalEast 3
    WalkNormalSouth 2
    WalkOnSpotNormalWest 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_081C:
    Delay8 4
    WalkOnSpotNormalEast 1
    Delay8 4
    WalkNormalEast 3
    WalkNormalSouth 2
    WalkNormalEast 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0838:
    Delay4 1
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0844:
    WalkOnSpotNormalNorth 1
    EmoteExclamationMark 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0850:
    Delay8 2
    WalkOnSpotNormalNorth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_085C:
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0864:
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_086C:
    WalkOnSpotNormalNorth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0874:
    WalkOnSpotNormalSouth 1
    EmoteExclamationMark 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0880:
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0888:
    WalkNormalNorth 1
    WalkOnSpotNormalEast 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0894:
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_089C:
    WalkOnSpotNormalWest 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08A4:
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08AC:
    WalkOnSpotNormalNorth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08B4:
    WalkOnSpotNormalNorth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08BC:
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08C4:
    WalkOnSpotNormalEast 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08CC:
    WalkOnSpotNormalWest 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08D4:
    WalkOnSpotNormalWest 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08DC:
    WalkOnSpotNormalEast 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08E4:
    WalkOnSpotNormalEast 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08EC:
    WalkOnSpotNormalWest 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_08F4:
    WalkNormalNorth 2
    WalkOnSpotNormalEast 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0900:
    Delay8 2
    WalkOnSpotNormalWest 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_090C:
    WalkNormalEast 2
    WalkOnSpotNormalNorth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0918:
    Delay8 2
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0924:
    WalkOnSpotNormalNorth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_092C:
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0934:
    WalkNormalSouth 1
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0940:
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0948:
    WalkNormalSouth 3
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0954:
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_095C:
    Delay8 1
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0968:
    WalkNormalWest 2
    WalkNormalSouth 1
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0978:
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_0980:
    WalkNormalSouth 1
    WalkOnSpotNormalSouth 1
    EndMovement

TwinleafTownPlayerHouse1f_Movement_098C:
    WalkOnSpotNormalSouth 1
    EndMovement

