@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry Common_Entry0
    ScriptEntry Common_Entry1
    ScriptEntry Common_Entry2
    ScriptEntry Common_Entry3
    ScriptEntry Common_Entry4
    ScriptEntry Common_Entry5
    ScriptEntry Common_Entry6
    ScriptEntry Common_Entry7
    ScriptEntry Common_Entry8
    ScriptEntry Common_Entry9
    ScriptEntry Common_Entry10
    ScriptEntry Common_Entry11
    ScriptEntry Common_Entry12
    ScriptEntry Common_Entry13
    ScriptEntry Common_Entry14
    ScriptEntry Common_Entry15
    ScriptEntry Common_Entry16
    ScriptEntry Common_Entry17
    ScriptEntry Common_Entry18
    ScriptEntry Common_Entry19
    ScriptEntry Common_Entry20
    ScriptEntry Common_Entry21
    ScriptEntry Common_Entry22
    ScriptEntry Common_Entry23
    ScriptEntry Common_Entry24
    ScriptEntry Common_Entry25
    ScriptEntry Common_Entry26
    ScriptEntry Common_Entry27
    ScriptEntry Common_Entry28
    ScriptEntry Common_Entry29
    ScriptEntry Common_Entry30
    ScriptEntry Common_Entry31
    ScriptEntry Common_Entry32
    ScriptEntry Common_Entry33
    ScriptEntry Common_Entry34
    ScriptEntry Common_Entry35
    ScriptEntry Common_Entry36
    ScriptEntry Common_Entry37
    ScriptEntry Common_Entry38
    ScriptEntry Common_Entry39
    ScriptEntry Common_Entry40
    ScriptEntry Common_Entry41
    ScriptEntry Common_Entry42
    ScriptEntry Common_Entry41
    ScriptEntry Common_Entry44
    ScriptEntry Common_Entry45
    ScriptEntry Common_Entry46
    ScriptEntry Common_Entry47
    ScriptEntry Common_Entry48
    ScriptEntry Common_Entry41
    ScriptEntry Common_Entry50
    ScriptEntry Common_Entry51
    ScriptEntry Common_Entry52
    ScriptEntry Common_Entry53
    ScriptEntry Common_Entry54
    ScriptEntry Common_Entry55
    ScriptEntry Common_Entry41
    ScriptEntry Common_Entry57
    ScriptEntry Common_Entry58
    ScriptEntryEnd

Common_Entry0:
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Common_0717
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_071E
    GetSignpostInput VAR_0x800C
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_071E
    SetSignpostCommand 2
    ReturnCommonScript
    End
Common_Entry1:
    Call Common_0729
    ReturnCommonScript
    End
Common_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    GetTrainerCardLevel VAR_0x800C
    CompareVarToValue VAR_0x800C, 4
    GoToIf 4, Common_079F
    SetVarFromValue VAR_0x8004, 0
    GetTimeOfDay VAR_0x800C
    Dummy1F9 32780
    SetVarFromValue VAR_0x8004, 120
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_07D5
    SetVarFromValue VAR_0x8004, 121
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_07D5
    SetVarFromValue VAR_0x8004, 0
    MessageVar VAR_0x8004
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_07F9
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_083E
    End
Common_Entry3:
    LockAll
    GetPartyCount VAR_0x8004
    SetVarFromValue VAR_0x8005, 0
    SurvivePoison VAR_0x800C, 32773
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_084B
    BufferPartyMonNickname 0, 32773
    Message 66
    AddVar VAR_0x8005, 1
    CompareVarToVar VAR_0x8004, VAR_0x8005
    GoToIf 5, Common_0877
    CountAliveMonsExcept VAR_0x800C, 6
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_08BE
    CloseMessage
    ReleaseAll
    End
Common_Entry4:
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    WaitABPress
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    End
Common_Entry5:
    ClearFlag FLAG_MAP_LOCAL_SAVE_EXTRA_BLOCK
    Call Common_08E0
    StoreSaveResult 32780
    CloseMessage
    End
Common_Entry6:
    SetFlag FLAG_MAP_LOCAL_SAVE_EXTRA_BLOCK
    Call Common_08E0
    SetVarFromVar VARS_START, VAR_0x800C
    ReturnCommonScript
    End
Common_Entry7:
    End
Common_Entry8:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CheckItem ITEM_HONEY, 1, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 5, Common_0934
    GetHoneyTreeStatus VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_0961
    CompareVarToValue VAR_0x800C, 2
    GoToIf 1, Common_096C
    CompareVarToValue VAR_0x800C, 3
    GoToIf 1, Common_097D
    End
Common_Entry9:
    Call Common_099C
    ReturnCommonScript
    End
Common_Entry10:
    End
Common_Entry11:
    End
Common_Entry12:
    Call Common_0AFB
    Message 109
    WaitButton
    ReturnCommonScript
    End
Common_Entry13:
    Call Common_0B18
    ReturnCommonScript
    End
Common_Entry14:
    Call Common_0B30
    ReturnCommonScript
    End
Common_Entry15:
    Call Common_0B4D
    Message 31
    WaitButton
    ReturnCommonScript
    End
Common_Entry16:
    Call Common_0B6B
    ReturnCommonScript
    End
Common_Entry17:
    Call Common_0BA0
    ReturnCommonScript
    End
Common_Entry18:
    LockAll
    PlaySE SEQ_SE_DP_PC_ON_sseq
    Call Common_0BA7
    BufferPlayerName 0
    Message 32
    GoTo Common_0BB2
Common_Entry19:
    Message 37
    ReturnCommonScript
    End
Common_Entry20:
    LockAll
    ApplyMovement LOCALID_PLAYER, Common_Movement_3002
    ApplyMovement 0, Common_Movement_300A
    WaitMovement
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    BufferPlayerName 0
    Message 40
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    CloseMessage
    PlayFanfare SEQ_ASA_sseq
    WaitFanfare
    HealParty
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CheckFlag FLAG_HAS_POKEDEX
    CallIf 1, Common_0C56
    CheckFlag FLAG_HAS_POKEDEX
    CallIf 0, Common_0C5B
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_Entry21:
    LockAll
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    SetPlayerState 256
    ChangePlayerState
    ApplyMovement LOCALID_PLAYER, Common_Movement_3012
    WaitMovement
    Message 43
    Call Common_0C60
    Call Common_0D56
    CheckBadgeAcquired 0, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_0D76
    Message 44
    ApplyMovement LOCALID_PLAYER, Common_Movement_301A
    WaitMovement
    SetPlayerState 1
    ChangePlayerState
    ApplyMovement 32775, Common_Movement_3022
    WaitMovement
    Message 45
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_Entry22:
    End
Common_Entry23:
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    OpenSealCapsuleEditor
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    End
Common_Entry24:
    End
Common_Entry25:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    ScrCmd_205
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_Entry26:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    MessageFromTrainerType
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_Entry27:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 67
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_Entry28:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 70
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_Entry29:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 71
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_Entry30:
    CheckItem ITEM_BICYCLE, 1, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_0D9B
    LockAll
    PlaySE SE_CONFIRM_sseq_3
    CheckPlayerOnBike VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_0D9D
    Message 73
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_0DBA
    SetPlayerBike 1
    CloseMessage
    ReleaseAll
    End
Common_Entry31:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 76
    WaitABPress
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    CloseMessage
    HatchEgg
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_Entry32:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CheckItem ITEM_REPEL, 1, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_0DC0
    CheckItem ITEM_SUPER_REPEL, 1, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_0DC0
    CheckItem ITEM_MAX_REPEL, 1, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_0DC0
    Message 79
    WaitABPress
    CloseMessage
    ReleaseAll
    End
Common_Entry33:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    ScrCmd_0A5
    ReleaseAll
    End
Common_Entry34:
    Message 20
    WaitABPress
    CloseMessage
    End
Common_Entry35:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 82
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_Entry36:
    Call Common_0DDA
    Message 31
    WaitButton
    ReturnCommonScript
    End
Common_Entry37:
    End
Common_Entry38:
    Call Common_0DF6
    ReturnCommonScript
    End
Common_Entry39:
    LockAll
    GetCurrentMapID VAR_0x8004
    CompareVarToValue VAR_0x8004, 220
    GoToIf 1, Common_0E73
    CompareVarToValue VAR_0x8004, 584
    GoToIf 1, Common_0E73
    CompareVarToValue VAR_0x8004, 585
    GoToIf 1, Common_0E73
    GoTo Common_0F25
Common_Entry40:
    StopMusic
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    CallIf 1, Common_0F30
    CompareVarToValue VAR_0x800C, 1
    CallIf 1, Common_0F36
    ReturnCommonScript
    End
Common_Entry41:
    FadeOutBGM 0, 30
    StopMusic
    PlayDefaultMusic
    ReturnCommonScript
    End
Common_Entry42:
    StopMusic
    SetBGM SEQ_THE_RIV_sseq
    ReturnCommonScript
    End
Common_Entry44:
    Call Common_0F3C
    ReturnCommonScript
    End
Common_Entry45:
    Call Common_0DDA
    Message 127
    ReturnCommonScript
    End
Common_Entry46:
    Call Common_0AFB
    Message 128
    ReturnCommonScript
    End
Common_Entry47:
    Call Common_0B4D
    Message 127
    ReturnCommonScript
    End
Common_Entry48:
    StopMusic
    SetBGM SEQ_TSURETEKE_sseq
    ReturnCommonScript
    End
Common_Entry50:
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    ScrCmd_0B3 32780
    SetVarFromVar VAR_0x8004, VAR_0x800C
    ScrCmd_2F6 32773, 32772, 32780
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_0F6F
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReturnCommonScript
    End
Common_Entry51:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    SetVarFromValue VAR_0x8004, 0
    GoTo Common_0F81
Common_Entry52:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    SetVarFromValue VAR_0x8004, 1
    GoTo Common_0F81
Common_Entry53:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    SetVarFromValue VAR_0x8004, 2
    GoTo Common_0F81
Common_Entry54:
    CheckFlag FLAG_OBTAINED_ALL_BATTLE_FRONTIER_GOLD_PRINTS
    GoToIf 1, Common_0FB1
    CompareVarToValue VAR_BATTLE_FACTORY_PRINT_STATE, 4
    GoToIf 5, Common_0FB1
    CompareVarToValue VAR_BATTLE_HALL_PRINT_STATE, 4
    GoToIf 5, Common_0FB1
    CompareVarToValue VAR_BATTLE_CASTLE_PRINT_STATE, 4
    GoToIf 5, Common_0FB1
    CompareVarToValue VAR_BATTLE_ARCADE_PRINT_STATE, 4
    GoToIf 5, Common_0FB1
    CompareVarToValue VAR_BATTLE_TOWER_PRINT_STATE, 4
    GoToIf 5, Common_0FB1
    SetFlag FLAG_OBTAINED_ALL_BATTLE_FRONTIER_GOLD_PRINTS
    IncrementTrainerScore 42
    GoTo Common_0FB1
Common_Entry55:
    StopMusic
    SetBGM SEQ_PL_HANDSOME_sseq
    ReturnCommonScript
    End
Common_Entry57:
    Message 130
    WaitButton
    CloseMessage
    ReleaseAll
    ReturnCommonScript
    End
Common_Entry58:
    LockAll
    SetVarFromValue VAR_0x8004, 255
    PlaySE SEQ_SE_DP_PC_ON_sseq
    BufferPlayerName 0
    Message 32
    GoTo Common_0BB2
Common_0717:
    SetSignpostCommand 2
    ReturnCommonScript
    End
Common_071E:
    SetSignpostCommand 4
    WaitForSignpostDone
    ShowStartMenu
    ReturnCommonScript
    End
Common_0729:
    GetItemPocket 32772, VAR_0x800C
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 7
    GoToIf 1, Common_0FB5
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Common_0FBB
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, Common_0FBB
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_0FBB
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, Common_0FBB
    CompareVarToValue VAR_0x8008, 6
    GoToIf 1, Common_0FBB
    CompareVarToValue VAR_0x8008, 5
    GoToIf 1, Common_0FC1
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, Common_0FC7
    End
Common_079F:
    CheckFlag FLAG_POKECENTER_GOLD_TRAINER_CARD_SEEN
    GoToIf 1, Common_0FCD
    SetFlag FLAG_POKECENTER_GOLD_TRAINER_CARD_SEEN
    Message 4
    BufferPlayerName 0
    Message 5
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_0FF1
    Message 9
    WaitButton
    CloseMessage
    ReleaseAll
    ReturnCommonScript
    End
Common_07D5:
    MessageVar VAR_0x8004
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_07F9
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_083E
    End
Common_07F9:
    SetPlayerState 256
    ChangePlayerState
    ApplyMovement LOCALID_PLAYER, Common_Movement_3012
    WaitMovement
    GetTrainerCardLevel VAR_0x800C
    CompareVarToValue VAR_0x800C, 4
    CallIf 4, Common_0FFD
    CompareVarToValue VAR_0x800C, 4
    CallIf 0, Common_1002
    Call Common_0D56
    CheckFlag FLAG_POKECENTER_IDENTIFIED_POKERUS
    GoToIf 0, Common_1007
    GoTo Common_101E
Common_083E:
    Message 3
    WaitButton
    CloseMessage
    ReleaseAll
    ReturnCommonScript
    End
Common_084B:
    AddVar VAR_0x8005, 1
    CompareVarToVar VAR_0x8004, VAR_0x8005
    GoToIf 5, Common_0877
    CountAliveMonsExcept VAR_0x800C, 6
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_08BE
    CloseMessage
    ReleaseAll
    End
Common_0877:
    SurvivePoison VAR_0x800C, 32773
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_084B
    BufferPartyMonNickname 0, 32773
    Message 66
    AddVar VAR_0x8005, 1
    CompareVarToVar VAR_0x8004, VAR_0x8005
    GoToIf 5, Common_0877
    CountAliveMonsExcept VAR_0x800C, 6
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_08BE
    CloseMessage
    ReleaseAll
    End
Common_08BE:
    BufferPlayerName 0
    Message 11
    WaitABPress
    CloseMessage
    FadeOutBGM 0, 10
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    WaitForTransition
    BlackOutFromBattle2
    End
Common_08E0:
    CheckSaveType VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_1055
    OpenSaveInfo
    Message 13
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_1062
    CheckSaveType VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_106C
    CompareVarToValue VAR_0x800C, 2
    GoToIf 1, Common_1075
    CompareVarToValue VAR_0x800C, 3
    GoToIf 1, Common_1092
    End
Common_0934:
    GetHoneyTreeStatus VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_10BE
    CompareVarToValue VAR_0x800C, 2
    GoToIf 1, Common_10C7
    CompareVarToValue VAR_0x800C, 3
    GoToIf 1, Common_097D
    End
Common_0961:
    Message 46
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_096C:
    Message 48
    WaitButton
    CloseMessage
    ReleaseAll
    SlatherHoneyTree
    GoTo Common_097D
Common_097D:
    IncrementGameRecord 117
    StartHoneyTreeBattle
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_10D2
    StopHoneyTreeShaking
    GoTo Common_10D8
Common_099C:
    BufferPlayerName 0
    BufferPoketchAppName 1, 32772
    PlayFanfare SEQ_POCKETCH_sseq
    Message 24
    WaitFanfare
    Message 26
    RegisterPoketchApp 32772
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, Common_10DC
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, Common_10E1
    CompareVarToValue VAR_0x8004, 2
    CallIf 1, Common_10E6
    CompareVarToValue VAR_0x8004, 3
    CallIf 1, Common_10EB
    CompareVarToValue VAR_0x8004, 4
    CallIf 1, Common_10F0
    CompareVarToValue VAR_0x8004, 5
    CallIf 1, Common_10F5
    CompareVarToValue VAR_0x8004, 6
    CallIf 1, Common_10FA
    CompareVarToValue VAR_0x8004, 7
    CallIf 1, Common_10FF
    CompareVarToValue VAR_0x8004, 8
    CallIf 1, Common_1104
    CompareVarToValue VAR_0x8004, 9
    CallIf 1, Common_1109
    CompareVarToValue VAR_0x8004, 10
    CallIf 1, Common_110E
    CompareVarToValue VAR_0x8004, 11
    CallIf 1, Common_1113
    CompareVarToValue VAR_0x8004, 12
    CallIf 1, Common_1118
    CompareVarToValue VAR_0x8004, 13
    CallIf 1, Common_111D
    CompareVarToValue VAR_0x8004, 14
    CallIf 1, Common_1122
    CompareVarToValue VAR_0x8004, 15
    CallIf 1, Common_1127
    CompareVarToValue VAR_0x8004, 16
    CallIf 1, Common_112C
    CompareVarToValue VAR_0x8004, 17
    CallIf 1, Common_1131
    CompareVarToValue VAR_0x8004, 18
    CallIf 1, Common_1136
    CompareVarToValue VAR_0x8004, 19
    CallIf 1, Common_113B
    CompareVarToValue VAR_0x8004, 20
    CallIf 1, Common_1140
    CompareVarToValue VAR_0x8004, 21
    CallIf 1, Common_1145
    CompareVarToValue VAR_0x8004, 22
    CallIf 1, Common_114A
    CompareVarToValue VAR_0x8004, 23
    CallIf 1, Common_114F
    CompareVarToValue VAR_0x8004, 24
    CallIf 1, Common_1154
    Return
Common_0AFB:
    PlayFanfare SEQ_FANFA4_sseq
    SendGoodToPC 32772, 32773, VAR_0x800C
    BufferUndergroundGoodsNameWithArticle 0, 32772
    Message 108
    BufferUndergroundGoodsName 0, 32772
    WaitFanfare
    Return
Common_0B18:
    PlayFanfare SEQ_FANFA4_sseq
    GiveTrap 32772, 32773, VAR_0x800C
    BufferUndergroundTrapName 0, 32772
    Message 80
    WaitFanfare
    Return
Common_0B30:
    PlayFanfare SEQ_FANFA4_sseq
    GiveSphere 32772, 32773, VAR_0x800C
    BufferUndergroundItemName 0, 32772
    BufferNumber 1, 32773
    Message 81
    WaitFanfare
    Return
Common_0B4D:
    PlayFanfare SEQ_ACCE_sseq
    AddAccessory 32772, 32773
    BufferAccessoryName 0, 32772
    Message 25
    WaitFanfare
    BufferPlayerName 0
    BufferAccessoryName 1, 32772
    Return
Common_0B6B:
    Call Common_0729
    AddItem 32772, 32773, VAR_0x800C
    GetItemPocket 32772, VAR_0x800C
    CompareVarToValue VAR_0x800C, 7
    CallIf 1, Common_1159
    CompareVarToValue VAR_0x800C, 7
    CallIf 5, Common_116A
    Message 30
    WaitButton
    Return
Common_0BA0:
    Message 27
    WaitButton
    Return
Common_0BA7:
    LoadPCAnimation 90
    PlayPCBootUpAnimation 90
    WaitForAnimation 90
    Return
Common_0BB2:
    BufferPlayerName 0
    Message 33
    InitGlobalTextMenu 1, 1, 0, VAR_0x8006, 1
    AddMenuEntryImm 59, 0
    AddMenuEntryImm 60, 1
    AddMenuEntryImm 62, 2
    AddMenuEntryImm 58, 5
    AddMenuEntryImm 57, 4
    AddMenuEntryImm 63, 7
    AddMenuEntryImm 93, 8
    AddMenuEntryImm 64, 6
    ShowMenu
    SetVarFromVar VAR_0x8008, VAR_0x8006
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Common_1182
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_1198
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, Common_11A8
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, Common_11BC
    CompareVarToValue VAR_0x8008, 5
    GoToIf 1, Common_13AF
    CompareVarToValue VAR_0x8008, 6
    GoToIf 1, Common_1451
    CompareVarToValue VAR_0x8008, 7
    GoToIf 1, Common_14E7
    CompareVarToValue VAR_0x8008, 8
    GoToIf 1, Common_14FE
    GoTo Common_1514
Common_0C56:
    Message 41
    Return
Common_0C5B:
    Message 42
    Return
Common_0C60:
    GetCurrentMapID VAR_0x8004
    CompareVarToValue VAR_0x8004, 6
    GoToIf 1, Common_152B
    CompareVarToValue VAR_0x8004, 36
    GoToIf 1, Common_1533
    CompareVarToValue VAR_0x8004, 48
    GoToIf 1, Common_153B
    CompareVarToValue VAR_0x8004, 69
    GoToIf 1, Common_1543
    CompareVarToValue VAR_0x8004, 101
    GoToIf 1, Common_154B
    CompareVarToValue VAR_0x8004, 123
    GoToIf 1, Common_1553
    CompareVarToValue VAR_0x8004, 134
    GoToIf 1, Common_155B
    CompareVarToValue VAR_0x8004, 151
    GoToIf 1, Common_1563
    CompareVarToValue VAR_0x8004, 168
    GoToIf 1, Common_156B
    CompareVarToValue VAR_0x8004, 173
    GoToIf 1, Common_1573
    CompareVarToValue VAR_0x8004, 189
    GoToIf 1, Common_157B
    CompareVarToValue VAR_0x8004, 420
    GoToIf 1, Common_1583
    CompareVarToValue VAR_0x8004, 428
    GoToIf 1, Common_158B
    CompareVarToValue VAR_0x8004, 435
    GoToIf 1, Common_1593
    CompareVarToValue VAR_0x8004, 443
    GoToIf 1, Common_159B
    CompareVarToValue VAR_0x8004, 452
    GoToIf 1, Common_15A3
    CompareVarToValue VAR_0x8004, 459
    GoToIf 1, Common_15AB
    CompareVarToValue VAR_0x8004, 175
    GoToIf 1, Common_15B3
    SetVarFromValue VAR_0x8007, 0
    Return
Common_0D56:
    ApplyMovement 32775, Common_Movement_302E
    WaitMovement
    CountPartyNonEggs VAR_0x8006
    PlayPokecenterHealingAnimation 32774
    ApplyMovement 32775, Common_Movement_3036
    WaitMovement
    HealParty
    Return
Common_0D76:
    ApplyMovement LOCALID_PLAYER, Common_Movement_301A
    WaitMovement
    SetPlayerState 1
    ChangePlayerState
    ApplyMovement 32775, Common_Movement_3022
    WaitMovement
    Message 39
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_0D9B:
    End
Common_0D9D:
    Message 74
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_0DBA
    SetPlayerBike 0
    CloseMessage
    ReleaseAll
    End
Common_0DBA:
    CloseMessage
    ReleaseAll
    End
Common_0DC0:
    Message 75
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_15BB
    CloseMessage
    ReleaseAll
    End
Common_0DDA:
    PlayFanfare SEQ_FANFA4_sseq
    AddContestBackdrop 32772
    BufferContestBackdropName 0, 32772
    Message 25
    WaitFanfare
    BufferPlayerName 0
    BufferContestBackdropName 1, 32772
    Return
Common_0DF6:
    AddVar VAR_NUM_PLATES_OBTAINED, 1
    CompareVarToValue VAR_NUM_PLATES_OBTAINED, 9
    CallIf 4, Common_1631
    CompareVarToValue VAR_NUM_PLATES_OBTAINED, 1
    CallIf 1, Common_1639
    CompareVarToValue VAR_NUM_PLATES_OBTAINED, 2
    CallIf 1, Common_163E
    CompareVarToValue VAR_NUM_PLATES_OBTAINED, 3
    CallIf 1, Common_1643
    CompareVarToValue VAR_NUM_PLATES_OBTAINED, 4
    CallIf 1, Common_1648
    CompareVarToValue VAR_NUM_PLATES_OBTAINED, 5
    CallIf 1, Common_164D
    CompareVarToValue VAR_NUM_PLATES_OBTAINED, 6
    CallIf 1, Common_1652
    CompareVarToValue VAR_NUM_PLATES_OBTAINED, 7
    CallIf 1, Common_1657
    CompareVarToValue VAR_NUM_PLATES_OBTAINED, 8
    CallIf 1, Common_165C
    Return
Common_0E73:
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8004, 31
    GoToIf 5, Common_0F25
    CompareVarToValue VAR_0x8005, 52
    GoToIf 5, Common_0F25
    CheckGameCompleted VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, Common_0F25
    GetSetNationalDexEnabled 2, VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, Common_0F25
    CheckFlag FLAG_CAUGHT_ARCEUS
    GoToIf 1, Common_0F25
    BufferPlayerName 0
    Message 122
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_1661
    BufferPlayerName 0
    Message 123
    CloseMessage
    WaitTime 30, VAR_0x800C
    PlayMusic SEQ_FUE_sseq
    WaitTime 540, VAR_0x800C
    GetPlayerMapPos 32772, 32773
    FadeScreen 6, 6, 0, 32767
    WaitFadeScreen
    Warp 510, 32772, 32773, 0
    FadeScreen 6, 6, 1, 32767
    WaitFadeScreen
    Message 124
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_0F25:
    Message 125
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_0F30:
    SetBGM SEQ_THE_GIRL_sseq
    Return
Common_0F36:
    SetBGM SEQ_THE_BOY_sseq
    Return
Common_0F3C:
    Call Common_0729
    AddItem 32772, 32773, VAR_0x800C
    GetItemPocket 32772, VAR_0x800C
    CompareVarToValue VAR_0x800C, 7
    CallIf 1, Common_1159
    CompareVarToValue VAR_0x800C, 7
    CallIf 5, Common_116A
    Message 126
    Return
Common_0F6F:
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReturnCommonScript
    End
Common_0F81:
    Message 129
    ShowMoveTutorMoveSelectionMenu 255, 32772, 32780
    SetVarFromVar VAR_0x8003, VAR_0x800C
    CompareVarToValue VAR_0x8003, 65534
    GoToIf 1, Common_1667
    ShowShardCost 21, 1, 32771, 32780
    WaitABPress
    CloseShardCostWindow
    GoTo Common_1667
Common_0FB1:
    ReturnCommonScript
    End
Common_0FB5:
    PlayFanfare SEQ_FANFA3_sseq
    Return
Common_0FBB:
    PlayFanfare SEQ_FANFA4_sseq
    Return
Common_0FC1:
    PlayFanfare SEQ_FANFA2_sseq
    Return
Common_0FC7:
    PlayFanfare SEQ_WAZA_sseq
    Return
Common_0FCD:
    BufferPlayerName 0
    Message 6
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_0FF1
    Message 9
    WaitButton
    CloseMessage
    ReleaseAll
    ReturnCommonScript
    End
Common_0FF1:
    SetVarFromValue VAR_0x8004, 1
    GoTo Common_07F9
Common_0FFD:
    Message 7
    Return
Common_1002:
    Message 1
    Return
Common_1007:
    CheckPartyPokerus VAR_0x8006
    CompareVarToValue VAR_0x8006, 1
    GoToIf 1, Common_166D
    GoTo Common_101E
Common_101E:
    CompareVarToValue VAR_0x8004, 1
    GoToIf 1, Common_168E
    Message 2
    ApplyMovement LOCALID_PLAYER, Common_Movement_301A
    WaitMovement
    SetPlayerState 1
    ChangePlayerState
    ApplyMovement 32775, Common_Movement_3022
    WaitMovement
    Message 3
    WaitButton
    CloseMessage
    ReleaseAll
    ReturnCommonScript
    End
Common_1055:
    Message 20
    WaitABPress
    SetVarFromValue VAR_0x800C, 0
    Return
Common_1062:
    CloseSaveInfo
    SetVarFromValue VAR_0x800C, 0
    Return
Common_106C:
    Message 21
    GoTo Common_16B8
Common_1075:
    Message 14
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_1062
    Message 21
    GoTo Common_16B8
Common_1092:
    Message 14
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_1062
    CheckFlag FLAG_MAP_LOCAL_SAVE_EXTRA_BLOCK
    GoToIf 0, Common_16CE
    CheckFlag FLAG_MAP_LOCAL_SAVE_EXTRA_BLOCK
    GoToIf 1, Common_16D7
    End
Common_10BE:
    Message 47
    GoTo Common_16EE
Common_10C7:
    Message 49
    SlatherHoneyTree
    GoTo Common_097D
Common_10D2:
    BlackOutFromBattle
    ReleaseAll
    End
Common_10D8:
    ReleaseAll
    End
Common_10DC:
    Message 83
    Return
Common_10E1:
    Message 84
    Return
Common_10E6:
    Message 85
    Return
Common_10EB:
    Message 86
    Return
Common_10F0:
    Message 87
    Return
Common_10F5:
    Message 88
    Return
Common_10FA:
    Message 89
    Return
Common_10FF:
    Message 90
    Return
Common_1104:
    Message 91
    Return
Common_1109:
    Message 92
    Return
Common_110E:
    Message 93
    Return
Common_1113:
    Message 94
    Return
Common_1118:
    Message 95
    Return
Common_111D:
    Message 96
    Return
Common_1122:
    Message 97
    Return
Common_1127:
    Message 98
    Return
Common_112C:
    Message 99
    Return
Common_1131:
    Message 100
    Return
Common_1136:
    Message 101
    Return
Common_113B:
    Message 102
    Return
Common_1140:
    Message 103
    Return
Common_1145:
    Message 104
    Return
Common_114A:
    Message 105
    Return
Common_114F:
    Message 106
    Return
Common_1154:
    Message 107
    Return
Common_1159:
    BufferPlayerName 0
    BufferItemName 1, 32772
    Message 28
    GoTo Common_1708
Common_116A:
    CompareVarToValue VAR_0x8005, 1
    GoToIf 2, Common_1738
    BufferItemName 0, 32772
    GoTo Common_1746
Common_1182:
    PlaySE SEQ_SE_DP_PC_LOGIN_sseq
    BufferPlayerName 0
    Message 34
    Call Common_174F
    GoTo Common_178C
Common_1198:
    PlaySE SEQ_SE_DP_PC_LOGIN_sseq
    BufferPlayerName 0
    Message 35
    GoTo Common_17DB
Common_11A8:
    PlaySE SEQ_SE_DP_PC_LOGIN_sseq
    CallCommonScript 9951
    SetVarFromValue VAR_0x8004, 255
    GoTo Common_0BB2
Common_11BC:
    Message 136
    InitLocalTextListMenu 1, 1, 0, VAR_0x800C, 1
    AddListMenuEntry 137, 0, 255
    CheckFlag FLAG_UNK_0x0A8A
    CallIf 1, Common_17E7
    CheckFlag FLAG_UNK_0x0A89
    CallIf 1, Common_17F1
    CheckFlag FLAG_UNK_0x0A88
    CallIf 1, Common_17FB
    CheckFlag FLAG_UNK_0x0A87
    CallIf 1, Common_1805
    CheckFlag FLAG_UNK_0x0A86
    CallIf 1, Common_180F
    CheckFlag FLAG_UNK_0x0A85
    CallIf 1, Common_1819
    CheckFlag FLAG_UNK_0x0A84
    CallIf 1, Common_1823
    CheckFlag FLAG_UNK_0x0A83
    CallIf 1, Common_182D
    CheckFlag FLAG_UNK_0x0A82
    CallIf 1, Common_1837
    CheckFlag FLAG_UNK_0x0A81
    CallIf 1, Common_1841
    CheckFlag FLAG_UNK_0x0A80
    CallIf 1, Common_184B
    CheckFlag FLAG_UNK_0x0A7F
    CallIf 1, Common_1855
    CheckFlag FLAG_UNK_0x0A7E
    CallIf 1, Common_185F
    CheckFlag FLAG_UNK_0x0A7D
    CallIf 1, Common_1869
    CheckFlag FLAG_UNK_0x0A7C
    CallIf 1, Common_1873
    CheckFlag FLAG_UNK_0x0A7B
    CallIf 1, Common_187D
    CheckFlag FLAG_UNK_0x0A7A
    CallIf 1, Common_1887
    CheckFlag FLAG_UNK_0x0A79
    CallIf 1, Common_1891
    AddListMenuEntry 156, 19, 255
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Common_189B
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_18C5
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, Common_18EF
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, Common_1919
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, Common_1943
    CompareVarToValue VAR_0x8008, 5
    GoToIf 1, Common_196D
    CompareVarToValue VAR_0x8008, 6
    GoToIf 1, Common_1997
    CompareVarToValue VAR_0x8008, 7
    GoToIf 1, Common_19C1
    CompareVarToValue VAR_0x8008, 8
    GoToIf 1, Common_19EB
    CompareVarToValue VAR_0x8008, 9
    GoToIf 1, Common_1A15
    CompareVarToValue VAR_0x8008, 10
    GoToIf 1, Common_1A3F
    CompareVarToValue VAR_0x8008, 11
    GoToIf 1, Common_1A69
    CompareVarToValue VAR_0x8008, 12
    GoToIf 1, Common_1A93
    CompareVarToValue VAR_0x8008, 13
    GoToIf 1, Common_1ABD
    CompareVarToValue VAR_0x8008, 14
    GoToIf 1, Common_1AE7
    CompareVarToValue VAR_0x8008, 15
    GoToIf 1, Common_1B11
    CompareVarToValue VAR_0x8008, 16
    GoToIf 1, Common_1B3B
    CompareVarToValue VAR_0x8008, 17
    GoToIf 1, Common_1B65
    CompareVarToValue VAR_0x8008, 18
    GoToIf 1, Common_1B8F
    CompareVarToValue VAR_0x8008, 19
    GoToIf 1, Common_1BB9
    GoTo Common_0BB2
Common_13AF:
    Message 172
    InitLocalTextListMenu 1, 1, 0, VAR_0x800C, 1
    AddListMenuEntry 166, 0, 255
    CountBadgesAcquired SCRIPT_LOCAL_VARS_START
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 3
    CallIf 4, Common_1BC1
    CountBadgesAcquired SCRIPT_LOCAL_VARS_START
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 5
    CallIf 4, Common_1BDB
    CountBadgesAcquired SCRIPT_LOCAL_VARS_START
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 5
    CallIf 4, Common_1BE5
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Common_1BEF
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_1C81
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, Common_1CA8
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, Common_1CCF
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, Common_1CF6
    CompareVarToValue VAR_0x8008, 5
    GoToIf 1, Common_1D10
    GoTo Common_0BB2
Common_1451:
    Message 172
    InitGlobalTextMenu 1, 1, 0, VAR_0x8006, 1
    AddMenuEntryImm 85, 0
    AddMenuEntryImm 86, 1
    AddMenuEntryImm 87, 2
    CheckFlag FLAG_GAME_COMPLETED
    CallIf 1, Common_1D2A
    CheckFlag FLAG_UNK_0x0A66
    CallIf 1, Common_1D30
    ShowMenu
    SetVarFromVar VAR_0x8008, VAR_0x8006
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Common_1D3E
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_1D58
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, Common_1D72
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, Common_1E06
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, Common_1E2D
    CompareVarToValue VAR_0x8008, 5
    GoToIf 1, Common_1E5A
    CompareVarToValue VAR_0x8008, 6
    GoToIf 1, Common_1E9B
    GoTo Common_0BB2
Common_14E7:
    CloseMessage
    PlayFanfare SEQ_ASA_sseq
    WaitFanfare
    HealParty
    Message 242
    WaitButton
    CloseMessage
    GoTo Common_0BB2
Common_14FE:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CallCommonScript 2019
    CloseMessageWithoutErasing
    PokeMartCommon 0
    ReleaseAll
    Return
Common_1514:
    CloseMessage
    PlaySE SEQ_SE_DP_PC_LOGOFF_sseq
    CompareVarToValue VAR_0x8004, 255
    CallIf 0, Common_1EC4
    ReleaseAll
    End
Common_152B:
    SetVarFromValue VAR_0x8007, 3
    Return
Common_1533:
    SetVarFromValue VAR_0x8007, 1
    Return
Common_153B:
    SetVarFromValue VAR_0x8007, 3
    Return
Common_1543:
    SetVarFromValue VAR_0x8007, 3
    Return
Common_154B:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_1553:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_155B:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_1563:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_156B:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_1573:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_157B:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_1583:
    SetVarFromValue VAR_0x8007, 3
    Return
Common_158B:
    SetVarFromValue VAR_0x8007, 2
    Return
Common_1593:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_159B:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_15A3:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_15AB:
    SetVarFromValue VAR_0x8007, 0
    Return
Common_15B3:
    SetVarFromValue VAR_0x8007, 3
    Return
Common_15BB:
    CloseMessage
    InitGlobalTextMenu 1, 1, 0, VAR_0x800C, 1
    CheckItem ITEM_REPEL, 1, SCRIPT_LOCAL_VARS_START
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 1
    CallIf 1, Common_1ECF
    CheckItem ITEM_SUPER_REPEL, 1, SCRIPT_LOCAL_VARS_START
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 1
    CallIf 1, Common_1ED5
    CheckItem ITEM_MAX_REPEL, 1, SCRIPT_LOCAL_VARS_START
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 1
    CallIf 1, Common_1EDB
    ShowMenu
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_1EE1
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_1F05
    CompareVarToValue VAR_0x800C, 2
    GoToIf 1, Common_1F29
    ReleaseAll
    End
Common_1631:
    SetVarFromValue VAR_NUM_PLATES_OBTAINED, 1
    Return
Common_1639:
    Message 110
    Return
Common_163E:
    Message 111
    Return
Common_1643:
    Message 112
    Return
Common_1648:
    Message 113
    Return
Common_164D:
    Message 114
    Return
Common_1652:
    Message 115
    Return
Common_1657:
    Message 116
    Return
Common_165C:
    Message 117
    Return
Common_1661:
    CloseMessage
    ReleaseAll
    End
Common_1667:
    CloseMessage
    ReleaseAll
    End
Common_166D:
    SetFlag FLAG_POKECENTER_IDENTIFIED_POKERUS
    ApplyMovement LOCALID_PLAYER, Common_Movement_301A
    WaitMovement
    SetPlayerState 1
    ChangePlayerState
    Message 10
    WaitButton
    CloseMessage
    ReleaseAll
    ReturnCommonScript
    End
Common_168E:
    Message 8
    ApplyMovement LOCALID_PLAYER, Common_Movement_301A
    WaitMovement
    SetPlayerState 1
    ChangePlayerState
    ApplyMovement 32775, Common_Movement_3022
    WaitMovement
    Message 9
    WaitButton
    CloseMessage
    ReleaseAll
    ReturnCommonScript
    End
Common_16B8:
    ScrCmd_258
    WaitTime 2, VAR_0x800C
    Call Common_1F4D
    ScrCmd_259
    GoTo Common_1F62
Common_16CE:
    Message 15
    GoTo Common_16B8
Common_16D7:
    CheckIsMiscSaveInit VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_1F85
    GoTo Common_16CE
Common_16EE:
    Message 50
    ShowYesNoMenu VAR_0x800C
    CloseMessage
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_1F8E
    ReleaseAll
    End
Common_1708:
    WaitFanfare
    CheckItemIsPlate 32772, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    CallIf 1, Common_0DF6
    BufferPlayerName 0
    CompareVarToValue VAR_0x8005, 1
    GoToIf 2, Common_1FAD
    BufferItemName 1, 32772
    GoTo Common_2028
Common_1738:
    BufferItemNamePlural 0, 32772
    Message 25
    GoTo Common_1708
Common_1746:
    Message 25
    GoTo Common_1708
Common_174F:
    InitGlobalTextListMenu 1, 1, 0, VAR_0x800C, 1
    AddListMenuEntry 65, 0, 74
    AddListMenuEntry 66, 1, 75
    AddListMenuEntry 67, 2, 76
    AddListMenuEntry 68, 3, 77
    CheckFlag FLAG_CONTEST_HALL_VISITED
    CallIf 1, Common_209E
    AddListMenuEntry 70, 5, 79
    Return
Common_178C:
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Common_20A8
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_20BB
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, Common_20CE
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, Common_20E1
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, Common_20F4
    GoTo Common_0BB2
Common_17DB:
    Call Common_2107
    GoTo Common_2129
Common_17E7:
    AddListMenuEntry 138, 1, 255
    Return
Common_17F1:
    AddListMenuEntry 139, 2, 255
    Return
Common_17FB:
    AddListMenuEntry 140, 3, 255
    Return
Common_1805:
    AddListMenuEntry 141, 4, 255
    Return
Common_180F:
    AddListMenuEntry 142, 5, 255
    Return
Common_1819:
    AddListMenuEntry 143, 6, 255
    Return
Common_1823:
    AddListMenuEntry 144, 7, 255
    Return
Common_182D:
    AddListMenuEntry 145, 8, 255
    Return
Common_1837:
    AddListMenuEntry 146, 9, 255
    Return
Common_1841:
    AddListMenuEntry 147, 10, 255
    Return
Common_184B:
    AddListMenuEntry 148, 11, 255
    Return
Common_1855:
    AddListMenuEntry 149, 12, 255
    Return
Common_185F:
    AddListMenuEntry 150, 13, 255
    Return
Common_1869:
    AddListMenuEntry 151, 14, 255
    Return
Common_1873:
    AddListMenuEntry 152, 15, 255
    Return
Common_187D:
    AddListMenuEntry 153, 16, 255
    Return
Common_1887:
    AddListMenuEntry 154, 17, 255
    Return
Common_1891:
    AddListMenuEntry 155, 18, 255
    Return
Common_189B:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 411, 116, 886, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_18C5:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 418, 177, 843, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_18EF:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 3, 180, 777, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1919:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 45, 303, 757, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1943:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 426, 176, 667, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_196D:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 65, 305, 531, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1997:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 86, 465, 698, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_19C1:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 433, 566, 657, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_19EB:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 132, 717, 612, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1A15:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 120, 600, 816, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1A3F:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 442, 472, 539, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1A69:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 33, 58, 723, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1A93:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 165, 379, 234, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1ABD:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 150, 860, 785, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1AE7:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 172, 847, 562, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1B11:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 392, 308, 914, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1B3B:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 188, 647, 430, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1B65:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 450, 659, 339, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1B8F:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 457, 802, 473, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Common_1BB9:
    CloseMessage
    GoTo Common_0BB2
Common_1BC1:
    AddListMenuEntry 167, 1, 255
    AddListMenuEntry 168, 2, 255
    AddListMenuEntry 169, 3, 255
    Return
Common_1BDB:
    AddListMenuEntry 170, 4, 255
    Return
Common_1BE5:
    AddListMenuEntry 171, 5, 255
    Return
Common_1BEF:
    Message 132
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    SelectMoveTutorPokemon
    GetSelectedPartySlot VAR_0x8005
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue VAR_0x8005, 255
    GoToIf 1, Common_2151
    GetPartyMonSpecies 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_215D
    CheckHasLearnableReminderMoves VAR_0x800C, 32773
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_216A
    Message 133
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    OpenMoveReminderMenu 32773
    CheckLearnedReminderMove VAR_0x800C
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue VAR_0x800C, 255
    GoToIf 1, Common_2151
    GoTo Common_2151
Common_1C81:
    Message 173
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2177
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_13AF
    GoTo Common_13AF
Common_1CA8:
    Message 173
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2220
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_13AF
    GoTo Common_13AF
Common_1CCF:
    Message 173
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_22C9
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2372
    GoTo Common_13AF
Common_1CF6:
    Message 205
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_237F
    GoTo Common_2428
Common_1D10:
    Message 221
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2435
    GoTo Common_2442
Common_1D2A:
    AddMenuEntryImm 61, 4
    Return
Common_1D30:
    AddMenuEntryImm 88, 3
    AddMenuEntryImm 89, 5
    AddMenuEntryImm 90, 6
    Return
Common_1D3E:
    Message 157
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2487
    GoTo Common_0BB2
Common_1D58:
    Message 230
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2506
    GoTo Common_2512
Common_1D72:
    Message 59
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2506
    Message 60
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    SelectMoveTutorPokemon
    GetSelectedPartySlot VAR_MAP_LOCAL_0x05
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue VAR_MAP_LOCAL_0x05, 255
    GoToIf 1, Common_2506
    GetPartyMonSpecies 16389, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_258A
    Message 61
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    PlaySE SEQ_SE_DP_FW367_sseq
    WaitSE SEQ_SE_DP_FW367_sseq
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    BufferPartyMonNickname 0, 16389
    Message 62
    IncreasePartyMonFriendship 255, 16389
    CloseMessage
    GoTo Common_2506
Common_1E06:
    Message 240
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2597
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2641
    GoTo Common_1451
Common_1E2D:
    PlaySE SEQ_SE_DP_PC_LOGIN_sseq
    CloseMessage
    CheckIsHallOfFameCorrupted VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2649
    Call Common_2652
    OpenPCHallOfFameScreen
    ReturnToField
    Call Common_266D
    GoTo Common_0BB2
Common_1E5A:
    Message 243
    ClearFlag FLAG_UNK_0x095E
    ClearFlag FLAG_UNK_0x095D
    ClearFlag FLAG_UNK_0x095C
    ClearFlag FLAG_UNK_0x095B
    ClearFlag FLAG_UNK_0x095A
    ClearFlag FLAG_UNK_0x0959
    ClearFlag FLAG_UNK_0x0958
    ClearFlag FLAG_UNK_0x0957
    ClearFlag FLAG_UNK_0x0956
    ClearFlag FLAG_UNK_0x0955
    ClearFlag FLAG_UNK_0x0954
    ClearFlag FLAG_UNK_0x0953
    ClearFlag FLAG_UNK_0x0952
    WaitButton
    CloseMessage
    GoTo Common_1451
Common_1E9B:
    Message 244
    ClearFlag FLAG_TRADED_FOR_KAZZA_ABRA
    ClearFlag FLAG_TRADED_FOR_CHARAP_CHATOT
    ClearFlag FLAG_TRADED_FOR_GASPAR_HAUNTER
    ClearFlag FLAG_TRADED_FOR_FOPPA_MAGIKARP
    ClearFlag FLAG_RECEIVED_HEARTHOME_CITY_NORTHWEST_HOUSE_EEVEE
    ClearFlag FLAG_RECEIVED_VEILSTONE_CITY_NORTHEAST_HOUSE_PORYGON
    ClearFlag FLAG_UNK_0x0A65
    WaitButton
    CloseMessage
    GoTo Common_1451
Common_1EC4:
    PlayPCShutDownAnimation 90
    WaitForAnimation 90
    UnloadAnimation 90
    Return
Common_1ECF:
    AddMenuEntryImm 30, 0
    Return
Common_1ED5:
    AddMenuEntryImm 31, 1
    Return
Common_1EDB:
    AddMenuEntryImm 32, 2
    Return
Common_1EE1:
    ScrCmd_Unused_007 37617448, 100
    Dummy088
    RemoveItem ITEM_REPEL, 1, SCRIPT_LOCAL_VARS_START
    BufferPlayerName 0
    BufferItemName 1, ITEM_REPEL
    Message 72
    WaitButton
    CloseMessage
    ReleaseAll
    Return
Common_1F05:
    ScrCmd_Unused_007 37617448, 150
    Dummy088
    RemoveItem ITEM_SUPER_REPEL, 1, SCRIPT_LOCAL_VARS_START
    BufferPlayerName 0
    BufferItemName 1, ITEM_SUPER_REPEL
    Message 72
    WaitButton
    CloseMessage
    ReleaseAll
    Return
Common_1F29:
    ScrCmd_Unused_007 37617448, 250
    Dummy088
    RemoveItem ITEM_MAX_REPEL, 1, SCRIPT_LOCAL_VARS_START
    BufferPlayerName 0
    BufferItemName 1, ITEM_MAX_REPEL
    Message 72
    WaitButton
    CloseMessage
    ReleaseAll
    Return
Common_1F4D:
    ShowSavingIcon
    CheckFlag FLAG_MAP_LOCAL_SAVE_EXTRA_BLOCK
    CallIf 1, Common_2688
    TrySaveGame VAR_0x800C
    HideSavingIcon
    Return
Common_1F62:
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2690
    BufferPlayerName 0
    Message 16
    PlaySE SEQ_SE_DP_SAVE_sseq
    WaitSE SEQ_SE_DP_SAVE_sseq
    WaitABPressTime 30
    CloseSaveInfo
    Return
Common_1F85:
    Message 21
    GoTo Common_16B8
Common_1F8E:
    RemoveItem ITEM_HONEY, 1, VAR_0x800C
    IncrementTrainerScore2 1
    SlatherHoneyTree
    WaitTime 10, VAR_0x800C
    Message 51
    WaitButton
    CloseMessage
    ReleaseAll
    End
Common_1FAD:
    BufferItemNamePlural 1, 32772
    GetItemPocket 32772, VAR_0x800C
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 7
    GoToIf 1, Common_2699
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Common_26AA
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, Common_26BB
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_26CC
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, Common_26DD
    CompareVarToValue VAR_0x8008, 6
    GoToIf 1, Common_26EE
    CompareVarToValue VAR_0x8008, 5
    GoToIf 1, Common_26FF
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, Common_2710
    End
Common_2028:
    GetItemPocket 32772, VAR_0x800C
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 7
    GoToIf 1, Common_2699
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Common_26AA
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, Common_26BB
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_26CC
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, Common_26DD
    CompareVarToValue VAR_0x8008, 6
    GoToIf 1, Common_26EE
    CompareVarToValue VAR_0x8008, 5
    GoToIf 1, Common_26FF
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, Common_2710
    End
Common_209E:
    AddListMenuEntry 69, 4, 78
    Return
Common_20A8:
    CloseMessage
    Call Common_2652
    OpenPokemonStorage 0
    ReturnToField
    GoTo Common_2721
Common_20BB:
    CloseMessage
    Call Common_2652
    OpenPokemonStorage 1
    ReturnToField
    GoTo Common_2721
Common_20CE:
    CloseMessage
    Call Common_2652
    OpenPokemonStorage 2
    ReturnToField
    GoTo Common_2721
Common_20E1:
    CloseMessage
    Call Common_2652
    OpenPokemonStorage 3
    ReturnToField
    GoTo Common_2721
Common_20F4:
    CloseMessage
    Call Common_2652
    OpenPokemonStorage 4
    ReturnToField
    GoTo Common_2721
Common_2107:
    InitGlobalTextListMenu 1, 1, 0, VAR_0x800C, 1
    AddListMenuEntry 71, 0, 80
    AddListMenuEntry 72, 1, 81
    AddListMenuEntry 73, 3, 82
    Return
Common_2129:
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Common_274C
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Common_2767
    GoTo Common_0BB2
Common_2151:
    SetVarFromValue VAR_0x8004, 255
    GoTo Common_13AF
Common_215D:
    Message 134
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_216A:
    Message 135
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2177:
    Message 175
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    SelectMoveTutorPokemon
    GetSelectedPartySlot SCRIPT_LOCAL_VARS_START
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 255
    GoToIf 1, Common_2151
    GetPartyMonSpecies 32768, VAR_0x8001
    CompareVarToValue VAR_0x8001, 0
    GoToIf 1, Common_2788
    CheckHasLearnableTutorMoves 32768, 0, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2795
    BufferPartyMonNickname 0, 32768
    Message 177
    ShowMoveTutorMoveSelectionMenu 32768, 0, 32780
    SetVarFromVar VAR_0x8003, VAR_0x800C
    CompareVarToValue VAR_0x8003, 65534
    GoToIf 1, Common_2151
    CompareVarToValue VAR_0x8003, 239
    GoToIf 1, Common_27A2
    GetPartyMonMoveCount VAR_0x800C, 32768
    SetVarFromVar VAR_0x8002, VAR_0x800C
    CompareVarToValue VAR_0x800C, 4
    GoToIf 1, Common_27AF
    GoTo Common_2867
Common_2220:
    Message 175
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    SelectMoveTutorPokemon
    GetSelectedPartySlot SCRIPT_LOCAL_VARS_START
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 255
    GoToIf 1, Common_2886
    GetPartyMonSpecies 32768, VAR_0x8001
    CompareVarToValue VAR_0x8001, 0
    GoToIf 1, Common_2893
    CheckHasLearnableTutorMoves 32768, 2, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_28A0
    BufferPartyMonNickname 0, 32768
    Message 177
    ShowMoveTutorMoveSelectionMenu 32768, 2, 32780
    SetVarFromVar VAR_0x8003, VAR_0x800C
    CompareVarToValue VAR_0x8003, 65534
    GoToIf 1, Common_2886
    CompareVarToValue VAR_0x800C, 239
    GoToIf 1, Common_28AD
    GetPartyMonMoveCount VAR_0x800C, 32768
    SetVarFromVar VAR_0x8002, VAR_0x800C
    CompareVarToValue VAR_0x800C, 4
    GoToIf 1, Common_28BA
    GoTo Common_2972
Common_22C9:
    Message 175
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    SelectMoveTutorPokemon
    GetSelectedPartySlot SCRIPT_LOCAL_VARS_START
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 255
    GoToIf 1, Common_2372
    GetPartyMonSpecies 32768, VAR_0x8001
    CompareVarToValue VAR_0x8001, 0
    GoToIf 1, Common_2991
    CheckHasLearnableTutorMoves 32768, 1, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_299E
    BufferPartyMonNickname 0, 32768
    Message 177
    ShowMoveTutorMoveSelectionMenu 32768, 1, 32780
    SetVarFromVar VAR_0x8003, VAR_0x800C
    CompareVarToValue VAR_0x8003, 65534
    GoToIf 1, Common_2372
    CompareVarToValue VAR_0x800C, 239
    GoToIf 1, Common_29AB
    GetPartyMonMoveCount VAR_0x800C, 32768
    SetVarFromVar VAR_0x8002, VAR_0x800C
    CompareVarToValue VAR_0x800C, 4
    GoToIf 1, Common_29B8
    GoTo Common_2A70
Common_2372:
    Message 174
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_237F:
    Message 206
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    SelectMoveTutorPokemon
    GetSelectedPartySlot SCRIPT_LOCAL_VARS_START
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 255
    GoToIf 1, Common_2428
    GetPartyMonSpecies 32768, VAR_0x8001
    CompareVarToValue VAR_0x8001, 0
    GoToIf 1, Common_2A8F
    Call Common_2A9C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2B40
    SetVarFromVar VAR_0x8002, VAR_0x800C
    Call Common_2B4D
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2B6D
    GetPartyMonFriendship VAR_0x800C, 32768
    CompareVarToValue VAR_0x800C, 255
    GoToIf 0, Common_2B7A
    BufferPartyMonSpecies 0, 32768
    CompareVarToValue VAR_0x8002, 1
    GoToIf 1, Common_2B87
    CompareVarToValue VAR_0x8002, 2
    GoToIf 1, Common_2BA7
    GoTo Common_2BC7
Common_2428:
    Message 207
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2435:
    Message 222
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2442:
    GetPartyCount VARS_START
    SubVar VARS_START, 1
    GetPartyMonSpecies 16384, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2BE7
    GetPartyMonType VAR_0x8004, VAR_0x8005, 16384
    CompareVarToValue VAR_0x8004, 16
    GoToIf 1, Common_2BFA
    CompareVarToValue VAR_0x8005, 16
    GoToIf 1, Common_2BFA
    GoTo Common_2BE7
Common_2487:
    Message 158
    WaitABPress
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    SelectMoveTutorPokemon
    GetSelectedPartySlot VAR_0x800C
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue VAR_0x800C, 255
    GoToIf 1, Common_2C22
    SetVarFromVar VAR_0x8005, VAR_0x800C
    GetPartyMonSpecies 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2C35
    CheckIsPartyMonOutsider 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2C48
    BufferPartyMonNickname 0, 32773
    Message 159
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2C60
    GoTo Common_2C22
Common_2506:
    SetVarFromValue VAR_0x8004, 255
    GoTo Common_1451
Common_2512:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    SelectMoveTutorPokemon
    GetSelectedPartySlot SCRIPT_LOCAL_VARS_START
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 255
    GoToIf 1, Common_2506
    GetPartyMonSpecies 32768, VAR_0x8001
    CompareVarToValue VAR_0x8001, 0
    GoToIf 1, Common_2CB8
    CalcHiddenPowerType 32768, VAR_0x8004
    CompareVarToValue VAR_0x8004, 65535
    GoToIf 1, Common_2CC3
    CheckPartyMonHasMove VAR_0x800C, MOVE_HIDDEN_POWER, 32768
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2CCE
    BufferTypeName 0, 32772
    Message 38
    GoTo Common_2506
Common_258A:
    Message 63
    WaitButton
    CloseMessage
    GoTo Common_2506
Common_2597:
    ClearFlag FLAG_HIDE_TURNBACK_CAVE_GIRATINA_ROOM_GIRATINA
    ClearFlag FLAG_HIDE_HALL_OF_ORIGIN_ARCEUS
    ClearFlag FLAG_CAUGHT_ARCEUS
    SetVarFromValue VAR_ARCEUS_EVENT_STATE, 0
    SetVarFromValue VAR_SPEAR_PILLAR_PALKIA_STATE, 0
    ClearFlag FLAG_CAUGHT_DIALGA
    SetVarFromValue VAR_HALL_OF_ORIGIN_STATE, 0
    ClearFlag FLAG_CAUGHT_PALKIA
    SetVarFromValue VAR_SPEAR_PILLAR_DIALGA_STATE, 0
    ClearFlag FLAG_HIDE_STARK_MOUNTAIN_ROOM_3_HEATRAN
    ClearFlag FLAG_CAUGHT_HEATRAN
    SetVarFromValue VAR_STARK_MOUNTAIN_ROOM_3_STATE, 1
    ClearFlag FLAG_HIDE_SNOWPOINT_TEMPLE_B5F_REGIGIGAS
    ClearFlag FLAG_CAUGHT_OLD_CHATEAU_ROTOM
    ClearFlag FLAG_DAILY_BATTLED_OLD_CHATEAU_ROTOM
    ClearFlag FLAG_HIDE_ACUITY_CAVERN_UXIE
    ClearFlag FLAG_HIDE_VALOR_CAVERN_AZELF
    ClearFlag FLAG_HIDE_NEWMOON_ISLAND_FOREST_DARKRAI
    ClearFlag FLAG_CAUGHT_DARKRAI
    ClearFlag FLAG_CAUGHT_SHAYMIN
    ClearFlag FLAG_HIDE_FLOWER_PARADISE_SHAYMIN
    SetVarFromValue VAR_IRON_RUINS_STATE, 270
    SetVarFromValue VAR_ICEBERG_RUINS_STATE, 270
    SetVarFromValue VAR_ROCK_PEAK_RUINS_STATE, 270
    SetVarFromValue VAR_ROAMING_MOLTRES_STATE, 0
    ActivateRoamingPokemon 3
    SetVarFromValue VAR_ROAMING_ZAPDOS_STATE, 0
    ActivateRoamingPokemon 4
    SetVarFromValue VAR_ROAMING_ARTICUNO_STATE, 0
    ActivateRoamingPokemon 5
    SetVarFromValue VAR_ROAMING_MESPRIT_STATE, 0
    ActivateRoamingPokemon 0
    SetVarFromValue VAR_ROAMING_CRESSELIA_STATE, 0
    ActivateRoamingPokemon 1
    Message 241
    WaitButton
    CloseMessage
    GoTo Common_1451
Common_2641:
    CloseMessage
    GoTo Common_1451
Common_2649:
    Message 131
    GoTo Common_0BB2
Common_2652:
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    CompareVarToValue VAR_0x8004, 255
    CallIf 0, Common_2CDC
    Return
Common_266D:
    CompareVarToValue VAR_0x8004, 255
    CallIf 0, Common_0BA7
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    Return
Common_2688:
    SaveExtraData
    ClearFlag FLAG_MAP_LOCAL_SAVE_EXTRA_BLOCK
    Return
Common_2690:
    Message 18
    WaitABPress
    CloseSaveInfo
    Return
Common_2699:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo Common_2CE1
Common_26AA:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo Common_2CE1
Common_26BB:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo Common_2CE1
Common_26CC:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo Common_2CE1
Common_26DD:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo Common_2CE1
Common_26EE:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo Common_2CE1
Common_26FF:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo Common_2CE1
Common_2710:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo Common_2CE1
Common_2721:
    SaveTVSegmentPokemonStorageBulletin
    BufferPlayerName 0
    MessageInstant 33
    Call Common_174F
    CompareVarToValue VAR_0x8004, 255
    CallIf 0, Common_0BA7
    FadeScreen 6, 1, 1, 0
    GoTo Common_178C
Common_274C:
    CloseMessage
    CountMailInMailbox VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2CE3
    ScrCmd_1B3
    GoTo Common_2CEC
Common_2767:
    CountUniqueSealsInSealCase VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2CFD
    CloseMessage
    Call Common_2652
    OpenSealCapsuleEditor
    GoTo Common_2D06
Common_2788:
    Message 185
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2795:
    Message 176
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_27A2:
    Message 4
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_27AF:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 179
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2D28
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    CloseMessage
    OpenSummaryScreenTeachMove 32768, 32771
    GetSummarySelectedMoveSlot VAR_0x8002
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue VAR_0x8002, 4
    GoToIf 1, Common_2D28
    GetPartyMonMove VAR_0x800C, 32768, 32770
    BufferMoveName 1, 32780
    Message 182
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2D28
    BufferPartyMonNickname 0, 32768
    GetPartyMonMove VAR_0x800C, 32768, 32770
    BufferMoveName 1, 32780
    Message 183
    PlaySE SEQ_SE_DP_KON_sseq
    WaitSE SEQ_SE_DP_KON_sseq
    WaitTime 30, VAR_0x800C
    Message 184
    WaitTime 32, VAR_0x800C
    PlayFanfare SEQ_FANFA1_sseq
    BufferMoveName 1, 32771
    Message 178
    WaitFanfare
    WaitTime 16, VAR_0x800C
    GoTo Common_2D4C
Common_2867:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 186
    PlayFanfare SEQ_FANFA1_sseq
    WaitFanfare
    WaitTime 16, VAR_0x800C
    GoTo Common_2D4C
Common_2886:
    Message 174
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2893:
    Message 185
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_28A0:
    Message 176
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_28AD:
    Message 11
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_28BA:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 188
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2D5A
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    CloseMessage
    OpenSummaryScreenTeachMove 32768, 32771
    GetSummarySelectedMoveSlot VAR_0x8002
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue VAR_0x8002, 4
    GoToIf 1, Common_2D5A
    GetPartyMonMove VAR_0x800C, 32768, 32770
    BufferMoveName 1, 32780
    Message 189
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2D5A
    BufferPartyMonNickname 0, 32768
    GetPartyMonMove VAR_0x800C, 32768, 32770
    BufferMoveName 1, 32780
    Message 190
    PlaySE SEQ_SE_DP_KON_sseq
    WaitSE SEQ_SE_DP_KON_sseq
    WaitTime 30, VAR_0x800C
    Message 191
    WaitTime 32, VAR_0x800C
    PlayFanfare SEQ_FANFA1_sseq
    BufferMoveName 1, 32771
    Message 192
    WaitFanfare
    WaitTime 16, VAR_0x800C
    GoTo Common_2D7E
Common_2972:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 193
    PlayFanfare SEQ_FANFA1_sseq
    WaitFanfare
    WaitTime 16, VAR_0x800C
    GoTo Common_2D7E
Common_2991:
    Message 185
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_299E:
    Message 176
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_29AB:
    Message 196
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_29B8:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 197
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2D8C
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    CloseMessage
    OpenSummaryScreenTeachMove 32768, 32771
    GetSummarySelectedMoveSlot VAR_0x8002
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue VAR_0x8002, 4
    GoToIf 1, Common_2D8C
    GetPartyMonMove VAR_0x800C, 32768, 32770
    BufferMoveName 1, 32780
    Message 198
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2D8C
    BufferPartyMonNickname 0, 32768
    GetPartyMonMove VAR_0x800C, 32768, 32770
    BufferMoveName 1, 32780
    Message 199
    PlaySE SEQ_SE_DP_KON_sseq
    WaitSE SEQ_SE_DP_KON_sseq
    WaitTime 30, VAR_0x800C
    Message 200
    WaitTime 32, VAR_0x800C
    PlayFanfare SEQ_FANFA1_sseq
    BufferMoveName 1, 32771
    Message 201
    WaitFanfare
    WaitTime 16, VAR_0x800C
    GoTo Common_2DB0
Common_2A70:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 202
    PlayFanfare SEQ_FANFA1_sseq
    WaitFanfare
    WaitTime 16, VAR_0x800C
    GoTo Common_2DB0
Common_2A8F:
    Message 209
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2A9C:
    CompareVarToValue VAR_0x8001, 6
    GoToIf 1, Common_2DBE
    CompareVarToValue VAR_0x8001, 157
    GoToIf 1, Common_2DBE
    CompareVarToValue VAR_0x8001, 257
    GoToIf 1, Common_2DBE
    CompareVarToValue VAR_0x8001, 392
    GoToIf 1, Common_2DBE
    CompareVarToValue VAR_0x8001, 9
    GoToIf 1, Common_2DC6
    CompareVarToValue VAR_0x8001, 160
    GoToIf 1, Common_2DC6
    CompareVarToValue VAR_0x8001, 260
    GoToIf 1, Common_2DC6
    CompareVarToValue VAR_0x8001, 395
    GoToIf 1, Common_2DC6
    CompareVarToValue VAR_0x8001, 3
    GoToIf 1, Common_2DCE
    CompareVarToValue VAR_0x8001, 154
    GoToIf 1, Common_2DCE
    CompareVarToValue VAR_0x8001, 254
    GoToIf 1, Common_2DCE
    CompareVarToValue VAR_0x8001, 389
    GoToIf 1, Common_2DCE
    SetVarFromValue VAR_0x800C, 0
    Return
Common_2B40:
    Message 208
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2B4D:
    CompareVarToValue VAR_0x8002, 1
    GoToIf 1, Common_2DD6
    CompareVarToValue VAR_0x8002, 2
    GoToIf 1, Common_2DE0
    GoTo Common_2DEA
Common_2B6D:
    Message 211
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2B7A:
    Message 210
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2B87:
    Message 212
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2428
    SetVarFromValue VAR_0x8003, 307
    GoTo Common_2DF4
Common_2BA7:
    Message 213
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2428
    SetVarFromValue VAR_0x8003, 308
    GoTo Common_2DF4
Common_2BC7:
    Message 214
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2428
    SetVarFromValue VAR_0x8003, 338
    GoTo Common_2DF4
Common_2BE7:
    CompareVarToValue VARS_START, 0
    GoToIf 5, Common_2E2D
    GoTo Common_2E6E
Common_2BFA:
    CheckPartyMonHasMove VAR_0x800C, MOVE_DRACO_METEOR, 16384
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2E7B
    CompareVarToValue VARS_START, 0
    GoToIf 5, Common_2E2D
    GoTo Common_2E6E
Common_2C22:
    Message 162
    WaitButton
    CloseMessage
    SetVarFromValue VAR_0x8004, 255
    GoTo Common_0BB2
Common_2C35:
    Message 165
    WaitButton
    CloseMessage
    SetVarFromValue VAR_0x8004, 255
    GoTo Common_0BB2
Common_2C48:
    BufferPartyMonNickname 0, 32773
    Message 164
    WaitButton
    CloseMessage
    SetVarFromValue VAR_0x8004, 255
    GoTo Common_0BB2
Common_2C60:
    Message 160
    WaitABPress
    CloseMessage
    SetVarFromValue VAR_0x800C, 0
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    OpenPokemonNamingScreen 32773, VAR_0x800C
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2F07
    ScrCmd_2B8 32773
    IncrementGameRecord 49
    BufferPartyMonNickname 0, 32773
    Message 161
    WaitButton
    CloseMessage
    SetVarFromValue VAR_0x8004, 255
    GoTo Common_0BB2
Common_2CB8:
    Message 231
    WaitButton
    GoTo Common_2506
Common_2CC3:
    Message 232
    WaitButton
    GoTo Common_2506
Common_2CCE:
    BufferTypeName 0, 32772
    Message 38
    GoTo Common_2506
Common_2CDC:
    UnloadAnimation 90
    Return
Common_2CE1:
    Return
Common_2CE3:
    Message 52
    GoTo Common_17DB
Common_2CEC:
    BufferPlayerName 0
    OpenMessage
    Call Common_2107
    GoTo Common_2129
Common_2CFD:
    Message 118
    GoTo Common_17DB
Common_2D06:
    BufferPlayerName 0
    MessageInstant 33
    Call Common_2107
    Call Common_0BA7
    FadeScreen 6, 1, 1, 0
    GoTo Common_2129
Common_2D28:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 180
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2F1F
    GoTo Common_27AF
Common_2D4C:
    ResetMoveSlot 32768, 32770, 32771
    GoTo Common_2151
Common_2D5A:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 194
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2F32
    GoTo Common_28BA
Common_2D7E:
    ResetMoveSlot 32768, 32770, 32771
    GoTo Common_2886
Common_2D8C:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 203
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2F45
    GoTo Common_29B8
Common_2DB0:
    ResetMoveSlot 32768, 32770, 32771
    GoTo Common_22C9
Common_2DBE:
    SetVarFromValue VAR_0x800C, 1
    Return
Common_2DC6:
    SetVarFromValue VAR_0x800C, 2
    Return
Common_2DCE:
    SetVarFromValue VAR_0x800C, 3
    Return
Common_2DD6:
    CheckPartyMonHasMove VAR_0x800C, MOVE_BLAST_BURN, 32768
    Return
Common_2DE0:
    CheckPartyMonHasMove VAR_0x800C, MOVE_HYDRO_CANNON, 32768
    Return
Common_2DEA:
    CheckPartyMonHasMove VAR_0x800C, MOVE_FRENZY_PLANT, 32768
    Return
Common_2DF4:
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    OpenMoveTutorMenu 32768, 32771
    CheckLearnedTutorMove VAR_0x800C
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue VAR_0x800C, 255
    GoToIf 1, Common_2428
    GoTo Common_2151
Common_2E2D:
    SubVar VARS_START, 1
    GetPartyMonSpecies 16384, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2BE7
    GetPartyMonType VAR_0x8004, VAR_0x8005, 16384
    CompareVarToValue VAR_0x8004, 16
    GoToIf 1, Common_2BFA
    CompareVarToValue VAR_0x8005, 16
    GoToIf 1, Common_2BFA
    GoTo Common_2BE7
Common_2E6E:
    Message 223
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2E7B:
    Message 224
    CloseMessage
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    SelectMoveTutorPokemon
    GetSelectedPartySlot SCRIPT_LOCAL_VARS_START
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue SCRIPT_LOCAL_VARS_START, 255
    GoToIf 1, Common_2435
    GetPartyMonSpecies 32768, VAR_0x8001
    CompareVarToValue VAR_0x8001, 0
    GoToIf 1, Common_2F58
    Call Common_2F65
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Common_2F8F
    CheckPartyMonHasMove VAR_0x800C, MOVE_DRACO_METEOR, 32768
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Common_2F9C
    GetPartyMonFriendship VAR_0x800C, 32768
    CompareVarToValue VAR_0x800C, 255
    GoToIf 0, Common_2FAE
    SetVarFromValue VAR_0x8003, 434
    GoTo Common_2FBB
Common_2F07:
    BufferPartyMonNickname 0, 32773
    Message 163
    WaitButton
    CloseMessage
    SetVarFromValue VAR_0x8004, 255
    GoTo Common_0BB2
Common_2F1F:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 187
    GoTo Common_2151
Common_2F32:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 195
    GoTo Common_2886
Common_2F45:
    BufferPartyMonNickname 0, 32768
    BufferMoveName 1, 32771
    Message 204
    GoTo Common_22C9
Common_2F58:
    Message 227
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2F65:
    GetPartyMonType VAR_0x8004, VAR_0x8005, 32768
    CompareVarToValue VAR_0x8004, 16
    GoToIf 1, Common_2FF9
    CompareVarToValue VAR_0x8005, 16
    GoToIf 1, Common_2FF9
    SetVarFromValue VAR_0x800C, 0
    Return
Common_2F8F:
    Message 226
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2F9C:
    BufferMoveName 0, MOVE_DRACO_METEOR
    Message 228
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2FAE:
    Message 225
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2FBB:
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    OpenMoveTutorMenu 32768, MOVE_DRACO_METEOR
    CheckLearnedTutorMove VAR_0x800C
    ReturnToField
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    CompareVarToValue VAR_0x800C, 255
    GoToIf 1, Common_2435
    Message 229
    WaitButton
    CloseMessage
    GoTo Common_2151
Common_2FF9:
    SetVarFromValue VAR_0x800C, 1
    Return
    .byte 0

Common_Movement_3002:
    FaceWest 1
    EndMovement

Common_Movement_300A:
    FaceEast 1
    EndMovement

Common_Movement_3012:
    PlayerGive 1
    EndMovement

Common_Movement_301A:
    PlayerReceive 1
    EndMovement

Common_Movement_3022:
    PokecenterNurseBow 1
    Delay4 1
    EndMovement

Common_Movement_302E:
    FaceWest 1
    EndMovement

Common_Movement_3036:
    FaceSouth 1
    EndMovement

