@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry SunyshoreCityGymRoom3_Entry0
    ScriptEntry SunyshoreCityGymRoom3_Entry1
    ScriptEntry SunyshoreCityGymRoom3_Entry2
    ScriptEntry SunyshoreCityGymRoom3_Entry3
    ScriptEntry SunyshoreCityGymRoom3_Entry4
    ScriptEntry SunyshoreCityGymRoom3_Entry5
    ScriptEntryEnd

SunyshoreCityGymRoom3_Entry0:
    SetVarFromValue VARS_START, 0
    InitPersistedMapFeaturesForSunyshoreGym 2
    End
SunyshoreCityGymRoom3_Entry1:
    PressSunyshoreGymButton 0
    End
SunyshoreCityGymRoom3_Entry2:
    PressSunyshoreGymButton 2
    End
SunyshoreCityGymRoom3_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0957
    GoToIf 1, SunyshoreCityGymRoom3_012F
    GetLeagueVictories 32780
    CompareVarToValue VAR_0x800C, 1
    GoToIf 4, SunyshoreCityGymRoom3_013A
    CheckBadgeAcquired 7, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SunyshoreCityGymRoom3_0169
    CreateJournalEvent 9, 156, 0, 0, 0
    Message 0
    CloseMessage
    StartTrainerBattle 320, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SunyshoreCityGymRoom3_017F
    Message 1
    BufferPlayerName 0
    Message 2
    PlayFanfare SEQ_BADGE_sseq
    WaitFanfare
    GiveBadge 7
    IncrementTrainerScore2 23
    SetTrainerFlag TRAINER_ACE_TRAINER_ZACHERY
    SetTrainerFlag TRAINER_ACE_TRAINER_DESTINY
    SetTrainerFlag TRAINER_GUITARIST_JERRY
    SetTrainerFlag TRAINER_GUITARIST_PRESTON
    SetTrainerFlag TRAINER_GUITARIST_LONNIE
    SetTrainerFlag TRAINER_POKE_KID_MEGHAN
    SetTrainerFlag TRAINER_SCHOOL_KID_FORREST
    SetTrainerFlag TRAINER_SCHOOL_KID_TIERA
    SetVarFromValue VAR_SUNYSHORE_CITY_STATE, 2
    CreateJournalEvent 10, 156, 246, 0, 0
    Message 3
    GoTo SunyshoreCityGymRoom3_0185
SunyshoreCityGymRoom3_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A6B
    GoToIf 0, SunyshoreCityGymRoom3_01DE
    Message 11
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SunyshoreCityGymRoom3_01ED
    GoTo SunyshoreCityGymRoom3_01D8
SunyshoreCityGymRoom3_Entry5:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 12
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SunyshoreCityGymRoom3_021F
    GoTo SunyshoreCityGymRoom3_01D8
SunyshoreCityGymRoom3_012F:
    Message 8
    WaitButton
    CloseMessage
    ReleaseAll
    End
SunyshoreCityGymRoom3_013A:
    Message 6
    WaitButton
    CloseMessage
    ReleaseAll
    StartTrainerBattle 855, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SunyshoreCityGymRoom3_017F
    Message 7
    SetFlag FLAG_UNK_0x0957
    WaitButton
    CloseMessage
    ReleaseAll
    End
SunyshoreCityGymRoom3_0169:
    CheckFlag FLAG_RECEIVED_VOLKNER_TM57
    GoToIf 0, SunyshoreCityGymRoom3_0185
    Message 5
    WaitButton
    CloseMessage
    ReleaseAll
    End
SunyshoreCityGymRoom3_017F:
    BlackOutFromBattle
    ReleaseAll
    End
SunyshoreCityGymRoom3_0185:
    SetVarFromValue VAR_0x8004, 384
    SetVarFromValue VAR_0x8005, 1
    SetVarFromValue VAR_OBJ_GFX_ID_6, 78
    CanFitItem 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SunyshoreCityGymRoom3_01CE
    CallCommonScript 2044
    SetFlag FLAG_RECEIVED_VOLKNER_TM57
    BufferItemName 0, 32772
    BufferTMHMMoveName 1, 32772
    Message 4
    WaitButton
    CloseMessage
    Message 9
    CloseMessage
    ReleaseAll
    End
SunyshoreCityGymRoom3_01CE:
    CallCommonScript 2017
    CloseMessage
    ReleaseAll
    End
SunyshoreCityGymRoom3_01D8:
    CloseMessage
    ReleaseAll
    End
SunyshoreCityGymRoom3_01DE:
    Message 10
    WaitButton
    CloseMessage
    SetFlag FLAG_UNK_0x0A6B
    ReleaseAll
    End
SunyshoreCityGymRoom3_01ED:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 154, 8, 14, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SunyshoreCityGymRoom3_021F:
    CloseMessage
    PlayCry SPECIES_HAPPINY, 0
    WaitCry
    HealParty
    Message 13
    WaitButton
    CloseMessage
    ReleaseAll
    End
