@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry VeilstoneCity_Entry0
    ScriptEntry VeilstoneCity_Entry1
    ScriptEntry VeilstoneCity_Entry2
    ScriptEntry VeilstoneCity_Entry3
    ScriptEntry VeilstoneCity_Entry4
    ScriptEntry VeilstoneCity_Entry5
    ScriptEntry VeilstoneCity_Entry6
    ScriptEntry VeilstoneCity_Entry7
    ScriptEntry VeilstoneCity_Entry8
    ScriptEntry VeilstoneCity_Entry9
    ScriptEntry VeilstoneCity_Entry10
    ScriptEntry VeilstoneCity_Entry11
    ScriptEntry VeilstoneCity_Entry12
    ScriptEntry VeilstoneCity_Entry13
    ScriptEntry VeilstoneCity_Entry14
    ScriptEntry VeilstoneCity_Entry15
    ScriptEntry VeilstoneCity_Entry16
    ScriptEntry VeilstoneCity_Entry17
    ScriptEntry VeilstoneCity_Entry18
    ScriptEntry VeilstoneCity_Entry19
    ScriptEntry VeilstoneCity_Entry20
    ScriptEntry VeilstoneCity_Entry21
    ScriptEntry VeilstoneCity_Entry22
    ScriptEntry VeilstoneCity_Entry23
    ScriptEntry VeilstoneCity_Entry24
    ScriptEntry VeilstoneCity_Entry25
    ScriptEntry VeilstoneCity_Entry26
    ScriptEntry VeilstoneCity_Entry27
    ScriptEntry VeilstoneCity_Entry28
    ScriptEntry VeilstoneCity_Entry29
    ScriptEntry VeilstoneCity_Entry30
    ScriptEntry VeilstoneCity_Entry31
    ScriptEntry VeilstoneCity_Entry32
    ScriptEntry VeilstoneCity_Entry33
    ScriptEntryEnd

VeilstoneCity_Entry0:
    CheckFlag FLAG_VEILSTONE_CITY_GRUNT_DROPPED_STORAGE_KEY
    CallIf 1, VeilstoneCity_0758
    CompareVarToValue VAR_VEILSTONE_CITY_COUNTERPART_NEEDS_HELP_STATE, 2
    CallIf 4, VeilstoneCity_076E
    GetPlayerGender VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, VeilstoneCity_0784
    CompareVarToValue VARS_START, 1
    GoToIf 1, VeilstoneCity_078C
    End
VeilstoneCity_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 43
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 49
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 44
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 45
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry5:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 46
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry6:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_RECEIVED_VEILSTONE_CITY_TM63
    GoToIf 1, VeilstoneCity_0794
    Message 50
    SetVarFromValue VAR_0x8004, 390
    SetVarFromValue VAR_0x8005, 1
    CanFitItem 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_079F
    CallCommonScript 2044
    SetFlag FLAG_RECEIVED_VEILSTONE_CITY_TM63
    GoTo VeilstoneCity_0794
VeilstoneCity_Entry7:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 47
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry8:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 48
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry9:
    LockAll
    ApplyMovement 7, VeilstoneCity_Movement_1020
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_102C
    WaitMovement
    Message 11
    CloseMessage
    ApplyMovement 7, VeilstoneCity_Movement_1034
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_104C
    WaitMovement
    ReleaseAll
    End
VeilstoneCity_Entry10:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckBadgeAcquired 2, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, VeilstoneCity_07A9
    Message 12
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry11:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckBadgeAcquired 2, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, VeilstoneCity_07B4
    Message 13
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry12:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 36
    CloseMessage
    FacePlayer
    ApplyMovement 23, VeilstoneCity_Movement_1054
    WaitMovement
    Message 37
    CloseMessage
    SetFlag FLAG_VEILSTONE_CITY_GRUNT_DROPPED_STORAGE_KEY
    SetObjectEventPos 26, 723, 601
    SetObjectEventMovementType 26, 14
    SetObjectEventDir 26, 0
    ClearFlag FLAG_HIDE_VEILSTONE_CITY_LOOKER
    AddObject 26
    GetPlayerDir VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_07BF
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, VeilstoneCity_07E5
    CompareVarToValue VAR_0x800C, 2
    GoToIf 1, VeilstoneCity_0803
    CompareVarToValue VAR_0x800C, 3
    GoToIf 1, VeilstoneCity_0829
    End
VeilstoneCity_Entry13:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 42
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry14:
    LockAll
    ApplyMovement 6, VeilstoneCity_Movement_105C
    WaitMovement
    CallCommonScript 2040
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8004, 681
    CallIf 1, VeilstoneCity_084F
    CompareVarToValue VAR_0x8004, 682
    CallIf 1, VeilstoneCity_085B
    CompareVarToValue VAR_0x8004, 683
    CallIf 1, VeilstoneCity_0867
    CompareVarToValue VAR_0x8004, 684
    CallIf 1, VeilstoneCity_0873
    GetPlayerGender VAR_0x8004
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, VeilstoneCity_087F
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, VeilstoneCity_0887
    CloseMessage
    CallCommonScript 2041
    LoadDoorAnimation 21, 19, 12, 3, 77
    PlayDoorOpenAnimation 77
    WaitForAnimation 77
    ClearFlag FLAG_HIDE_VEILSTONE_CRASHER_WAKE
    AddObject 25
    ApplyMovement 25, VeilstoneCity_Movement_1070
    WaitMovement
    PlayDoorCloseAnimation 77
    WaitForAnimation 77
    UnloadAnimation 77
    ApplyMovement 6, VeilstoneCity_Movement_1078
    WaitMovement
    Message 4
    CloseMessage
    ApplyMovement 25, VeilstoneCity_Movement_1080
    WaitMovement
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8004, 681
    CallIf 1, VeilstoneCity_088F
    CompareVarToValue VAR_0x8004, 682
    CallIf 1, VeilstoneCity_08AB
    CompareVarToValue VAR_0x8004, 683
    CallIf 1, VeilstoneCity_08C7
    CompareVarToValue VAR_0x8004, 684
    CallIf 1, VeilstoneCity_08E3
    Message 5
    Message 6
    CloseMessage
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8004, 681
    CallIf 1, VeilstoneCity_08FF
    CompareVarToValue VAR_0x8004, 682
    CallIf 1, VeilstoneCity_091B
    CompareVarToValue VAR_0x8004, 683
    CallIf 1, VeilstoneCity_0937
    CompareVarToValue VAR_0x8004, 684
    CallIf 1, VeilstoneCity_0953
    RemoveObject 25
    WaitTime 20, VAR_0x800C
    GetPlayerGender VAR_0x8004
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, VeilstoneCity_096F
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, VeilstoneCity_098C
    CloseMessage
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8004, 681
    CallIf 1, VeilstoneCity_09A9
    CompareVarToValue VAR_0x8004, 682
    CallIf 1, VeilstoneCity_09BD
    CompareVarToValue VAR_0x8004, 683
    CallIf 1, VeilstoneCity_09D1
    CompareVarToValue VAR_0x8004, 684
    CallIf 1, VeilstoneCity_09E5
    RemoveObject 6
    SetVarFromValue VAR_VEILSTONE_CITY_CRASHER_WAKE_STATE, 1
    ReleaseAll
    End
VeilstoneCity_Entry15:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    GetPlayerGender VAR_0x8004
    CompareVarToValue VAR_0x8004, 0
    GoToIf 1, VeilstoneCity_09F9
    CompareVarToValue VAR_0x8004, 1
    GoToIf 1, VeilstoneCity_0A16
    End
VeilstoneCity_Entry16:
    DrawSignpostInstantMessage 61, 0, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
VeilstoneCity_Entry17:
    DrawSignpostTextBox 3, 0
    SetSignpostCommand 3
    WaitForSignpostDone
    DrawSignpostScrollingMessage 62, VAR_0x800C
    CallCommonScript 2000
    End
VeilstoneCity_Entry18:
    DrawSignpostInstantMessage 63, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
VeilstoneCity_Entry19:
    DrawSignpostInstantMessage 64, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
VeilstoneCity_Entry20:
    DrawSignpostInstantMessage 65, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
VeilstoneCity_Entry21:
    DrawSignpostInstantMessage 66, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
VeilstoneCity_Entry22:
    DrawSignpostInstantMessage 67, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
VeilstoneCity_Entry23:
    DrawSignpostInstantMessage 68, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
VeilstoneCity_Entry24:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CheckPartyHasSpecies2 SPECIES_DEOXYS, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_0A33
    ChangeDeoxysForm 3
    PlayCry SPECIES_DEOXYS, 0
    Message 57
    WaitButton
    WaitCry
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry25:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CheckPartyHasSpecies2 SPECIES_DEOXYS, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_0A33
    ChangeDeoxysForm 2
    PlayCry SPECIES_DEOXYS, 0
    Message 58
    WaitButton
    WaitCry
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry26:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CheckPartyHasSpecies2 SPECIES_DEOXYS, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_0A33
    ChangeDeoxysForm 1
    PlayCry SPECIES_DEOXYS, 0
    Message 59
    WaitButton
    WaitCry
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry27:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CheckPartyHasSpecies2 SPECIES_DEOXYS, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_0A33
    ChangeDeoxysForm 0
    PlayCry SPECIES_DEOXYS, 0
    Message 60
    WaitButton
    WaitCry
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry28:
    LockAll
    ApplyMovement 6, VeilstoneCity_Movement_1088
    WaitMovement
    GetPlayerGender VAR_0x8004
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, VeilstoneCity_0A3E
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, VeilstoneCity_0A46
    CloseMessage
    ApplyMovement 6, VeilstoneCity_Movement_109C
    WaitMovement
    RemoveObject 6
    Call VeilstoneCity_076E
    ClearFlag FLAG_HIDE_VEILSTONE_COUNTERPART
    AddObject 6
    SetVarFromValue VAR_VEILSTONE_CITY_COUNTERPART_NEEDS_HELP_STATE, 2
    ReleaseAll
    End
VeilstoneCity_Entry29:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    ApplyMovement 26, VeilstoneCity_Movement_10A4
    WaitMovement
    BufferPlayerName 0
    Message 41
    CallCommonScript 2055
    CheckFlag FLAG_AGREED_WITH_LOOKER_TO_ENTER_HIDEOUT
    GoToIf 1, VeilstoneCity_0A4E
    GoTo VeilstoneCity_0A65
VeilstoneCity_Entry30:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 52
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, VeilstoneCity_0A7F
    Message 53
    GoTo VeilstoneCity_0A88
VeilstoneCity_Entry31:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 55
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_Entry32:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A83
    GoToIf 0, VeilstoneCity_0A90
    Message 70
    InitLocalTextListMenu 1, 1, 0, VAR_0x800C, 1
    CheckFlag FLAG_UNK_0x0A84
    CallIf 1, VeilstoneCity_0A9D
    CheckFlag FLAG_UNK_0x0A82
    CallIf 1, VeilstoneCity_0AA7
    CheckFlag FLAG_UNK_0x0A81
    CallIf 1, VeilstoneCity_0AB1
    CheckFlag FLAG_UNK_0x0A7E
    CallIf 1, VeilstoneCity_0ABB
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, VeilstoneCity_0AC5
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, VeilstoneCity_0AF7
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, VeilstoneCity_0B29
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, VeilstoneCity_0B5B
    GoTo VeilstoneCity_0B8D
VeilstoneCity_Entry33:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 75
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, VeilstoneCity_0B93
    GetPartyCount VAR_0x8001
    CountPartyMonsBelowLevelThreshold VAR_0x8002, 38
    SubVar VAR_0x8001, VAR_0x8002
    CompareVarToValue VAR_0x8001, 0
    GoToIf 2, VeilstoneCity_0B9E
    Message 76
    CloseMessage
    Call VeilstoneCity_0BA9
    End
VeilstoneCity_0758:
    SetObjectEventPos 26, 717, 593
    SetObjectEventMovementType 26, 14
    SetObjectEventDir 26, 0
    Return
VeilstoneCity_076E:
    SetObjectEventPos 6, 696, 596
    SetObjectEventMovementType 6, 17
    SetObjectEventDir 6, 3
    Return
VeilstoneCity_0784:
    SetVarFromValue OBJ_GFX_VARS_START, 97
    End
VeilstoneCity_078C:
    SetVarFromValue OBJ_GFX_VARS_START, 0
    End
VeilstoneCity_0794:
    Message 51
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_079F:
    CallCommonScript 2017
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_07A9:
    Message 14
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_07B4:
    Message 15
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_07BF:
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_10B4
    ApplyMovement 23, VeilstoneCity_Movement_10C4
    WaitMovement
    CallCommonScript 2055
    ApplyMovement 26, VeilstoneCity_Movement_10D8
    WaitMovement
    GoTo VeilstoneCity_0BC6
VeilstoneCity_07E5:
    ApplyMovement 23, VeilstoneCity_Movement_10C4
    WaitMovement
    CallCommonScript 2055
    ApplyMovement 26, VeilstoneCity_Movement_10E8
    WaitMovement
    GoTo VeilstoneCity_0BC6
VeilstoneCity_0803:
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_10F8
    ApplyMovement 23, VeilstoneCity_Movement_1104
    WaitMovement
    CallCommonScript 2055
    ApplyMovement 26, VeilstoneCity_Movement_1114
    WaitMovement
    GoTo VeilstoneCity_0BC6
VeilstoneCity_0829:
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1124
    ApplyMovement 23, VeilstoneCity_Movement_10C4
    WaitMovement
    CallCommonScript 2055
    ApplyMovement 26, VeilstoneCity_Movement_1130
    WaitMovement
    GoTo VeilstoneCity_0BC6
VeilstoneCity_084F:
    ApplyMovement 6, VeilstoneCity_Movement_1140
    WaitMovement
    Return
VeilstoneCity_085B:
    ApplyMovement 6, VeilstoneCity_Movement_114C
    WaitMovement
    Return
VeilstoneCity_0867:
    ApplyMovement 6, VeilstoneCity_Movement_1154
    WaitMovement
    Return
VeilstoneCity_0873:
    ApplyMovement 6, VeilstoneCity_Movement_1160
    WaitMovement
    Return
VeilstoneCity_087F:
    BufferPlayerName 0
    Message 2
    Return
VeilstoneCity_0887:
    BufferPlayerName 0
    Message 3
    Return
VeilstoneCity_088F:
    ApplyMovement 25, VeilstoneCity_Movement_116C
    ApplyMovement 6, VeilstoneCity_Movement_1178
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1184
    WaitMovement
    Return
VeilstoneCity_08AB:
    ApplyMovement 25, VeilstoneCity_Movement_1194
    ApplyMovement 6, VeilstoneCity_Movement_11A0
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_11AC
    WaitMovement
    Return
VeilstoneCity_08C7:
    ApplyMovement 25, VeilstoneCity_Movement_11BC
    ApplyMovement 6, VeilstoneCity_Movement_11C8
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_11D4
    WaitMovement
    Return
VeilstoneCity_08E3:
    ApplyMovement 25, VeilstoneCity_Movement_11E4
    ApplyMovement 6, VeilstoneCity_Movement_11F8
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1204
    WaitMovement
    Return
VeilstoneCity_08FF:
    ApplyMovement 25, VeilstoneCity_Movement_1214
    ApplyMovement 6, VeilstoneCity_Movement_121C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1228
    WaitMovement
    Return
VeilstoneCity_091B:
    ApplyMovement 25, VeilstoneCity_Movement_1238
    ApplyMovement 6, VeilstoneCity_Movement_121C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1228
    WaitMovement
    Return
VeilstoneCity_0937:
    ApplyMovement 25, VeilstoneCity_Movement_1240
    ApplyMovement 6, VeilstoneCity_Movement_121C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1228
    WaitMovement
    Return
VeilstoneCity_0953:
    ApplyMovement 25, VeilstoneCity_Movement_1248
    ApplyMovement 6, VeilstoneCity_Movement_121C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1228
    WaitMovement
    Return
VeilstoneCity_096F:
    BufferPlayerName 0
    Message 7
    CloseMessage
    WaitTime 15, VAR_0x800C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1250
    WaitMovement
    Message 8
    Return
VeilstoneCity_098C:
    BufferPlayerName 0
    Message 9
    CloseMessage
    WaitTime 15, VAR_0x800C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1250
    WaitMovement
    Message 10
    Return
VeilstoneCity_09A9:
    ApplyMovement 6, VeilstoneCity_Movement_1258
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1264
    WaitMovement
    Return
VeilstoneCity_09BD:
    ApplyMovement 6, VeilstoneCity_Movement_1258
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1264
    WaitMovement
    Return
VeilstoneCity_09D1:
    ApplyMovement 6, VeilstoneCity_Movement_1274
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1280
    WaitMovement
    Return
VeilstoneCity_09E5:
    ApplyMovement 6, VeilstoneCity_Movement_1274
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1280
    WaitMovement
    Return
VeilstoneCity_09F9:
    BufferPlayerName 0
    Message 19
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_0BD0
    GoTo VeilstoneCity_0BD9
VeilstoneCity_0A16:
    BufferPlayerName 0
    Message 24
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_0BE4
    GoTo VeilstoneCity_0BED
VeilstoneCity_0A33:
    Message 56
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_0A3E:
    BufferPlayerName 0
    Message 0
    Return
VeilstoneCity_0A46:
    BufferPlayerName 0
    Message 1
    Return
VeilstoneCity_0A4E:
    SetVarFromValue VAR_VEILSTONE_CITY_GALACTIC_WAREHOUSE_STATE, 3
    SetFlag FLAG_AGREED_WITH_LOOKER_TO_ENTER_HIDEOUT
    Message 39
    CloseMessage
    CallCommonScript 2056
    ReleaseAll
    End
VeilstoneCity_0A65:
    Message 38
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_0A4E
    GoTo VeilstoneCity_0BF8
VeilstoneCity_0A7F:
    Message 54
    GoTo VeilstoneCity_0A88
VeilstoneCity_0A88:
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_0A90:
    Message 69
    SetFlag FLAG_UNK_0x0A83
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_0A9D:
    AddListMenuEntry 71, 0, 255
    Return
VeilstoneCity_0AA7:
    AddListMenuEntry 72, 1, 255
    Return
VeilstoneCity_0AB1:
    AddListMenuEntry 73, 2, 255
    Return
VeilstoneCity_0ABB:
    AddListMenuEntry 74, 3, 255
    Return
VeilstoneCity_0AC5:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 433, 566, 657, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
VeilstoneCity_0AF7:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 120, 600, 816, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
VeilstoneCity_0B29:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 442, 472, 539, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
VeilstoneCity_0B5B:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 150, 860, 785, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
VeilstoneCity_0B8D:
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_0B93:
    Message 77
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_0B9E:
    Message 79
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_0BA9:
    StartTrainerBattle 211, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_0C07
    GoTo VeilstoneCity_0C0D
VeilstoneCity_0BC6:
    RemoveObject 23
    GoTo VeilstoneCity_0A65
VeilstoneCity_0BD0:
    Message 20
    GoTo VeilstoneCity_0C18
VeilstoneCity_0BD9:
    Message 21
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_0BE4:
    Message 25
    GoTo VeilstoneCity_0C18
VeilstoneCity_0BED:
    Message 26
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_0BF8:
    Message 40
    WaitButton
    CloseMessage
    CallCommonScript 2056
    ReleaseAll
    End
VeilstoneCity_0C07:
    BlackOutFromBattle
    ReleaseAll
    End
VeilstoneCity_0C0D:
    Message 78
    WaitButton
    CloseMessage
    ReleaseAll
    End
VeilstoneCity_0C18:
    CloseMessage
    GetPlayerDir VAR_0x800C
    CompareVarToValue VAR_0x800C, 3
    CallIf 1, VeilstoneCity_0DFC
    CompareVarToValue VAR_0x800C, 1
    CallIf 1, VeilstoneCity_0E10
    CompareVarToValue VAR_0x800C, 0
    CallIf 1, VeilstoneCity_0E24
    Call VeilstoneCity_0E38
    StartTagBattle 32772, 848, 849
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_0E58
    Message 16
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 595
    CallIf 1, VeilstoneCity_0E5E
    CompareVarToValue VAR_0x8005, 597
    CallIf 1, VeilstoneCity_0E6A
    Message 17
    CloseMessage
    WaitTime 15, VAR_0x800C
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 595
    CallIf 1, VeilstoneCity_0E76
    CompareVarToValue VAR_0x8005, 597
    CallIf 1, VeilstoneCity_0E82
    RemoveObject 7
    Message 18
    CloseMessage
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 595
    CallIf 1, VeilstoneCity_0E8E
    CompareVarToValue VAR_0x8005, 597
    CallIf 1, VeilstoneCity_0E9A
    RemoveObject 20
    GetPlayerGender VAR_0x8004
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, VeilstoneCity_0EA6
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, VeilstoneCity_0EAB
    CloseMessage
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 595
    CallIf 1, VeilstoneCity_0EB0
    CompareVarToValue VAR_0x8005, 597
    CallIf 1, VeilstoneCity_0EC4
    WaitTime 10, VAR_0x800C
    BufferPlayerName 0
    GetPlayerGender VAR_0x8004
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, VeilstoneCity_0ED8
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, VeilstoneCity_0EDD
    CloseMessage
    WaitTime 15, VAR_0x800C
    ClearFlag FLAG_HIDE_VEILSTONE_CITY_LOOKER
    SetObjectEventPos 26, 692, 606
    AddObject 26
    CallCommonScript 2055
    ApplyMovement 26, VeilstoneCity_Movement_1290
    WaitMovement
    Message 29
    CloseMessage
    ApplyMovement 6, VeilstoneCity_Movement_129C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_12A4
    WaitMovement
    GetPlayerGender VAR_0x8004
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, VeilstoneCity_0EE2
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, VeilstoneCity_0EE7
    Message 32
    GetPlayerGender VAR_0x8004
    CompareVarToValue VAR_0x8004, 0
    CallIf 1, VeilstoneCity_0EEC
    CompareVarToValue VAR_0x8004, 1
    CallIf 1, VeilstoneCity_0EF1
    CloseMessage
    ApplyMovement 6, VeilstoneCity_Movement_12AC
    ApplyMovement 26, VeilstoneCity_Movement_12B8
    WaitMovement
    RemoveObject 6
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 595
    GoToIf 1, VeilstoneCity_0EF6
    CompareVarToValue VAR_0x8005, 597
    GoToIf 1, VeilstoneCity_0F0E
    End
VeilstoneCity_0DFC:
    ApplyMovement 6, VeilstoneCity_Movement_12C4
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_12D0
    WaitMovement
    Return
VeilstoneCity_0E10:
    ApplyMovement 6, VeilstoneCity_Movement_12DC
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_12E8
    WaitMovement
    Return
VeilstoneCity_0E24:
    ApplyMovement 6, VeilstoneCity_Movement_12F0
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_12FC
    WaitMovement
    Return
VeilstoneCity_0E38:
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VeilstoneCity_0F26
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, VeilstoneCity_0F58
    End
VeilstoneCity_0E58:
    BlackOutFromBattle
    ReleaseAll
    End
VeilstoneCity_0E5E:
    ApplyMovement 20, VeilstoneCity_Movement_1304
    WaitMovement
    Return
VeilstoneCity_0E6A:
    ApplyMovement 7, VeilstoneCity_Movement_1304
    WaitMovement
    Return
VeilstoneCity_0E76:
    ApplyMovement 7, VeilstoneCity_Movement_130C
    WaitMovement
    Return
VeilstoneCity_0E82:
    ApplyMovement 7, VeilstoneCity_Movement_130C
    WaitMovement
    Return
VeilstoneCity_0E8E:
    ApplyMovement 20, VeilstoneCity_Movement_131C
    WaitMovement
    Return
VeilstoneCity_0E9A:
    ApplyMovement 20, VeilstoneCity_Movement_131C
    WaitMovement
    Return
VeilstoneCity_0EA6:
    Message 22
    Return
VeilstoneCity_0EAB:
    Message 27
    Return
VeilstoneCity_0EB0:
    ApplyMovement 6, VeilstoneCity_Movement_132C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1334
    WaitMovement
    Return
VeilstoneCity_0EC4:
    ApplyMovement 6, VeilstoneCity_Movement_133C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1344
    WaitMovement
    Return
VeilstoneCity_0ED8:
    Message 23
    Return
VeilstoneCity_0EDD:
    Message 28
    Return
VeilstoneCity_0EE2:
    Message 30
    Return
VeilstoneCity_0EE7:
    Message 31
    Return
VeilstoneCity_0EEC:
    Message 33
    Return
VeilstoneCity_0EF1:
    Message 34
    Return
VeilstoneCity_0EF6:
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_134C
    ApplyMovement 26, VeilstoneCity_Movement_1358
    WaitMovement
    GoTo VeilstoneCity_0F8A
VeilstoneCity_0F0E:
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_1364
    ApplyMovement 26, VeilstoneCity_Movement_1370
    WaitMovement
    GoTo VeilstoneCity_0F8A
VeilstoneCity_0F26:
    GetPlayerStarterSpecies VAR_0x800C
    SetVarFromValue VAR_0x8004, 625
    CompareVarToValue VAR_0x800C, 390
    GoToIf 1, VeilstoneCity_0FB1
    SetVarFromValue VAR_0x8004, 626
    CompareVarToValue VAR_0x800C, 393
    GoToIf 1, VeilstoneCity_0FB1
    SetVarFromValue VAR_0x8004, 624
    Return
VeilstoneCity_0F58:
    GetPlayerStarterSpecies VAR_0x800C
    SetVarFromValue VAR_0x8004, 622
    CompareVarToValue VAR_0x800C, 390
    GoToIf 1, VeilstoneCity_0FB1
    SetVarFromValue VAR_0x8004, 623
    CompareVarToValue VAR_0x800C, 393
    GoToIf 1, VeilstoneCity_0FB1
    SetVarFromValue VAR_0x8004, 621
    Return
VeilstoneCity_0F8A:
    Message 35
    CloseMessage
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 595
    GoToIf 1, VeilstoneCity_0FB3
    CompareVarToValue VAR_0x8005, 597
    GoToIf 1, VeilstoneCity_0FCB
    End
VeilstoneCity_0FB1:
    Return
VeilstoneCity_0FB3:
    ApplyMovement 26, VeilstoneCity_Movement_137C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_138C
    WaitMovement
    GoTo VeilstoneCity_0FE3
VeilstoneCity_0FCB:
    ApplyMovement 26, VeilstoneCity_Movement_137C
    ApplyMovement LOCALID_PLAYER, VeilstoneCity_Movement_13A0
    WaitMovement
    GoTo VeilstoneCity_0FE3
VeilstoneCity_0FE3:
    SetFlag FLAG_HIDE_PASTORIA_CITY_RIVAL
    SetFlag FLAG_HIDE_VEILSTONE_CITY_LOOKER
    ClearFlag FLAG_HIDE_VEILSTONE_CITY_GALACTIC_WAREHOUSE_LOOKER
    SetVarFromValue VAR_VEILSTONE_CITY_GALACTIC_WAREHOUSE_STATE, 1
    PlaySE SEQ_SE_DP_KAIDAN2_sseq
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 143, 8, 11, 0
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    End
    .balign 4, 0

VeilstoneCity_Movement_1020:
    WalkOnSpotNormalSouth 1
    EmoteExclamationMark 1
    EndMovement

VeilstoneCity_Movement_102C:
    WalkOnSpotNormalNorth 1
    EndMovement

VeilstoneCity_Movement_1034:
    WalkFastSouth 1
    WalkOnSpotNormalWest 1
    Delay8 2
    WalkNormalNorth 1
    WalkOnSpotNormalWest 1
    EndMovement

VeilstoneCity_Movement_104C:
    WalkNormalWest 1
    EndMovement

VeilstoneCity_Movement_1054:
    EmoteExclamationMark 1
    EndMovement

VeilstoneCity_Movement_105C:
    Delay8 1
    WalkOnSpotNormalSouth 1
    EmoteExclamationMark 1
    Delay8 1
    EndMovement

VeilstoneCity_Movement_1070:
    WalkNormalSouth 1
    EndMovement

VeilstoneCity_Movement_1078:
    WalkOnSpotFastNorth 1
    EndMovement

VeilstoneCity_Movement_1080:
    EmoteExclamationMark 1
    EndMovement

VeilstoneCity_Movement_1088:
    WalkOnSpotNormalNorth 1
    EmoteExclamationMark 1
    WalkNormalEast 2
    WalkNormalNorth 1
    EndMovement

VeilstoneCity_Movement_109C:
    WalkNormalSouth 9
    EndMovement

VeilstoneCity_Movement_10A4:
    Delay8 1
    EmoteExclamationMark 1
    Delay8 1
    EndMovement

VeilstoneCity_Movement_10B4:
    Delay8 1
    WalkOnSpotNormalEast 1
    WalkOnSpotNormalSouth 1
    EndMovement

VeilstoneCity_Movement_10C4:
    WalkFastEast 1
    WalkFastSouth 2
    WalkFastEast 1
    WalkFastSouth 9
    EndMovement

VeilstoneCity_Movement_10D8:
    WalkNormalNorth 6
    WalkNormalWest 2
    WalkOnSpotNormalNorth 1
    EndMovement

VeilstoneCity_Movement_10E8:
    WalkNormalNorth 6
    WalkNormalWest 2
    WalkNormalNorth 2
    EndMovement

VeilstoneCity_Movement_10F8:
    Delay8 1
    WalkOnSpotNormalSouth 1
    EndMovement

VeilstoneCity_Movement_1104:
    WalkFastSouth 2
    WalkFastEast 2
    WalkFastSouth 9
    EndMovement

VeilstoneCity_Movement_1114:
    WalkNormalNorth 6
    WalkNormalWest 1
    WalkNormalNorth 1
    EndMovement

VeilstoneCity_Movement_1124:
    Delay8 2
    WalkOnSpotNormalSouth 1
    EndMovement

VeilstoneCity_Movement_1130:
    WalkNormalNorth 6
    WalkNormalWest 3
    WalkNormalNorth 1
    EndMovement

VeilstoneCity_Movement_1140:
    WalkNormalWest 1
    WalkNormalSouth 1
    EndMovement

VeilstoneCity_Movement_114C:
    WalkNormalSouth 1
    EndMovement

VeilstoneCity_Movement_1154:
    WalkNormalEast 1
    WalkNormalSouth 1
    EndMovement

VeilstoneCity_Movement_1160:
    WalkNormalEast 2
    WalkNormalSouth 1
    EndMovement

VeilstoneCity_Movement_116C:
    WalkNormalSouth 4
    WalkNormalWest 2
    EndMovement

VeilstoneCity_Movement_1178:
    Delay8 4
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_1184:
    Delay8 4
    Delay4 1
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_1194:
    WalkNormalSouth 4
    WalkNormalWest 1
    EndMovement

VeilstoneCity_Movement_11A0:
    Delay8 3
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_11AC:
    Delay8 3
    Delay4 1
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_11BC:
    WalkNormalSouth 4
    WalkOnSpotNormalWest 1
    EndMovement

VeilstoneCity_Movement_11C8:
    Delay8 2
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_11D4:
    Delay8 2
    Delay4 1
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_11E4:
    WalkNormalSouth 1
    WalkNormalWest 1
    WalkNormalSouth 3
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_11F8:
    Delay8 4
    WalkOnSpotNormalWest 1
    EndMovement

VeilstoneCity_Movement_1204:
    Delay8 4
    Delay4 1
    WalkOnSpotNormalWest 1
    EndMovement

VeilstoneCity_Movement_1214:
    WalkNormalSouth 8
    EndMovement

VeilstoneCity_Movement_121C:
    Delay8 1
    WalkOnSpotNormalSouth 1
    EndMovement

VeilstoneCity_Movement_1228:
    Delay8 1
    Delay4 1
    WalkOnSpotNormalSouth 1
    EndMovement

VeilstoneCity_Movement_1238:
    WalkNormalSouth 8
    EndMovement

VeilstoneCity_Movement_1240:
    WalkNormalSouth 8
    EndMovement

VeilstoneCity_Movement_1248:
    WalkNormalSouth 8
    EndMovement

VeilstoneCity_Movement_1250:
    WalkOnSpotNormalNorth 1
    EndMovement

VeilstoneCity_Movement_1258:
    WalkNormalEast 1
    WalkNormalSouth 9
    EndMovement

VeilstoneCity_Movement_1264:
    Delay8 2
    WalkOnSpotNormalEast 1
    WalkOnSpotNormalSouth 1
    EndMovement

VeilstoneCity_Movement_1274:
    WalkNormalWest 1
    WalkNormalSouth 9
    EndMovement

VeilstoneCity_Movement_1280:
    Delay8 2
    WalkOnSpotNormalWest 1
    WalkOnSpotNormalSouth 1
    EndMovement

VeilstoneCity_Movement_1290:
    WalkFastNorth 10
    WalkFastEast 3
    EndMovement

VeilstoneCity_Movement_129C:
    WalkOnSpotFastWest 1
    EndMovement

VeilstoneCity_Movement_12A4:
    WalkOnSpotNormalWest 1
    EndMovement

VeilstoneCity_Movement_12AC:
    WalkNormalWest 3
    WalkNormalSouth 10
    EndMovement

VeilstoneCity_Movement_12B8:
    Delay8 2
    WalkOnSpotNormalWest 1
    EndMovement

VeilstoneCity_Movement_12C4:
    WalkNormalSouth 1
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_12D0:
    WalkNormalNorth 1
    WalkNormalEast 1
    EndMovement

VeilstoneCity_Movement_12DC:
    WalkNormalSouth 1
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_12E8:
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_12F0:
    WalkNormalNorth 1
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_12FC:
    WalkOnSpotNormalEast 1
    EndMovement

VeilstoneCity_Movement_1304:
    WalkOnSpotNormalWest 1
    EndMovement

VeilstoneCity_Movement_130C:
    WalkFastEast 4
    WalkFastNorth 4
    WalkOnSpotFastNorth 1
    EndMovement

VeilstoneCity_Movement_131C:
    WalkFastEast 4
    WalkFastNorth 6
    WalkOnSpotFastNorth 1
    EndMovement

VeilstoneCity_Movement_132C:
    WalkOnSpotNormalNorth 1
    EndMovement

VeilstoneCity_Movement_1334:
    WalkOnSpotNormalSouth 1
    EndMovement

VeilstoneCity_Movement_133C:
    WalkOnSpotNormalSouth 1
    EndMovement

VeilstoneCity_Movement_1344:
    WalkOnSpotNormalNorth 1
    EndMovement

VeilstoneCity_Movement_134C:
    Delay8 1
    FaceSouth 1
    EndMovement

VeilstoneCity_Movement_1358:
    WalkNormalEast 1
    WalkOnSpotNormalNorth 1
    EndMovement

VeilstoneCity_Movement_1364:
    Delay8 1
    FaceNorth 1
    EndMovement

VeilstoneCity_Movement_1370:
    WalkNormalEast 1
    WalkOnSpotNormalSouth 1
    EndMovement

VeilstoneCity_Movement_137C:
    WalkNormalEast 5
    WalkNormalNorth 4
    SetInvisible 1
    EndMovement

VeilstoneCity_Movement_138C:
    WalkNormalSouth 1
    WalkNormalEast 5
    WalkNormalNorth 5
    SetInvisible 1
    EndMovement

VeilstoneCity_Movement_13A0:
    WalkNormalNorth 1
    WalkNormalEast 5
    WalkNormalNorth 5
    SetInvisible 1
    EndMovement

