@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry SnowpointCityGym_Entry0
    ScriptEntry SnowpointCityGym_Entry1
    ScriptEntry SnowpointCityGym_Entry2
    ScriptEntry SnowpointCityGym_Entry3
    ScriptEntry SnowpointCityGym_Entry4
    ScriptEntry SnowpointCityGym_Entry5
    ScriptEntry SnowpointCityGym_Entry6
    ScriptEntryEnd

SnowpointCityGym_Entry0:
    CheckFlag FLAG_DUMMY_0x00EB
    GoToIf 1, SnowpointCityGym_019E
    End
SnowpointCityGym_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0958
    GoToIf 1, SnowpointCityGym_01A4
    GetLeagueVictories 32780
    CompareVarToValue VAR_0x800C, 1
    GoToIf 4, SnowpointCityGym_01AF
    CheckBadgeAcquired 6, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SnowpointCityGym_01DE
    CreateJournalEvent 9, 167, 0, 0, 0
    Message 0
    CloseMessage
    StartTrainerBattle 319, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SnowpointCityGym_01F4
    Message 1
    BufferPlayerName 0
    Message 2
    PlayFanfare SEQ_BADGE_sseq
    WaitFanfare
    GiveBadge 6
    IncrementTrainerScore2 23
    SetTrainerFlag TRAINER_ACE_TRAINER_SERGIO
    SetTrainerFlag TRAINER_ACE_TRAINER_ISAIAH
    SetTrainerFlag TRAINER_ACE_TRAINER_ANTON
    SetTrainerFlag TRAINER_ACE_TRAINER_SAVANNAH
    SetTrainerFlag TRAINER_ACE_TRAINER_ALICIA
    SetTrainerFlag TRAINER_ACE_TRAINER_BRENNA
    CreateJournalEvent 10, 167, 319, 0, 0
    SetFlag FLAG_HIDE_VEILSTONE_GALACTIC_GRUNTS
    Message 3
    GoTo SnowpointCityGym_01FA
SnowpointCityGym_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckBadgeAcquired 6, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SnowpointCityGym_0243
    Message 6
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCityGym_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CheckBadgeAcquired 6, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SnowpointCityGym_0251
    BufferRivalName 0
    BufferRivalName 1
    Message 8
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCityGym_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A6D
    GoToIf 0, SnowpointCityGym_026F
    Message 15
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SnowpointCityGym_0280
    GoTo SnowpointCityGym_027A
SnowpointCityGym_Entry5:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A6D
    GoToIf 0, SnowpointCityGym_02B2
    Message 17
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SnowpointCityGym_02C1
    GoTo SnowpointCityGym_027A
SnowpointCityGym_Entry6:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 18
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SnowpointCityGym_02F3
    GoTo SnowpointCityGym_027A
SnowpointCityGym_019E:
    SetFlag FLAG_HIDE_SNOWPOINT_CITY_CANDICE
    End
SnowpointCityGym_01A4:
    Message 12
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCityGym_01AF:
    Message 10
    WaitButton
    CloseMessage
    ReleaseAll
    StartTrainerBattle 853, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SnowpointCityGym_01F4
    Message 11
    WaitButton
    CloseMessage
    ReleaseAll
    SetFlag FLAG_UNK_0x0958
    End
SnowpointCityGym_01DE:
    CheckFlag FLAG_RECEIVED_CANDICE_TM72
    GoToIf 0, SnowpointCityGym_01FA
    Message 5
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCityGym_01F4:
    BlackOutFromBattle
    ReleaseAll
    End
SnowpointCityGym_01FA:
    SetVarFromValue VAR_0x8004, 399
    SetVarFromValue VAR_0x8005, 1
    SetVarFromValue VAR_OBJ_GFX_ID_6, 62
    CanFitItem 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SnowpointCityGym_0265
    CallCommonScript 2044
    SetFlag FLAG_RECEIVED_CANDICE_TM72
    BufferItemName 0, 32772
    BufferTMHMMoveName 1, 32772
    Message 4
    WaitButton
    CloseMessage
    Message 13
    CloseMessage
    ReleaseAll
    End
SnowpointCityGym_0243:
    BufferPlayerName 0
    Message 7
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCityGym_0251:
    BufferRivalName 0
    BufferPlayerName 1
    BufferRivalName 2
    Message 9
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCityGym_0265:
    CallCommonScript 2017
    CloseMessage
    ReleaseAll
    End
SnowpointCityGym_026F:
    Message 14
    WaitButton
    CloseMessage
    ReleaseAll
    End
SnowpointCityGym_027A:
    CloseMessage
    ReleaseAll
    End
SnowpointCityGym_0280:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 167, 11, 4, 0
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SnowpointCityGym_02B2:
    Message 16
    WaitButton
    CloseMessage
    SetFlag FLAG_UNK_0x0A6D
    ReleaseAll
    End
SnowpointCityGym_02C1:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 167, 11, 28, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SnowpointCityGym_02F3:
    CloseMessage
    PlayCry SPECIES_HAPPINY, 0
    WaitCry
    HealParty
    Message 19
    WaitButton
    CloseMessage
    ReleaseAll
    End
