@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry Route209_Entry0
    ScriptEntry Route209_Entry1
    ScriptEntry Route209_Entry2
    ScriptEntry Route209_Entry3
    ScriptEntry Route209_Entry4
    ScriptEntry Route209_Entry5
    ScriptEntry Route209_Entry6
    ScriptEntry Route209_Entry7
    ScriptEntry Route209_Entry8
    ScriptEntryEnd

Route209_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 0
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route209_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CompareVarToValue VAR_HALLOWED_TOWER_STATE, 1
    GoToIf 1, Route209_016F
    CheckItem ITEM_ODD_KEYSTONE, 1, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route209_0186
    Message 2
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route209_0191
    CloseMessage
    ReleaseAll
    End
Route209_Entry2:
    DrawSignpostInstantMessage 18, 1, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
Route209_Entry3:
    DrawSignpostInstantMessage 19, 1, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
Route209_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    SetVarFromValue VAR_0x8004, 446
    BufferItemNameWithArticle 0, 32772
    CapitalizeFirstLetter 0
    CheckFlag FLAG_RECEIVED_GOOD_ROD
    GoToIf 1, Route209_01AD
    Message 10
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route209_01D5
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Route209_01F1
    End
Route209_Entry5:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 16
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route209_Entry6:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 17
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route209_Entry7:
    GetTimeOfDay VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, Route209_01FC
    CompareVarToValue VARS_START, 1
    GoToIf 1, Route209_020E
    CompareVarToValue VARS_START, 2
    GoToIf 1, Route209_020E
    CompareVarToValue VARS_START, 3
    GoToIf 1, Route209_020E
    CompareVarToValue VARS_START, 4
    GoToIf 1, Route209_020E
    End
Route209_Entry8:
    DrawSignpostTextBox 3, 0
    SetSignpostCommand 3
    WaitForSignpostDone
    DrawSignpostScrollingMessage 20, VAR_0x800C
    CallCommonScript 2000
    End
Route209_016F:
    GetSpiritombCounter VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 4, Route209_0220
    GoTo Route209_0252
Route209_0186:
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route209_0191:
    BufferPlayerName 0
    Message 3
    WaitButton
    RemoveItem ITEM_ODD_KEYSTONE, 1, VAR_0x800C
    SetVarFromValue VAR_HALLOWED_TOWER_STATE, 1
    CloseMessage
    ReleaseAll
    End
Route209_01AD:
    BufferItemName 0, 32772
    Message 12
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route209_025D
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, Route209_0268
    End
Route209_01D5:
    BufferItemName 0, 32772
    Message 11
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetFlag FLAG_RECEIVED_GOOD_ROD
    GoTo Route209_01AD
Route209_01F1:
    Message 13
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route209_01FC:
    ClearFlag FLAG_HIDE_ROUTE_209_JOGGER_RICHARD
    ClearFlag FLAG_HIDE_ROUTE_209_JOGGER_RAUL
    SetFlag FLAG_HIDE_ROUTE_209_JOGGER_RICHARD_NO_BATTLE
    SetFlag FLAG_HIDE_ROUTE_209_JOGGER_RAUL_NO_BATTLE
    End
Route209_020E:
    ClearFlag FLAG_HIDE_ROUTE_209_JOGGER_RICHARD_NO_BATTLE
    ClearFlag FLAG_HIDE_ROUTE_209_JOGGER_RAUL_NO_BATTLE
    SetFlag FLAG_HIDE_ROUTE_209_JOGGER_RICHARD
    SetFlag FLAG_HIDE_ROUTE_209_JOGGER_RAUL
    End
Route209_0220:
    WaitSE SE_CONFIRM_sseq_3
    PlayCry SPECIES_SPIRITOMB, 0
    Message 9
    WaitCry
    CloseMessage
    StartWildBattle SPECIES_SPIRITOMB, 25
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route209_0273
    SetVarFromValue VAR_HALLOWED_TOWER_STATE, 0
    ClearSpiritombCounter
    End
Route209_0252:
    Message 4
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route209_025D:
    Message 14
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route209_0268:
    Message 15
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route209_0273:
    BlackOutFromBattle
    ReleaseAll
    End
    .byte 0

