@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry NewmoonIslandForest_Entry0
    ScriptEntry NewmoonIslandForest_Entry1
    ScriptEntry NewmoonIslandForest_Entry2
    ScriptEntryEnd

NewmoonIslandForest_Entry0:
    GetSetNationalDexEnabled 2, VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, NewmoonIslandForest_00B2
    CheckItem ITEM_MEMBER_CARD, 1, VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, NewmoonIslandForest_00B2
    CheckFlag FLAG_CAUGHT_DARKRAI
    GoToIf 1, NewmoonIslandForest_00B2
    ClearFlag FLAG_HIDE_NEWMOON_ISLAND_FOREST_DARKRAI
    End
NewmoonIslandForest_Entry1:
    CheckFlag FLAG_MAP_LOCAL_REMOVE_OBJECT
    GoToIf 1, NewmoonIslandForest_00B8
    End
NewmoonIslandForest_Entry2:
    LockAll
    PlaySE SE_CONFIRM_sseq_3
    WaitSE SE_CONFIRM_sseq_3
    Message 0
    CloseMessage
    SetFlag FLAG_MAP_LOCAL_REMOVE_OBJECT
    StartLegendaryBattle SPECIES_DARKRAI, 50
    ClearFlag FLAG_MAP_LOCAL_REMOVE_OBJECT
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, NewmoonIslandForest_00C6
    CheckDidNotCapture VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, NewmoonIslandForest_00CC
    SetFlag FLAG_CAUGHT_DARKRAI
    SetFlag FLAG_HIDE_CANALAVE_CITY_HARBOR_INN_GYM_GUIDE
    CompareVarToValue VAR_DARKRAI_EVENT_STATE, 2
    GoToIf 1, NewmoonIslandForest_00D7
    Message 3
    WaitButton
    CloseMessage
    ReleaseAll
    End
NewmoonIslandForest_00B2:
    SetFlag FLAG_HIDE_NEWMOON_ISLAND_FOREST_DARKRAI
    End
NewmoonIslandForest_00B8:
    SetFlag FLAG_HIDE_NEWMOON_ISLAND_FOREST_DARKRAI
    RemoveObject 0
    ClearFlag FLAG_MAP_LOCAL_REMOVE_OBJECT
    End
NewmoonIslandForest_00C6:
    BlackOutFromBattle
    ReleaseAll
    End
NewmoonIslandForest_00CC:
    Message 1
    CloseMessage
    GoTo NewmoonIslandForest_0140
NewmoonIslandForest_00D7:
    Message 2
    CloseMessage
    WaitTime 30, VAR_0x800C
    FadeScreen 6, 3, 0, 0
    WaitFadeScreen
    FadeScreen 6, 3, 1, 0
    WaitFadeScreen
    FadeScreen 6, 3, 0, 0
    WaitFadeScreen
    FadeScreen 6, 3, 1, 0
    WaitFadeScreen
    FadeScreen 6, 6, 0, 0
    WaitFadeScreen
    WaitTime 120, VAR_0x800C
    Warp 43, 8, 6, 1
    FadeScreen 6, 6, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
NewmoonIslandForest_0140:
    SetFlag FLAG_HIDE_CANALAVE_CITY_HARBOR_INN_GYM_GUIDE
    CompareVarToValue VAR_DARKRAI_EVENT_STATE, 2
    GoToIf 1, NewmoonIslandForest_00D7
    Message 3
    WaitButton
    CloseMessage
    ReleaseAll
    End
