@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry PokemonDayCare_Entry0
    ScriptEntry PokemonDayCare_Entry1
    ScriptEntry PokemonDayCare_Entry2
    ScriptEntry PokemonDayCare_Entry3
    ScriptEntry PokemonDayCare_Entry4
    ScriptEntryEnd

PokemonDayCare_Entry0:
    CheckFlag FLAG_STORED_POKEMON_AT_DAY_CARE
    CallIf 1, PokemonDayCare_016D
    End
PokemonDayCare_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckPoketchAppRegistered 8, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, PokemonDayCare_0173
    Message 0
    SetVarFromValue VAR_0x8004, 8
    CallCommonScript 2009
    WaitButton
    CloseMessage
    ReleaseAll
    End
PokemonDayCare_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 2
    WaitButton
    CloseMessage
    ReleaseAll
    End
PokemonDayCare_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 3
    InitLocalTextListMenu 1, 1, 0, VAR_0x800C, 1
    AddListMenuEntry 16, 0, 255
    AddListMenuEntry 4, 1, 255
    AddListMenuEntry 5, 2, 255
    AddListMenuEntry 6, 3, 255
    AddListMenuEntry 7, 4, 255
    AddListMenuEntry 8, 5, 255
    AddListMenuEntry 9, 6, 255
    AddListMenuEntry 10, 7, 255
    AddListMenuEntry 11, 8, 255
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, PokemonDayCare_017E
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, PokemonDayCare_0189
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, PokemonDayCare_01AA
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, PokemonDayCare_01CB
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, PokemonDayCare_01EC
    CompareVarToValue VAR_0x8008, 5
    GoToIf 1, PokemonDayCare_020D
    CompareVarToValue VAR_0x8008, 6
    GoToIf 1, PokemonDayCare_022E
    CompareVarToValue VAR_0x8008, 7
    GoToIf 1, PokemonDayCare_024F
    CompareVarToValue VAR_0x8008, 8
    GoToIf 1, PokemonDayCare_02B8
    GoTo PokemonDayCare_0321
PokemonDayCare_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    GoToIfSet FLAG_RECEIVED_POKEMON_DAY_CARE_GIFT, PokemonDayCare_0321
    Message 18
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_0404
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, PokemonDayCare_0321
    End
PokemonDayCare_016D:
    ClearFlag FLAG_HIDE_DAY_CARE_GYM_GUIDE
    Return
PokemonDayCare_0173:
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
PokemonDayCare_017E:
    CloseMessage
    Message 17
    WaitButton
    CloseMessage
    Return
PokemonDayCare_0189:
    CloseMessage
    StartTrainerBattle 217, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_032C
    HealParty
    GoTo PokemonDayCare_0332
PokemonDayCare_01AA:
    CloseMessage
    StartTrainerBattle 218, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_032C
    HealParty
    GoTo PokemonDayCare_0355
PokemonDayCare_01CB:
    CloseMessage
    StartTrainerBattle 219, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_032C
    HealParty
    GoTo PokemonDayCare_0378
PokemonDayCare_01EC:
    CloseMessage
    StartTrainerBattle 220, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_032C
    HealParty
    GoTo PokemonDayCare_039B
PokemonDayCare_020D:
    CloseMessage
    StartTrainerBattle 221, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_032C
    HealParty
    GoTo PokemonDayCare_03BE
PokemonDayCare_022E:
    CloseMessage
    StartTrainerBattle 222, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_032C
    HealParty
    GoTo PokemonDayCare_03E1
PokemonDayCare_024F:
    Message 14
    WaitButton
    CloseMessage
    SetVarFromValue VAR_0x8004, 289
    SetVarFromValue VAR_0x8005, 2
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 290
    SetVarFromValue VAR_0x8005, 2
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 291
    SetVarFromValue VAR_0x8005, 2
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 292
    SetVarFromValue VAR_0x8005, 2
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 293
    SetVarFromValue VAR_0x8005, 2
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 294
    SetVarFromValue VAR_0x8005, 2
    CallCommonScript 2044
    Return
PokemonDayCare_02B8:
    Message 15
    WaitButton
    CloseMessage
    SetVarFromValue VAR_0x8004, 169
    SetVarFromValue VAR_0x8005, 50
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 170
    SetVarFromValue VAR_0x8005, 50
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 171
    SetVarFromValue VAR_0x8005, 50
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 172
    SetVarFromValue VAR_0x8005, 50
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 173
    SetVarFromValue VAR_0x8005, 50
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 174
    SetVarFromValue VAR_0x8005, 50
    CallCommonScript 2044
    Return
PokemonDayCare_0321:
    Message 12
    WaitButton
    CloseMessage
    ReleaseAll
    End
PokemonDayCare_032C:
    BlackOutFromBattle
    ReleaseAll
    End
PokemonDayCare_0332:
    Message 13
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_0189
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, PokemonDayCare_0321
    End
PokemonDayCare_0355:
    Message 13
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_01AA
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, PokemonDayCare_0321
    End
PokemonDayCare_0378:
    Message 13
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_01CB
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, PokemonDayCare_0321
    End
PokemonDayCare_039B:
    Message 13
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_01EC
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, PokemonDayCare_0321
    End
PokemonDayCare_03BE:
    Message 13
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_020D
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, PokemonDayCare_0321
    End
PokemonDayCare_03E1:
    Message 13
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, PokemonDayCare_022E
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, PokemonDayCare_0321
    End
PokemonDayCare_0404:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, PokemonDayCare_0430
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GiveDesignedPokemon SPECIES_FLOETTE, 30, ITEM_NONE, 0, 31, 1, VAR_0x800C
    SetFlag FLAG_RECEIVED_POKEMON_DAY_CARE_GIFT
    Message 12
    CloseMessage
    ReleaseAll
    End
PokemonDayCare_0430:
    Message 19
    WaitButton
    CloseMessage
    ReleaseAll
    End
    .balign 4, 0

