@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry IcebergRuins_Entry0
    ScriptEntry IcebergRuins_Entry1
    ScriptEntry IcebergRuins_Entry2
    ScriptEntry IcebergRuins_Entry3
    ScriptEntry IcebergRuins_Entry4
    ScriptEntry IcebergRuins_Entry5
    ScriptEntry IcebergRuins_Entry6
    ScriptEntry IcebergRuins_Entry7
    ScriptEntry IcebergRuins_Entry8
    ScriptEntryEnd

IcebergRuins_Entry0:
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 280
    GoToIf 0, IcebergRuins_0137
    End
IcebergRuins_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 290
    GoToIf 1, IcebergRuins_013F
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 280
    GoToIf 1, IcebergRuins_0148
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 270
    GoToIf 1, IcebergRuins_0157
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 260
    GoToIf 0, IcebergRuins_0196
    WaitSE SE_CONFIRM_sseq_3
    ScrCmd_29F 1
    SetVarFromValue VAR_ICEBERG_RUINS_STATE, 270
    Message 1
    GoTo IcebergRuins_019F
IcebergRuins_Entry2:
    SetVarFromValue VAR_MAP_LOCAL_0x01, 1
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 260
    GoToIf 4, IcebergRuins_01A7
    GoTo IcebergRuins_01A9
IcebergRuins_Entry3:
    SetVarFromValue VAR_MAP_LOCAL_0x02, 1
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 260
    GoToIf 4, IcebergRuins_01A7
    GoTo IcebergRuins_01A9
IcebergRuins_Entry4:
    SetVarFromValue VAR_MAP_LOCAL_0x03, 1
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 260
    GoToIf 4, IcebergRuins_01A7
    GoTo IcebergRuins_01A9
IcebergRuins_Entry5:
    SetVarFromValue VAR_MAP_LOCAL_0x04, 1
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 260
    GoToIf 4, IcebergRuins_01A7
    GoTo IcebergRuins_01A9
IcebergRuins_Entry6:
    SetVarFromValue VAR_MAP_LOCAL_0x05, 1
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 260
    GoToIf 4, IcebergRuins_01A7
    GoTo IcebergRuins_01A9
IcebergRuins_Entry7:
    SetVarFromValue VAR_MAP_LOCAL_0x06, 1
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 260
    GoToIf 4, IcebergRuins_01A7
    GoTo IcebergRuins_01A9
IcebergRuins_Entry8:
    SetVarFromValue VAR_MAP_LOCAL_0x07, 1
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 260
    GoToIf 4, IcebergRuins_01A7
    GoTo IcebergRuins_01A9
IcebergRuins_0137:
    SetVarFromValue VAR_ICEBERG_RUINS_STATE, 0
    End
IcebergRuins_013F:
    Message 3
    GoTo IcebergRuins_019F
IcebergRuins_0148:
    SetVarFromValue VAR_ICEBERG_RUINS_STATE, 280
    Message 3
    GoTo IcebergRuins_019F
IcebergRuins_0157:
    PlayCry SPECIES_REGICE, 0
    Message 2
    WaitCry
    CloseMessage
    StartLegendaryBattle SPECIES_REGICE, 30
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, IcebergRuins_01CC
    CheckDidNotCapture VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, IcebergRuins_0148
    SetVarFromValue VAR_ICEBERG_RUINS_STATE, 290
    ReleaseAll
    End
IcebergRuins_0196:
    Message 0
    GoTo IcebergRuins_019F
IcebergRuins_019F:
    WaitButton
    CloseMessage
    ReleaseAll
    End
IcebergRuins_01A7:
    End
IcebergRuins_01A9:
    LockAll
    GetPlayerMapPos 32772, 32773
    ActivateRegiRuinsDot VAR_ICEBERG_RUINS_STATE, 590, 32772, 32773
    CompareVarToValue VAR_ICEBERG_RUINS_STATE, 260
    GoToIf 4, IcebergRuins_01D2
    ReleaseAll
    End
IcebergRuins_01CC:
    BlackOutFromBattle
    ReleaseAll
    End
IcebergRuins_01D2:
    WaitSE SE_CONFIRM_sseq_3
    ScrCmd_29F 1
    SetVarFromValue VAR_ICEBERG_RUINS_STATE, 270
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
    .balign 4, 0

