@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry SpearPillarPalkia_Entry0
    ScriptEntry SpearPillarPalkia_Entry1
    ScriptEntryEnd

SpearPillarPalkia_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CompareVarToValue VAR_SPEAR_PILLAR_PALKIA_STATE, 1
    GoToIf 4, SpearPillarPalkia_0083
    CheckFlag FLAG_CAUGHT_PALKIA
    GoToIf 1, SpearPillarPalkia_0083
    Message 0
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SpearPillarPalkia_008E
    PlayCry SPECIES_PALKIA, 0
    Message 1
    WaitCry
    CloseMessage
    StartLegendaryBattle SPECIES_PALKIA, 70
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, SpearPillarPalkia_0094
    SetVarFromValue VAR_SPEAR_PILLAR_PALKIA_STATE, 1
    CheckDidNotCapture VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    CallIf 1, SpearPillarPalkia_009A
    ReleaseAll
    End
SpearPillarPalkia_Entry1:
    Call SpearPillarPalkia_00A0
    End
SpearPillarPalkia_0083:
    Message 2
    WaitButton
    GoTo SpearPillarPalkia_008E
SpearPillarPalkia_008E:
    CloseMessage
    ReleaseAll
    End
SpearPillarPalkia_0094:
    BlackOutFromBattle
    ReleaseAll
    End
SpearPillarPalkia_009A:
    SetFlag FLAG_CAUGHT_PALKIA
    Return
SpearPillarPalkia_00A0:
    CheckGameCompleted VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, SpearPillarPalkia_00EF
    GetSetNationalDexEnabled 2, VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, SpearPillarPalkia_00EF
    CheckItem ITEM_AZURE_FLUTE, 1, VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, SpearPillarPalkia_00EF
    CheckFlag FLAG_CAUGHT_ARCEUS
    GoToIf 1, SpearPillarPalkia_00EF
    SetVarFromValue VAR_HALL_OF_ORIGIN_STATE, 1
    GoTo SpearPillarPalkia_00EF
SpearPillarPalkia_00EF:
    Return
    .byte 0

