@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry Route221_Entry0
    ScriptEntry Route221_Entry1
    ScriptEntry Route221_Entry2
    ScriptEntry Route221_Entry3
    ScriptEntry Route221_Entry4
    ScriptEntryEnd

Route221_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 0
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route221_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route221_Entry2:
    DrawSignpostInstantMessage 2, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
Route221_Entry3:
    GetSetNationalDexEnabled 2, VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, Route221_009C
    SetFlag FLAG_HIDE_ROUTE_221_WORKER_WEST
    SetFlag FLAG_HIDE_ROUTE_221_WORKER_EAST
    End
Route221_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A7C
    GoToIf 0, Route221_009E
    Message 4
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route221_00AB
    GoTo Route221_00DD
Route221_009C:
    End
Route221_009E:
    Message 3
    SetFlag FLAG_UNK_0x0A7C
    CloseMessage
    ReleaseAll
    End
Route221_00AB:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 418, 177, 843, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Route221_00DD:
    CloseMessage
    ReleaseAll
    End
    .balign 4, 0

