@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry OreburghCityMiddleHouse_Entry0
    ScriptEntry OreburghCityMiddleHouse_Entry1
    ScriptEntry OreburghCityMiddleHouse_Entry2
    ScriptEntryEnd

OreburghCityMiddleHouse_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 0
    WaitButton
    CloseMessage
    ReleaseAll
    End
OreburghCityMiddleHouse_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
OreburghCityMiddleHouse_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 2
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, OreburghCityMiddleHouse_0063
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, OreburghCityMiddleHouse_0092
    GoTo OreburghCityMiddleHouse_0092
OreburghCityMiddleHouse_0063:
    GetRandom VAR_0x800C, 3
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, OreburghCityMiddleHouse_009D
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, OreburghCityMiddleHouse_00C9
    CompareVarToValue VAR_0x800C, 2
    GoToIf 1, OreburghCityMiddleHouse_00F5
    End
OreburghCityMiddleHouse_0092:
    Message 6
    WaitButton
    CloseMessage
    ReleaseAll
    End
OreburghCityMiddleHouse_009D:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, OreburghCityMiddleHouse_0121
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_ODDISH, 15, 0, VAR_0x800C
    Message 6
    CloseMessage
    ReleaseAll
    End
OreburghCityMiddleHouse_00C9:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, OreburghCityMiddleHouse_0121
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_BELLSPROUT, 15, 0, VAR_0x800C
    Message 6
    CloseMessage
    ReleaseAll
    End
OreburghCityMiddleHouse_00F5:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, OreburghCityMiddleHouse_0121
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_CACNEA, 15, 0, VAR_0x800C
    Message 6
    CloseMessage
    ReleaseAll
    End
OreburghCityMiddleHouse_0121:
    Message 7
    WaitButton
    CloseMessage
    ReleaseAll
    End
