@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry VisibleItems_Entry0
    ScriptEntry VisibleItems_Entry1
    ScriptEntry VisibleItems_Entry2
    ScriptEntry VisibleItems_Entry3
    ScriptEntry VisibleItems_Entry4
    ScriptEntry VisibleItems_Entry5
    ScriptEntry VisibleItems_Entry6
    ScriptEntry VisibleItems_Entry7
    ScriptEntry VisibleItems_Entry8
    ScriptEntry VisibleItems_Entry9
    ScriptEntry VisibleItems_Entry10
    ScriptEntry VisibleItems_Entry11
    ScriptEntry VisibleItems_Entry12
    ScriptEntry VisibleItems_Entry13
    ScriptEntry VisibleItems_Entry14
    ScriptEntry VisibleItems_Entry15
    ScriptEntry VisibleItems_Entry16
    ScriptEntry VisibleItems_Entry17
    ScriptEntry VisibleItems_Entry18
    ScriptEntry VisibleItems_Entry19
    ScriptEntry VisibleItems_Entry20
    ScriptEntry VisibleItems_Entry21
    ScriptEntry VisibleItems_Entry22
    ScriptEntry VisibleItems_Entry23
    ScriptEntry VisibleItems_Entry24
    ScriptEntry VisibleItems_Entry25
    ScriptEntry VisibleItems_Entry26
    ScriptEntry VisibleItems_Entry27
    ScriptEntry VisibleItems_Entry28
    ScriptEntry VisibleItems_Entry29
    ScriptEntry VisibleItems_Entry30
    ScriptEntry VisibleItems_Entry31
    ScriptEntry VisibleItems_Entry32
    ScriptEntry VisibleItems_Entry33
    ScriptEntry VisibleItems_Entry34
    ScriptEntry VisibleItems_Entry35
    ScriptEntry VisibleItems_Entry36
    ScriptEntry VisibleItems_Entry37
    ScriptEntry VisibleItems_Entry38
    ScriptEntry VisibleItems_Entry39
    ScriptEntry VisibleItems_Entry40
    ScriptEntry VisibleItems_Entry41
    ScriptEntry VisibleItems_Entry42
    ScriptEntry VisibleItems_Entry43
    ScriptEntry VisibleItems_Entry44
    ScriptEntry VisibleItems_Entry45
    ScriptEntry VisibleItems_Entry46
    ScriptEntry VisibleItems_Entry47
    ScriptEntry VisibleItems_Entry48
    ScriptEntry VisibleItems_Entry49
    ScriptEntry VisibleItems_Entry50
    ScriptEntry VisibleItems_Entry51
    ScriptEntry VisibleItems_Entry52
    ScriptEntry VisibleItems_Entry53
    ScriptEntry VisibleItems_Entry54
    ScriptEntry VisibleItems_Entry55
    ScriptEntry VisibleItems_Entry56
    ScriptEntry VisibleItems_Entry57
    ScriptEntry VisibleItems_Entry58
    ScriptEntry VisibleItems_Entry59
    ScriptEntry VisibleItems_Entry60
    ScriptEntry VisibleItems_Entry61
    ScriptEntry VisibleItems_Entry62
    ScriptEntry VisibleItems_Entry63
    ScriptEntry VisibleItems_Entry64
    ScriptEntry VisibleItems_Entry65
    ScriptEntry VisibleItems_Entry66
    ScriptEntry VisibleItems_Entry67
    ScriptEntry VisibleItems_Entry68
    ScriptEntry VisibleItems_Entry69
    ScriptEntry VisibleItems_Entry70
    ScriptEntry VisibleItems_Entry71
    ScriptEntry VisibleItems_Entry72
    ScriptEntry VisibleItems_Entry73
    ScriptEntry VisibleItems_Entry74
    ScriptEntry VisibleItems_Entry75
    ScriptEntry VisibleItems_Entry76
    ScriptEntry VisibleItems_Entry77
    ScriptEntry VisibleItems_Entry78
    ScriptEntry VisibleItems_Entry79
    ScriptEntry VisibleItems_Entry80
    ScriptEntry VisibleItems_Entry81
    ScriptEntry VisibleItems_Entry82
    ScriptEntry VisibleItems_Entry83
    ScriptEntry VisibleItems_Entry84
    ScriptEntry VisibleItems_Entry85
    ScriptEntry VisibleItems_Entry86
    ScriptEntry VisibleItems_Entry87
    ScriptEntry VisibleItems_Entry88
    ScriptEntry VisibleItems_Entry89
    ScriptEntry VisibleItems_Entry90
    ScriptEntry VisibleItems_Entry91
    ScriptEntry VisibleItems_Entry92
    ScriptEntry VisibleItems_Entry93
    ScriptEntry VisibleItems_Entry94
    ScriptEntry VisibleItems_Entry95
    ScriptEntry VisibleItems_Entry96
    ScriptEntry VisibleItems_Entry97
    ScriptEntry VisibleItems_Entry98
    ScriptEntry VisibleItems_Entry99
    ScriptEntry VisibleItems_Entry100
    ScriptEntry VisibleItems_Entry101
    ScriptEntry VisibleItems_Entry102
    ScriptEntry VisibleItems_Entry103
    ScriptEntry VisibleItems_Entry104
    ScriptEntry VisibleItems_Entry105
    ScriptEntry VisibleItems_Entry106
    ScriptEntry VisibleItems_Entry107
    ScriptEntry VisibleItems_Entry108
    ScriptEntry VisibleItems_Entry109
    ScriptEntry VisibleItems_Entry110
    ScriptEntry VisibleItems_Entry111
    ScriptEntry VisibleItems_Entry112
    ScriptEntry VisibleItems_Entry113
    ScriptEntry VisibleItems_Entry114
    ScriptEntry VisibleItems_Entry115
    ScriptEntry VisibleItems_Entry116
    ScriptEntry VisibleItems_Entry117
    ScriptEntry VisibleItems_Entry118
    ScriptEntry VisibleItems_Entry119
    ScriptEntry VisibleItems_Entry120
    ScriptEntry VisibleItems_Entry121
    ScriptEntry VisibleItems_Entry122
    ScriptEntry VisibleItems_Entry123
    ScriptEntry VisibleItems_Entry124
    ScriptEntry VisibleItems_Entry125
    ScriptEntry VisibleItems_Entry126
    ScriptEntry VisibleItems_Entry127
    ScriptEntry VisibleItems_Entry128
    ScriptEntry VisibleItems_Entry129
    ScriptEntry VisibleItems_Entry130
    ScriptEntry VisibleItems_Entry131
    ScriptEntry VisibleItems_Entry132
    ScriptEntry VisibleItems_Entry133
    ScriptEntry VisibleItems_Entry134
    ScriptEntry VisibleItems_Entry135
    ScriptEntry VisibleItems_Entry136
    ScriptEntry VisibleItems_Entry137
    ScriptEntry VisibleItems_Entry138
    ScriptEntry VisibleItems_Entry139
    ScriptEntry VisibleItems_Entry140
    ScriptEntry VisibleItems_Entry141
    ScriptEntry VisibleItems_Entry142
    ScriptEntry VisibleItems_Entry143
    ScriptEntry VisibleItems_Entry144
    ScriptEntry VisibleItems_Entry145
    ScriptEntry VisibleItems_Entry146
    ScriptEntry VisibleItems_Entry147
    ScriptEntry VisibleItems_Entry148
    ScriptEntry VisibleItems_Entry149
    ScriptEntry VisibleItems_Entry150
    ScriptEntry VisibleItems_Entry151
    ScriptEntry VisibleItems_Entry152
    ScriptEntry VisibleItems_Entry153
    ScriptEntry VisibleItems_Entry154
    ScriptEntry VisibleItems_Entry155
    ScriptEntry VisibleItems_Entry156
    ScriptEntry VisibleItems_Entry157
    ScriptEntry VisibleItems_Entry158
    ScriptEntry VisibleItems_Entry159
    ScriptEntry VisibleItems_Entry160
    ScriptEntry VisibleItems_Entry161
    ScriptEntry VisibleItems_Entry162
    ScriptEntry VisibleItems_Entry163
    ScriptEntry VisibleItems_Entry164
    ScriptEntry VisibleItems_Entry165
    ScriptEntry VisibleItems_Entry166
    ScriptEntry VisibleItems_Entry167
    ScriptEntry VisibleItems_Entry168
    ScriptEntry VisibleItems_Entry169
    ScriptEntry VisibleItems_Entry170
    ScriptEntry VisibleItems_Entry171
    ScriptEntry VisibleItems_Entry172
    ScriptEntry VisibleItems_Entry173
    ScriptEntry VisibleItems_Entry174
    ScriptEntry VisibleItems_Entry175
    ScriptEntry VisibleItems_Entry176
    ScriptEntry VisibleItems_Entry177
    ScriptEntry VisibleItems_Entry178
    ScriptEntry VisibleItems_Entry179
    ScriptEntry VisibleItems_Entry180
    ScriptEntry VisibleItems_Entry181
    ScriptEntry VisibleItems_Entry182
    ScriptEntry VisibleItems_Entry183
    ScriptEntry VisibleItems_Entry184
    ScriptEntry VisibleItems_Entry185
    ScriptEntry VisibleItems_Entry186
    ScriptEntry VisibleItems_Entry187
    ScriptEntry VisibleItems_Entry188
    ScriptEntry VisibleItems_Entry189
    ScriptEntry VisibleItems_Entry190
    ScriptEntry VisibleItems_Entry191
    ScriptEntry VisibleItems_Entry192
    ScriptEntry VisibleItems_Entry193
    ScriptEntry VisibleItems_Entry194
    ScriptEntry VisibleItems_Entry195
    ScriptEntry VisibleItems_Entry196
    ScriptEntry VisibleItems_Entry197
    ScriptEntry VisibleItems_Entry198
    ScriptEntry VisibleItems_Entry199
    ScriptEntry VisibleItems_Entry200
    ScriptEntry VisibleItems_Entry201
    ScriptEntry VisibleItems_Entry202
    ScriptEntry VisibleItems_Entry203
    ScriptEntry VisibleItems_Entry204
    ScriptEntry VisibleItems_Entry205
    ScriptEntry VisibleItems_Entry206
    ScriptEntry VisibleItems_Entry207
    ScriptEntry VisibleItems_Entry208
    ScriptEntry VisibleItems_Entry209
    ScriptEntry VisibleItems_Entry210
    ScriptEntry VisibleItems_Entry211
    ScriptEntry VisibleItems_Entry212
    ScriptEntry VisibleItems_Entry213
    ScriptEntry VisibleItems_Entry214
    ScriptEntry VisibleItems_Entry215
    ScriptEntry VisibleItems_Entry216
    ScriptEntry VisibleItems_Entry217
    ScriptEntry VisibleItems_Entry218
    ScriptEntry VisibleItems_Entry219
    ScriptEntry VisibleItems_Entry220
    ScriptEntry VisibleItems_Entry221
    ScriptEntry VisibleItems_Entry222
    ScriptEntry VisibleItems_Entry223
    ScriptEntry VisibleItems_Entry224
    ScriptEntry VisibleItems_Entry225
    ScriptEntry VisibleItems_Entry226
    ScriptEntry VisibleItems_Entry227
    ScriptEntry VisibleItems_Entry228
    ScriptEntry VisibleItems_Entry229
    ScriptEntry VisibleItems_Entry230
    ScriptEntry VisibleItems_Entry231
    ScriptEntry VisibleItems_Entry232
    ScriptEntry VisibleItems_Entry233
    ScriptEntry VisibleItems_Entry234
    ScriptEntry VisibleItems_Entry235
    ScriptEntry VisibleItems_Entry236
    ScriptEntry VisibleItems_Entry237
    ScriptEntry VisibleItems_Entry238
    ScriptEntry VisibleItems_Entry239
    ScriptEntry VisibleItems_Entry240
    ScriptEntry VisibleItems_Entry241
    ScriptEntry VisibleItems_Entry242
    ScriptEntry VisibleItems_Entry243
    ScriptEntry VisibleItems_Entry244
    ScriptEntry VisibleItems_Entry245
    ScriptEntry VisibleItems_Entry246
    ScriptEntry VisibleItems_Entry247
    ScriptEntry VisibleItems_Entry248
    ScriptEntry VisibleItems_Entry249
    ScriptEntry VisibleItems_Entry250
    ScriptEntry VisibleItems_Entry251
    ScriptEntry VisibleItems_Entry252
    ScriptEntry VisibleItems_Entry253
    ScriptEntry VisibleItems_Entry254
    ScriptEntry VisibleItems_Entry255
    ScriptEntry VisibleItems_Entry256
    ScriptEntry VisibleItems_Entry257
    ScriptEntry VisibleItems_Entry258
    ScriptEntry VisibleItems_Entry259
    ScriptEntry VisibleItems_Entry260
    ScriptEntry VisibleItems_Entry261
    ScriptEntry VisibleItems_Entry262
    ScriptEntry VisibleItems_Entry263
    ScriptEntry VisibleItems_Entry264
    ScriptEntry VisibleItems_Entry265
    ScriptEntry VisibleItems_Entry266
    ScriptEntry VisibleItems_Entry267
    ScriptEntry VisibleItems_Entry268
    ScriptEntry VisibleItems_Entry269
    ScriptEntry VisibleItems_Entry270
    ScriptEntry VisibleItems_Entry271
    ScriptEntry VisibleItems_Entry272
    ScriptEntry VisibleItems_Entry273
    ScriptEntry VisibleItems_Entry274
    ScriptEntry VisibleItems_Entry275
    ScriptEntry VisibleItems_Entry276
    ScriptEntry VisibleItems_Entry277
    ScriptEntry VisibleItems_Entry278
    ScriptEntry VisibleItems_Entry279
    ScriptEntry VisibleItems_Entry280
    ScriptEntry VisibleItems_Entry281
    ScriptEntry VisibleItems_Entry282
    ScriptEntry VisibleItems_Entry283
    ScriptEntry VisibleItems_Entry284
    ScriptEntry VisibleItems_Entry285
    ScriptEntry VisibleItems_Entry286
    ScriptEntry VisibleItems_Entry287
    ScriptEntry VisibleItems_Entry288
    ScriptEntry VisibleItems_Entry289
    ScriptEntry VisibleItems_Entry290
    ScriptEntry VisibleItems_Entry291
    ScriptEntry VisibleItems_Entry292
    ScriptEntry VisibleItems_Entry293
    ScriptEntry VisibleItems_Entry294
    ScriptEntry VisibleItems_Entry295
    ScriptEntry VisibleItems_Entry296
    ScriptEntry VisibleItems_Entry297
    ScriptEntry VisibleItems_Entry298
    ScriptEntry VisibleItems_Entry299
    ScriptEntry VisibleItems_Entry300
    ScriptEntry VisibleItems_Entry301
    ScriptEntry VisibleItems_Entry302
    ScriptEntry VisibleItems_Entry303
    ScriptEntry VisibleItems_Entry304
    ScriptEntry VisibleItems_Entry305
    ScriptEntry VisibleItems_Entry306
    ScriptEntry VisibleItems_Entry307
    ScriptEntry VisibleItems_Entry308
    ScriptEntry VisibleItems_Entry309
    ScriptEntry VisibleItems_Entry310
    ScriptEntry VisibleItems_Entry311
    ScriptEntry VisibleItems_Entry312
    ScriptEntry VisibleItems_Entry313
    ScriptEntry VisibleItems_Entry314
    ScriptEntry VisibleItems_Entry315
    ScriptEntry VisibleItems_Entry316
    ScriptEntry VisibleItems_Entry317
    ScriptEntry VisibleItems_Entry318
    ScriptEntry VisibleItems_Entry319
    ScriptEntry VisibleItems_Entry320
    ScriptEntry VisibleItems_Entry321
    ScriptEntry VisibleItems_Entry322
    ScriptEntry VisibleItems_Entry323
    ScriptEntry VisibleItems_Entry324
    ScriptEntry VisibleItems_Entry325
    ScriptEntry VisibleItems_Entry326
    ScriptEntry VisibleItems_Entry327
    ScriptEntry VisibleItems_Entry328
    ScriptEntry VisibleItems_Entry329
    ScriptEntry VisibleItems_Entry330
    ScriptEntry VisibleItems_Entry331
    ScriptEntry VisibleItems_Entry332
    ScriptEntry VisibleItems_Entry333
    ScriptEntry VisibleItems_Entry334
    ScriptEntry VisibleItems_Entry335
    ScriptEntry VisibleItems_Entry336
    ScriptEntry VisibleItems_Entry337
    ScriptEntry VisibleItems_Entry338
    ScriptEntry VisibleItems_Entry339
    ScriptEntry VisibleItems_Entry340
    ScriptEntry VisibleItems_Entry341
    ScriptEntry VisibleItems_Entry342
    ScriptEntry VisibleItems_Entry343
    ScriptEntry VisibleItems_Entry344
    ScriptEntry VisibleItems_Entry345
    ScriptEntry VisibleItems_Entry346
    ScriptEntry VisibleItems_Entry347
    ScriptEntry VisibleItems_Entry348
    ScriptEntry VisibleItems_Entry349
    ScriptEntry VisibleItems_Entry350
    ScriptEntry VisibleItems_Entry351
    ScriptEntry VisibleItems_Entry352
    ScriptEntry VisibleItems_Entry353
    ScriptEntry VisibleItems_Entry354
    ScriptEntry VisibleItems_Entry355
    ScriptEntry VisibleItems_Entry356
    ScriptEntry VisibleItems_Entry357
    ScriptEntry VisibleItems_Entry358
    ScriptEntry VisibleItems_Entry359
    ScriptEntry VisibleItems_Entry360
    ScriptEntry VisibleItems_Entry361
    ScriptEntry VisibleItems_Entry362
    ScriptEntry VisibleItems_Entry363
    ScriptEntry VisibleItems_Entry364
    ScriptEntry VisibleItems_Entry365
    ScriptEntry VisibleItems_Entry366
    ScriptEntry VisibleItems_Entry367
    ScriptEntry VisibleItems_Entry368
    ScriptEntry VisibleItems_Entry369
    ScriptEntry VisibleItems_Entry370
    ScriptEntry VisibleItems_Entry371
    ScriptEntry VisibleItems_Entry372
    ScriptEntry VisibleItems_Entry373
    ScriptEntry VisibleItems_Entry374
    ScriptEntry VisibleItems_Entry375
    ScriptEntry VisibleItems_Entry376
    ScriptEntry VisibleItems_Entry377
    ScriptEntry VisibleItems_Entry378
    ScriptEntry VisibleItems_Entry379
    ScriptEntry VisibleItems_Entry380
    ScriptEntry VisibleItems_Entry381
    ScriptEntry VisibleItems_Entry382
    ScriptEntry VisibleItems_Entry383
    ScriptEntry VisibleItems_Entry384
    ScriptEntry VisibleItems_Entry385
    ScriptEntry VisibleItems_Entry386
    ScriptEntry VisibleItems_Entry387
    ScriptEntry VisibleItems_Entry388
    ScriptEntry VisibleItems_Entry389
    ScriptEntry VisibleItems_Entry390
    ScriptEntry VisibleItems_Entry391
    ScriptEntry VisibleItems_Entry392
    ScriptEntry VisibleItems_Entry393
    ScriptEntry VisibleItems_Entry394
    ScriptEntry VisibleItems_Entry395
    ScriptEntry VisibleItems_Entry396
    ScriptEntry VisibleItems_Entry397
    ScriptEntry VisibleItems_Entry398
    ScriptEntry VisibleItems_Entry399
    ScriptEntry VisibleItems_Entry400
    ScriptEntry VisibleItems_Entry401
    ScriptEntry VisibleItems_Entry402
    ScriptEntry VisibleItems_Entry403
    ScriptEntry VisibleItems_Entry404
    ScriptEntry VisibleItems_Entry405
    ScriptEntry VisibleItems_Entry406
    ScriptEntry VisibleItems_Entry407
    ScriptEntry VisibleItems_Entry408
    ScriptEntry VisibleItems_Entry409
    ScriptEntry VisibleItems_Entry410
    ScriptEntry VisibleItems_Entry411
    ScriptEntry VisibleItems_Entry412
    ScriptEntry VisibleItems_Entry413
    ScriptEntry VisibleItems_Entry414
    ScriptEntry VisibleItems_Entry415
    ScriptEntry VisibleItems_Entry416
    ScriptEntry VisibleItems_Entry417
    ScriptEntry VisibleItems_Entry418
    ScriptEntry VisibleItems_Entry419
    ScriptEntry VisibleItems_Entry420
    ScriptEntry VisibleItems_Entry421
    ScriptEntry VisibleItems_Entry422
    ScriptEntry VisibleItems_Entry423
    ScriptEntry VisibleItems_Entry424
    ScriptEntry VisibleItems_Entry425
    ScriptEntry VisibleItems_Entry426
    ScriptEntry VisibleItems_Entry427
    ScriptEntry VisibleItems_Entry428
    ScriptEntry VisibleItems_Entry429
    ScriptEntry VisibleItems_Entry430
    ScriptEntry VisibleItems_Entry431
    ScriptEntry VisibleItems_Entry432
    ScriptEntry VisibleItems_Entry433
    ScriptEntry VisibleItems_Entry434
    ScriptEntry VisibleItems_Entry435
    ScriptEntry VisibleItems_Entry436
    ScriptEntry VisibleItems_Entry437
    ScriptEntry VisibleItems_Entry438
    ScriptEntry VisibleItems_Entry439
    ScriptEntry VisibleItems_Entry440
    ScriptEntry VisibleItems_Entry441
    ScriptEntry VisibleItems_Entry442
    ScriptEntry VisibleItems_Entry443
    ScriptEntry VisibleItems_Entry444
    ScriptEntry VisibleItems_Entry445
    ScriptEntry VisibleItems_Entry446
    ScriptEntry VisibleItems_Entry447
    ScriptEntry VisibleItems_Entry448
    ScriptEntry VisibleItems_Entry449
    ScriptEntry VisibleItems_Entry450
    ScriptEntry VisibleItems_Entry451
    ScriptEntry VisibleItems_Entry452
    ScriptEntry VisibleItems_Entry453
    ScriptEntry VisibleItems_Entry454
    ScriptEntry VisibleItems_Entry455
    ScriptEntry VisibleItems_Entry456
    ScriptEntry VisibleItems_Entry457
    ScriptEntry VisibleItems_Entry458
    ScriptEntry VisibleItems_Entry459
    ScriptEntry VisibleItems_Entry460
    ScriptEntry VisibleItems_Entry461
    ScriptEntry VisibleItems_Entry462
    ScriptEntry VisibleItems_Entry463
    ScriptEntry VisibleItems_Entry464
    ScriptEntry VisibleItems_Entry465
    ScriptEntry VisibleItems_Entry466
    ScriptEntry VisibleItems_Entry467
    ScriptEntry VisibleItems_Entry468
    ScriptEntryEnd

VisibleItems_Entry0:
    SetVarFromValue VAR_0x8008, 0
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry1:
    SetVarFromValue VAR_0x8008, 1
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry2:
    SetVarFromValue VAR_0x8008, 2
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry3:
    SetVarFromValue VAR_0x8008, 3
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry4:
    SetVarFromValue VAR_0x8008, 4
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry5:
    SetVarFromValue VAR_0x8008, 5
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry6:
    SetVarFromValue VAR_0x8008, 6
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry7:
    SetVarFromValue VAR_0x8008, 7
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry8:
    SetVarFromValue VAR_0x8008, 8
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry9:
    SetVarFromValue VAR_0x8008, 9
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry10:
    SetVarFromValue VAR_0x8008, 10
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry11:
    SetVarFromValue VAR_0x8008, 11
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry12:
    SetVarFromValue VAR_0x8008, 12
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry13:
    SetVarFromValue VAR_0x8008, 13
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry14:
    SetVarFromValue VAR_0x8008, 14
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry15:
    SetVarFromValue VAR_0x8008, 15
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry16:
    SetVarFromValue VAR_0x8008, 16
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry17:
    SetVarFromValue VAR_0x8008, 17
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry18:
    SetVarFromValue VAR_0x8008, 18
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry19:
    SetVarFromValue VAR_0x8008, 19
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry20:
    SetVarFromValue VAR_0x8008, 20
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry21:
    SetVarFromValue VAR_0x8008, 21
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry22:
    SetVarFromValue VAR_0x8008, 22
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry23:
    SetVarFromValue VAR_0x8008, 23
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry24:
    SetVarFromValue VAR_0x8008, 24
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry25:
    SetVarFromValue VAR_0x8008, 25
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry26:
    SetVarFromValue VAR_0x8008, 26
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry27:
    SetVarFromValue VAR_0x8008, 27
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry28:
    SetVarFromValue VAR_0x8008, 28
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry29:
    SetVarFromValue VAR_0x8008, 29
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry30:
    SetVarFromValue VAR_0x8008, 30
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry31:
    SetVarFromValue VAR_0x8008, 31
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry32:
    SetVarFromValue VAR_0x8008, 32
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry33:
    SetVarFromValue VAR_0x8008, 33
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry34:
    SetVarFromValue VAR_0x8008, 34
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry35:
    SetVarFromValue VAR_0x8008, 35
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry36:
    SetVarFromValue VAR_0x8008, 36
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry37:
    SetVarFromValue VAR_0x8008, 37
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry38:
    SetVarFromValue VAR_0x8008, 38
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry39:
    SetVarFromValue VAR_0x8008, 39
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry40:
    SetVarFromValue VAR_0x8008, 40
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry41:
    SetVarFromValue VAR_0x8008, 41
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry42:
    SetVarFromValue VAR_0x8008, 42
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry43:
    SetVarFromValue VAR_0x8008, 43
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry44:
    SetVarFromValue VAR_0x8008, 44
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry45:
    SetVarFromValue VAR_0x8008, 45
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry46:
    SetVarFromValue VAR_0x8008, 46
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry47:
    SetVarFromValue VAR_0x8008, 47
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry48:
    SetVarFromValue VAR_0x8008, 48
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry49:
    SetVarFromValue VAR_0x8008, 49
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry50:
    SetVarFromValue VAR_0x8008, 50
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry51:
    SetVarFromValue VAR_0x8008, 51
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry52:
    SetVarFromValue VAR_0x8008, 52
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry53:
    SetVarFromValue VAR_0x8008, 53
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry54:
    SetVarFromValue VAR_0x8008, 54
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry55:
    SetVarFromValue VAR_0x8008, 55
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry56:
    SetVarFromValue VAR_0x8008, 56
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry57:
    SetVarFromValue VAR_0x8008, 57
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry58:
    SetVarFromValue VAR_0x8008, 58
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry59:
    SetVarFromValue VAR_0x8008, 59
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry60:
    SetVarFromValue VAR_0x8008, 60
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry61:
    SetVarFromValue VAR_0x8008, 61
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry62:
    SetVarFromValue VAR_0x8008, 62
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry63:
    SetVarFromValue VAR_0x8008, 63
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry64:
    SetVarFromValue VAR_0x8008, 64
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry65:
    SetVarFromValue VAR_0x8008, 65
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry66:
    SetVarFromValue VAR_0x8008, 66
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry67:
    SetVarFromValue VAR_0x8008, 67
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry68:
    SetVarFromValue VAR_0x8008, 68
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry69:
    SetVarFromValue VAR_0x8008, 69
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry70:
    SetVarFromValue VAR_0x8008, 70
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry71:
    SetVarFromValue VAR_0x8008, 71
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry72:
    SetVarFromValue VAR_0x8008, 72
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry73:
    SetVarFromValue VAR_0x8008, 73
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry74:
    SetVarFromValue VAR_0x8008, 74
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry75:
    SetVarFromValue VAR_0x8008, 75
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry76:
    SetVarFromValue VAR_0x8008, 76
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry77:
    SetVarFromValue VAR_0x8008, 77
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry78:
    SetVarFromValue VAR_0x8008, 78
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry79:
    SetVarFromValue VAR_0x8008, 79
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry80:
    SetVarFromValue VAR_0x8008, 80
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry81:
    SetVarFromValue VAR_0x8008, 81
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry82:
    SetVarFromValue VAR_0x8008, 82
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry83:
    SetVarFromValue VAR_0x8008, 83
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry84:
    SetVarFromValue VAR_0x8008, 84
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry85:
    SetVarFromValue VAR_0x8008, 85
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry86:
    SetVarFromValue VAR_0x8008, 86
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry87:
    SetVarFromValue VAR_0x8008, 87
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry88:
    SetVarFromValue VAR_0x8008, 88
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry89:
    SetVarFromValue VAR_0x8008, 89
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry90:
    SetVarFromValue VAR_0x8008, 90
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry91:
    SetVarFromValue VAR_0x8008, 91
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry92:
    SetVarFromValue VAR_0x8008, 92
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry93:
    SetVarFromValue VAR_0x8008, 93
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry94:
    SetVarFromValue VAR_0x8008, 94
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry95:
    SetVarFromValue VAR_0x8008, 95
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry96:
    SetVarFromValue VAR_0x8008, 96
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry97:
    SetVarFromValue VAR_0x8008, 97
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry98:
    SetVarFromValue VAR_0x8008, 98
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry99:
    SetVarFromValue VAR_0x8008, 99
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry100:
    SetVarFromValue VAR_0x8008, 100
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry101:
    SetVarFromValue VAR_0x8008, 101
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry102:
    SetVarFromValue VAR_0x8008, 102
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry103:
    SetVarFromValue VAR_0x8008, 103
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry104:
    SetVarFromValue VAR_0x8008, 104
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry105:
    SetVarFromValue VAR_0x8008, 105
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry106:
    SetVarFromValue VAR_0x8008, 106
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry107:
    SetVarFromValue VAR_0x8008, 107
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry108:
    SetVarFromValue VAR_0x8008, 108
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry109:
    SetVarFromValue VAR_0x8008, 109
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry110:
    SetVarFromValue VAR_0x8008, 110
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry111:
    SetVarFromValue VAR_0x8008, 111
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry112:
    SetVarFromValue VAR_0x8008, 112
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry113:
    SetVarFromValue VAR_0x8008, 113
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry114:
    SetVarFromValue VAR_0x8008, 114
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry115:
    SetVarFromValue VAR_0x8008, 115
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry116:
    SetVarFromValue VAR_0x8008, 116
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry117:
    SetVarFromValue VAR_0x8008, 117
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry118:
    SetVarFromValue VAR_0x8008, 118
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry119:
    SetVarFromValue VAR_0x8008, 119
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry120:
    SetVarFromValue VAR_0x8008, 120
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry121:
    SetVarFromValue VAR_0x8008, 121
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry122:
    SetVarFromValue VAR_0x8008, 122
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry123:
    SetVarFromValue VAR_0x8008, 123
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry124:
    SetVarFromValue VAR_0x8008, 124
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry125:
    SetVarFromValue VAR_0x8008, 125
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry126:
    SetVarFromValue VAR_0x8008, 126
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry127:
    SetVarFromValue VAR_0x8008, 127
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry128:
    SetVarFromValue VAR_0x8008, 128
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry129:
    SetVarFromValue VAR_0x8008, 129
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry130:
    SetVarFromValue VAR_0x8008, 130
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry131:
    SetVarFromValue VAR_0x8008, 131
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry132:
    SetVarFromValue VAR_0x8008, 132
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry133:
    SetVarFromValue VAR_0x8008, 133
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry134:
    SetVarFromValue VAR_0x8008, 134
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry135:
    SetVarFromValue VAR_0x8008, 135
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry136:
    SetVarFromValue VAR_0x8008, 136
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry137:
    SetVarFromValue VAR_0x8008, 137
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry138:
    SetVarFromValue VAR_0x8008, 138
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry139:
    SetVarFromValue VAR_0x8008, 139
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry140:
    SetVarFromValue VAR_0x8008, 140
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry141:
    SetVarFromValue VAR_0x8008, 141
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry142:
    SetVarFromValue VAR_0x8008, 142
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry143:
    SetVarFromValue VAR_0x8008, 143
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry144:
    SetVarFromValue VAR_0x8008, 144
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry145:
    SetVarFromValue VAR_0x8008, 145
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry146:
    SetVarFromValue VAR_0x8008, 146
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry147:
    SetVarFromValue VAR_0x8008, 147
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry148:
    SetVarFromValue VAR_0x8008, 148
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry149:
    SetVarFromValue VAR_0x8008, 149
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry150:
    SetVarFromValue VAR_0x8008, 150
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry151:
    SetVarFromValue VAR_0x8008, 151
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry152:
    SetVarFromValue VAR_0x8008, 152
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry153:
    SetVarFromValue VAR_0x8008, 153
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry154:
    SetVarFromValue VAR_0x8008, 154
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry155:
    SetVarFromValue VAR_0x8008, 155
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry156:
    SetVarFromValue VAR_0x8008, 156
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry157:
    SetVarFromValue VAR_0x8008, 157
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry158:
    SetVarFromValue VAR_0x8008, 158
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry159:
    SetVarFromValue VAR_0x8008, 159
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry160:
    SetVarFromValue VAR_0x8008, 160
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry161:
    SetVarFromValue VAR_0x8008, 161
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry162:
    SetVarFromValue VAR_0x8008, 162
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry163:
    SetVarFromValue VAR_0x8008, 163
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry164:
    SetVarFromValue VAR_0x8008, 164
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry165:
    SetVarFromValue VAR_0x8008, 165
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry166:
    SetVarFromValue VAR_0x8008, 166
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry167:
    SetVarFromValue VAR_0x8008, 167
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry168:
    SetVarFromValue VAR_0x8008, 168
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry169:
    SetVarFromValue VAR_0x8008, 169
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry170:
    SetVarFromValue VAR_0x8008, 170
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry171:
    SetVarFromValue VAR_0x8008, 171
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry172:
    SetVarFromValue VAR_0x8008, 172
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry173:
    SetVarFromValue VAR_0x8008, 173
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry174:
    SetVarFromValue VAR_0x8008, 174
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry175:
    SetVarFromValue VAR_0x8008, 175
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry176:
    SetVarFromValue VAR_0x8008, 176
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry177:
    SetVarFromValue VAR_0x8008, 177
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry178:
    SetVarFromValue VAR_0x8008, 178
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry179:
    SetVarFromValue VAR_0x8008, 179
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry180:
    SetVarFromValue VAR_0x8008, 180
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry181:
    SetVarFromValue VAR_0x8008, 181
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry182:
    SetVarFromValue VAR_0x8008, 182
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry183:
    SetVarFromValue VAR_0x8008, 183
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry184:
    SetVarFromValue VAR_0x8008, 184
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry185:
    SetVarFromValue VAR_0x8008, 185
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry186:
    SetVarFromValue VAR_0x8008, 186
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry187:
    SetVarFromValue VAR_0x8008, 187
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry188:
    SetVarFromValue VAR_0x8008, 188
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry189:
    SetVarFromValue VAR_0x8008, 189
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry190:
    SetVarFromValue VAR_0x8008, 190
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry191:
    SetVarFromValue VAR_0x8008, 191
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry192:
    SetVarFromValue VAR_0x8008, 192
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry193:
    SetVarFromValue VAR_0x8008, 193
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry194:
    SetVarFromValue VAR_0x8008, 194
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry195:
    SetVarFromValue VAR_0x8008, 195
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry196:
    SetVarFromValue VAR_0x8008, 196
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry197:
    SetVarFromValue VAR_0x8008, 197
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry198:
    SetVarFromValue VAR_0x8008, 198
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry199:
    SetVarFromValue VAR_0x8008, 199
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry200:
    SetVarFromValue VAR_0x8008, 200
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry201:
    SetVarFromValue VAR_0x8008, 201
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry202:
    SetVarFromValue VAR_0x8008, 202
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry203:
    SetVarFromValue VAR_0x8008, 203
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry204:
    SetVarFromValue VAR_0x8008, 204
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry205:
    SetVarFromValue VAR_0x8008, 205
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry206:
    SetVarFromValue VAR_0x8008, 206
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry207:
    SetVarFromValue VAR_0x8008, 207
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry208:
    SetVarFromValue VAR_0x8008, 208
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry209:
    SetVarFromValue VAR_0x8008, 209
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry210:
    SetVarFromValue VAR_0x8008, 210
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry211:
    SetVarFromValue VAR_0x8008, 211
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry212:
    SetVarFromValue VAR_0x8008, 212
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry213:
    SetVarFromValue VAR_0x8008, 213
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry214:
    SetVarFromValue VAR_0x8008, 214
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry215:
    SetVarFromValue VAR_0x8008, 215
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry216:
    SetVarFromValue VAR_0x8008, 216
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry217:
    SetVarFromValue VAR_0x8008, 217
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry218:
    SetVarFromValue VAR_0x8008, 218
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry219:
    SetVarFromValue VAR_0x8008, 219
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry220:
    SetVarFromValue VAR_0x8008, 220
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry221:
    SetVarFromValue VAR_0x8008, 221
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry222:
    SetVarFromValue VAR_0x8008, 222
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry223:
    SetVarFromValue VAR_0x8008, 223
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry224:
    SetVarFromValue VAR_0x8008, 224
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry225:
    SetVarFromValue VAR_0x8008, 225
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry226:
    SetVarFromValue VAR_0x8008, 226
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry227:
    SetVarFromValue VAR_0x8008, 227
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry228:
    SetVarFromValue VAR_0x8008, 228
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry229:
    SetVarFromValue VAR_0x8008, 229
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry230:
    SetVarFromValue VAR_0x8008, 230
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry231:
    SetVarFromValue VAR_0x8008, 231
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry232:
    SetVarFromValue VAR_0x8008, 232
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry233:
    SetVarFromValue VAR_0x8008, 233
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry234:
    SetVarFromValue VAR_0x8008, 234
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry235:
    SetVarFromValue VAR_0x8008, 235
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry236:
    SetVarFromValue VAR_0x8008, 236
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry237:
    SetVarFromValue VAR_0x8008, 237
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry238:
    SetVarFromValue VAR_0x8008, 238
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry239:
    SetVarFromValue VAR_0x8008, 239
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry240:
    SetVarFromValue VAR_0x8008, 240
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry241:
    SetVarFromValue VAR_0x8008, 241
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry242:
    SetVarFromValue VAR_0x8008, 242
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry243:
    SetVarFromValue VAR_0x8008, 243
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry244:
    SetVarFromValue VAR_0x8008, 244
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry245:
    SetVarFromValue VAR_0x8008, 245
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry246:
    SetVarFromValue VAR_0x8008, 246
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry247:
    SetVarFromValue VAR_0x8008, 247
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry248:
    SetVarFromValue VAR_0x8008, 248
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry249:
    SetVarFromValue VAR_0x8008, 249
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry250:
    SetVarFromValue VAR_0x8008, 250
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry251:
    SetVarFromValue VAR_0x8008, 251
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry252:
    SetVarFromValue VAR_0x8008, 252
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry253:
    SetVarFromValue VAR_0x8008, 253
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry254:
    SetVarFromValue VAR_0x8008, 254
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry255:
    SetVarFromValue VAR_0x8008, 255
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry256:
    SetVarFromValue VAR_0x8008, 256
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry257:
    SetVarFromValue VAR_0x8008, 257
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry258:
    SetVarFromValue VAR_0x8008, 258
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry259:
    SetVarFromValue VAR_0x8008, 259
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry260:
    SetVarFromValue VAR_0x8008, 260
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry261:
    SetVarFromValue VAR_0x8008, 261
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry262:
    SetVarFromValue VAR_0x8008, 262
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry263:
    SetVarFromValue VAR_0x8008, 263
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry264:
    SetVarFromValue VAR_0x8008, 264
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry265:
    SetVarFromValue VAR_0x8008, 265
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry266:
    SetVarFromValue VAR_0x8008, 266
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry267:
    SetVarFromValue VAR_0x8008, 267
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry268:
    SetVarFromValue VAR_0x8008, 268
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry269:
    SetVarFromValue VAR_0x8008, 269
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry270:
    SetVarFromValue VAR_0x8008, 270
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry271:
    SetVarFromValue VAR_0x8008, 271
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry272:
    SetVarFromValue VAR_0x8008, 272
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry273:
    SetVarFromValue VAR_0x8008, 273
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry274:
    SetVarFromValue VAR_0x8008, 274
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry275:
    SetVarFromValue VAR_0x8008, 275
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry276:
    SetVarFromValue VAR_0x8008, 276
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry277:
    SetVarFromValue VAR_0x8008, 277
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry278:
    SetVarFromValue VAR_0x8008, 278
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry279:
    SetVarFromValue VAR_0x8008, 279
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry280:
    SetVarFromValue VAR_0x8008, 280
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry281:
    SetVarFromValue VAR_0x8008, 281
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry282:
    SetVarFromValue VAR_0x8008, 282
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry283:
    SetVarFromValue VAR_0x8008, 283
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry284:
    SetVarFromValue VAR_0x8008, 284
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry285:
    SetVarFromValue VAR_0x8008, 285
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry286:
    SetVarFromValue VAR_0x8008, 286
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry287:
    SetVarFromValue VAR_0x8008, 287
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry288:
    SetVarFromValue VAR_0x8008, 288
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry289:
    SetVarFromValue VAR_0x8008, 289
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry290:
    SetVarFromValue VAR_0x8008, 290
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry291:
    SetVarFromValue VAR_0x8008, 291
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry292:
    SetVarFromValue VAR_0x8008, 292
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry293:
    SetVarFromValue VAR_0x8008, 293
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry294:
    SetVarFromValue VAR_0x8008, 294
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry295:
    SetVarFromValue VAR_0x8008, 295
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry296:
    SetVarFromValue VAR_0x8008, 296
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry297:
    SetVarFromValue VAR_0x8008, 297
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry298:
    SetVarFromValue VAR_0x8008, 298
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry299:
    SetVarFromValue VAR_0x8008, 299
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry300:
    SetVarFromValue VAR_0x8008, 300
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry301:
    SetVarFromValue VAR_0x8008, 301
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry302:
    SetVarFromValue VAR_0x8008, 302
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry303:
    SetVarFromValue VAR_0x8008, 303
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry304:
    SetVarFromValue VAR_0x8008, 304
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry305:
    SetVarFromValue VAR_0x8008, 305
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry306:
    SetVarFromValue VAR_0x8008, 306
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry307:
    SetVarFromValue VAR_0x8008, 307
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry308:
    SetVarFromValue VAR_0x8008, 308
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry309:
    SetVarFromValue VAR_0x8008, 309
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry310:
    SetVarFromValue VAR_0x8008, 310
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry311:
    SetVarFromValue VAR_0x8008, 311
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry312:
    SetVarFromValue VAR_0x8008, 312
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry313:
    SetVarFromValue VAR_0x8008, 313
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry314:
    SetVarFromValue VAR_0x8008, 314
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry315:
    SetVarFromValue VAR_0x8008, 315
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry316:
    SetVarFromValue VAR_0x8008, 316
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry317:
    SetVarFromValue VAR_0x8008, 317
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry318:
    SetVarFromValue VAR_0x8008, 318
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry319:
    SetVarFromValue VAR_0x8008, 319
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry320:
    SetVarFromValue VAR_0x8008, 320
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry321:
    SetVarFromValue VAR_0x8008, 321
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry322:
    SetVarFromValue VAR_0x8008, 322
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry323:
    SetVarFromValue VAR_0x8008, 323
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry324:
    SetVarFromValue VAR_0x8008, 324
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry325:
    SetVarFromValue VAR_0x8008, 325
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry326:
    SetVarFromValue VAR_0x8008, 326
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry327:
    SetVarFromValue VAR_0x8008, 327
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry328:
    SetVarFromValue VAR_0x8008, 328
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry329:
    SetVarFromValue VAR_0x8008, 329
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry330:
    SetVarFromValue VAR_0x8008, 330
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry331:
    SetVarFromValue VAR_0x8008, 331
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry332:
    SetVarFromValue VAR_0x8008, 332
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry333:
    SetVarFromValue VAR_0x8008, 333
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry334:
    SetVarFromValue VAR_0x8008, 334
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry335:
    SetVarFromValue VAR_0x8008, 335
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry336:
    SetVarFromValue VAR_0x8008, 336
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry337:
    SetVarFromValue VAR_0x8008, 337
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry338:
    SetVarFromValue VAR_0x8008, 338
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry339:
    SetVarFromValue VAR_0x8008, 339
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry340:
    SetVarFromValue VAR_0x8008, 340
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry341:
    SetVarFromValue VAR_0x8008, 341
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry342:
    SetVarFromValue VAR_0x8008, 342
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry343:
    SetVarFromValue VAR_0x8008, 343
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry344:
    SetVarFromValue VAR_0x8008, 344
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry345:
    SetVarFromValue VAR_0x8008, 345
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry346:
    SetVarFromValue VAR_0x8008, 346
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry347:
    SetVarFromValue VAR_0x8008, 347
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry348:
    SetVarFromValue VAR_0x8008, 348
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry349:
    SetVarFromValue VAR_0x8008, 349
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry350:
    SetVarFromValue VAR_0x8008, 350
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry351:
    SetVarFromValue VAR_0x8008, 351
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry352:
    SetVarFromValue VAR_0x8008, 352
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry353:
    SetVarFromValue VAR_0x8008, 353
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry354:
    SetVarFromValue VAR_0x8008, 354
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry355:
    SetVarFromValue VAR_0x8008, 355
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry356:
    SetVarFromValue VAR_0x8008, 356
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry357:
    SetVarFromValue VAR_0x8008, 357
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry358:
    SetVarFromValue VAR_0x8008, 358
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry359:
    SetVarFromValue VAR_0x8008, 359
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry360:
    SetVarFromValue VAR_0x8008, 360
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry361:
    SetVarFromValue VAR_0x8008, 361
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry362:
    SetVarFromValue VAR_0x8008, 362
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry363:
    SetVarFromValue VAR_0x8008, 363
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry364:
    SetVarFromValue VAR_0x8008, 364
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry365:
    SetVarFromValue VAR_0x8008, 365
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry366:
    SetVarFromValue VAR_0x8008, 366
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry367:
    SetVarFromValue VAR_0x8008, 367
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry368:
    SetVarFromValue VAR_0x8008, 368
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry369:
    SetVarFromValue VAR_0x8008, 369
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry370:
    SetVarFromValue VAR_0x8008, 370
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry371:
    SetVarFromValue VAR_0x8008, 371
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry372:
    SetVarFromValue VAR_0x8008, 372
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry373:
    SetVarFromValue VAR_0x8008, 373
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry374:
    SetVarFromValue VAR_0x8008, 374
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry375:
    SetVarFromValue VAR_0x8008, 375
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry376:
    SetVarFromValue VAR_0x8008, 376
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry377:
    SetVarFromValue VAR_0x8008, 377
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry378:
    SetVarFromValue VAR_0x8008, 378
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry379:
    SetVarFromValue VAR_0x8008, 379
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry380:
    SetVarFromValue VAR_0x8008, 380
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry381:
    SetVarFromValue VAR_0x8008, 381
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry382:
    SetVarFromValue VAR_0x8008, 382
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry383:
    SetVarFromValue VAR_0x8008, 383
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry384:
    SetVarFromValue VAR_0x8008, 384
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry385:
    SetVarFromValue VAR_0x8008, 385
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry386:
    SetVarFromValue VAR_0x8008, 386
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry387:
    SetVarFromValue VAR_0x8008, 387
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry388:
    SetVarFromValue VAR_0x8008, 388
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry389:
    SetVarFromValue VAR_0x8008, 389
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry390:
    SetVarFromValue VAR_0x8008, 390
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry391:
    SetVarFromValue VAR_0x8008, 391
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry392:
    SetVarFromValue VAR_0x8008, 392
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry393:
    SetVarFromValue VAR_0x8008, 393
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry394:
    SetVarFromValue VAR_0x8008, 394
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry395:
    SetVarFromValue VAR_0x8008, 395
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry396:
    SetVarFromValue VAR_0x8008, 396
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry397:
    SetVarFromValue VAR_0x8008, 397
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry398:
    SetVarFromValue VAR_0x8008, 398
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry399:
    SetVarFromValue VAR_0x8008, 399
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry400:
    SetVarFromValue VAR_0x8008, 400
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry401:
    SetVarFromValue VAR_0x8008, 401
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry402:
    SetVarFromValue VAR_0x8008, 402
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry403:
    SetVarFromValue VAR_0x8008, 403
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry404:
    SetVarFromValue VAR_0x8008, 404
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry405:
    SetVarFromValue VAR_0x8008, 405
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry406:
    SetVarFromValue VAR_0x8008, 406
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry407:
    SetVarFromValue VAR_0x8008, 407
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry408:
    SetVarFromValue VAR_0x8008, 408
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry409:
    SetVarFromValue VAR_0x8008, 409
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry410:
    SetVarFromValue VAR_0x8008, 410
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry411:
    SetVarFromValue VAR_0x8008, 411
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry412:
    SetVarFromValue VAR_0x8008, 412
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry413:
    SetVarFromValue VAR_0x8008, 413
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry414:
    SetVarFromValue VAR_0x8008, 414
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry415:
    SetVarFromValue VAR_0x8008, 415
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry416:
    SetVarFromValue VAR_0x8008, 416
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry417:
    SetVarFromValue VAR_0x8008, 417
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry418:
    SetVarFromValue VAR_0x8008, 418
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry419:
    SetVarFromValue VAR_0x8008, 419
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry420:
    SetVarFromValue VAR_0x8008, 420
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry421:
    SetVarFromValue VAR_0x8008, 421
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry422:
    SetVarFromValue VAR_0x8008, 422
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry423:
    SetVarFromValue VAR_0x8008, 423
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry424:
    SetVarFromValue VAR_0x8008, 424
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry425:
    SetVarFromValue VAR_0x8008, 425
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry426:
    SetVarFromValue VAR_0x8008, 426
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry427:
    SetVarFromValue VAR_0x8008, 427
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry428:
    SetVarFromValue VAR_0x8008, 428
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry429:
    SetVarFromValue VAR_0x8008, 429
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry430:
    SetVarFromValue VAR_0x8008, 430
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry431:
    SetVarFromValue VAR_0x8008, 431
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry432:
    SetVarFromValue VAR_0x8008, 432
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry433:
    SetVarFromValue VAR_0x8008, 433
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry434:
    SetVarFromValue VAR_0x8008, 434
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry435:
    SetVarFromValue VAR_0x8008, 435
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry436:
    SetVarFromValue VAR_0x8008, 436
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry437:
    SetVarFromValue VAR_0x8008, 437
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry438:
    SetVarFromValue VAR_0x8008, 438
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry439:
    SetVarFromValue VAR_0x8008, 439
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry440:
    SetVarFromValue VAR_0x8008, 440
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry441:
    SetVarFromValue VAR_0x8008, 441
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry442:
    SetVarFromValue VAR_0x8008, 442
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry443:
    SetVarFromValue VAR_0x8008, 443
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry444:
    SetVarFromValue VAR_0x8008, 444
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry445:
    SetVarFromValue VAR_0x8008, 445
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry446:
    SetVarFromValue VAR_0x8008, 446
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry447:
    SetVarFromValue VAR_0x8008, 447
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry448:
    SetVarFromValue VAR_0x8008, 448
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry449:
    SetVarFromValue VAR_0x8008, 449
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry450:
    SetVarFromValue VAR_0x8008, 450
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry451:
    SetVarFromValue VAR_0x8008, 451
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry452:
    SetVarFromValue VAR_0x8008, 452
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry453:
    SetVarFromValue VAR_0x8008, 453
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry454:
    SetVarFromValue VAR_0x8008, 454
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry455:
    SetVarFromValue VAR_0x8008, 455
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry456:
    SetVarFromValue VAR_0x8008, 456
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry457:
    SetVarFromValue VAR_0x8008, 457
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry458:
    SetVarFromValue VAR_0x8008, 458
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry459:
    SetVarFromValue VAR_0x8008, 459
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry460:
    SetVarFromValue VAR_0x8008, 460
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry461:
    SetVarFromValue VAR_0x8008, 461
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry462:
    SetVarFromValue VAR_0x8008, 462
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry463:
    SetVarFromValue VAR_0x8008, 463
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry464:
    SetVarFromValue VAR_0x8008, 464
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry465:
    SetVarFromValue VAR_0x8008, 465
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry466:
    SetVarFromValue VAR_0x8008, 466
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry467:
    SetVarFromValue VAR_0x8008, 467
    SetVarFromValue VAR_0x8009, 1
    GoTo VisibleItems_Entry468
VisibleItems_Entry468:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    WaitSE SE_CONFIRM_sseq_3
    SetVarFromVar VAR_0x8004, VAR_0x8008
    SetVarFromVar VAR_0x8005, VAR_0x8009
    CanFitItem 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, VisibleItems_287A
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VisibleItems_28BD
    End
VisibleItems_287A:
    CallCommonScript 2001
    RemoveObject 32781
    AddItem 32772, 32773, VAR_0x800C
    TrySetUnusedCollectedOrbFlag 32772
    CompareVarToValue VAR_0x8004, 463
    CallIf 1, VisibleItems_28D3
    IsItemTMHM 32772, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, VisibleItems_28D9
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, VisibleItems_28EF
    End
VisibleItems_28BD:
    BufferItemName 0, 32772
    Message 4
    WaitButton
    SetVarFromValue VAR_0x800C, 0
    GoTo VisibleItems_2900
VisibleItems_28D3:
    SetFlag FLAG_ALT_MUSIC_GALACTIC_HQ_1F
    Return
VisibleItems_28D9:
    BufferPlayerName 0
    BufferItemNameWithArticle 1, 32772
    BufferTMHMMoveName 2, 32772
    Message 6
    GoTo VisibleItems_2906
VisibleItems_28EF:
    BufferPlayerName 0
    BufferItemNameWithArticle 1, 32772
    Message 3
    GoTo VisibleItems_2906
VisibleItems_2900:
    CloseMessage
    ReleaseAll
    End
VisibleItems_2906:
    WaitFanfare
    CheckItemIsPlate 32772, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    CallIf 1, VisibleItems_2999
    BufferPlayerName 0
    BufferItemName 1, 32772
    GetItemPocket 32772, VAR_0x800C
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 7
    GoToIf 1, VisibleItems_299F
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, VisibleItems_29B0
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, VisibleItems_29C1
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, VisibleItems_29D2
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, VisibleItems_29E3
    CompareVarToValue VAR_0x8008, 6
    GoToIf 1, VisibleItems_29F4
    CompareVarToValue VAR_0x8008, 5
    GoToIf 1, VisibleItems_2A05
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, VisibleItems_2A16
    End
VisibleItems_2999:
    CallCommonScript 2038
    Return
VisibleItems_299F:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo VisibleItems_2A27
VisibleItems_29B0:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo VisibleItems_2A27
VisibleItems_29C1:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo VisibleItems_2A27
VisibleItems_29D2:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo VisibleItems_2A27
VisibleItems_29E3:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo VisibleItems_2A27
VisibleItems_29F4:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo VisibleItems_2A27
VisibleItems_2A05:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo VisibleItems_2A27
VisibleItems_2A16:
    GetItemPocket 32772, VAR_0x800C
    BufferPocketName 2, 32780
    GoTo VisibleItems_2A27
VisibleItems_2A27:
    CreateJournalEvent 18, 32772, 0, 0, 0
    Message 9
    WaitButton
    SetVarFromValue VAR_0x800C, 1
    GoTo VisibleItems_2900
