@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry FloaromaMeadowHouse_Entry0
    ScriptEntry FloaromaMeadowHouse_Entry1
    ScriptEntryEnd

@ Oxide: the gift clown that stood here is gone (Ian, 2026-09-27; the encounter track's
@ clown-replacements.md): its object, its script entry and its lines, with the
@ orphaned pick-menu names. Where the town had no other capture, new grass
@ outside takes its place.

FloaromaMeadowHouse_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 0
    WaitButton
    CloseMessage
    ReleaseAll
    End
FloaromaMeadowHouse_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
