@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry CanalaveLibrary2f_Entry0
    ScriptEntry CanalaveLibrary2f_Entry1
    ScriptEntry CanalaveLibrary2f_Entry2
    ScriptEntry CanalaveLibrary2f_Entry3
    ScriptEntry CanalaveLibrary2f_Entry4
    ScriptEntry CanalaveLibrary2f_Entry5
    ScriptEntry CanalaveLibrary2f_Entry6
    ScriptEntryEnd

CanalaveLibrary2f_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_LAKE_VALOR_EXPLODED
    GoToIf 1, CanalaveLibrary2f_00EB
    Message 0
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CompareVarToValue VAR_ARCEUS_EVENT_STATE, 3
    GoToIf 4, CanalaveLibrary2f_00F6
    Message 2
    GoTo CanalaveLibrary2f_0102
CanalaveLibrary2f_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 3
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 4
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_Entry4:
    SetFlag FLAG_HIDE_CANALAVE_LIBRARY_2F_HIKER
    CompareVarToValue VAR_ARCEUS_EVENT_STATE, 2
    CallIf 1, CanalaveLibrary2f_010A
    End
CanalaveLibrary2f_Entry5:
    LockAll
    ApplyMovement 1, CanalaveLibrary2f_Movement_0378
    WaitMovement
    Message 5
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveLibrary2f_0110
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveLibrary2f_0142
    End
CanalaveLibrary2f_Entry6:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 14
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveLibrary2f_0165
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveLibrary2f_02D0
    GoTo CanalaveLibrary2f_02D0
CanalaveLibrary2f_00EB:
    Message 1
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_00F6:
    BufferPlayerName 0
    Message 13
    GoTo CanalaveLibrary2f_0102
CanalaveLibrary2f_0102:
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_010A:
    ClearFlag FLAG_HIDE_CANALAVE_LIBRARY_2F_HIKER
    Return
CanalaveLibrary2f_0110:
    Message 7
    CloseMessage
    ApplyMovement 1, CanalaveLibrary2f_Movement_0390
    WaitMovement
    Message 8
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveLibrary2f_02DB
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveLibrary2f_031E
    End
CanalaveLibrary2f_0142:
    Message 6
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveLibrary2f_0110
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveLibrary2f_0142
    End
CanalaveLibrary2f_0165:
    GetRandom VAR_0x800C, 7
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveLibrary2f_01C8
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveLibrary2f_01F4
    CompareVarToValue VAR_0x800C, 2
    GoToIf 1, CanalaveLibrary2f_0220
    CompareVarToValue VAR_0x800C, 3
    GoToIf 1, CanalaveLibrary2f_024C
    CompareVarToValue VAR_0x800C, 4
    GoToIf 1, CanalaveLibrary2f_0278
    CompareVarToValue VAR_0x800C, 5
    GoToIf 1, CanalaveLibrary2f_02A4
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, CanalaveLibrary2f_034C
    End
CanalaveLibrary2f_01C8:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, CanalaveLibrary2f_0341
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_DUGTRIO, 50, 0, VAR_0x800C
    Message 15
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_01F4:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, CanalaveLibrary2f_0341
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_BANETTE, 50, 0, VAR_0x800C
    Message 15
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_0220:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, CanalaveLibrary2f_0341
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_HARIYAMA, 50, 0, VAR_0x800C
    Message 15
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_024C:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, CanalaveLibrary2f_0341
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_AGGRON, 50, 0, VAR_0x800C
    Message 15
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_0278:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, CanalaveLibrary2f_0341
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_DRAPION, 50, 0, VAR_0x800C
    Message 15
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_02A4:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, CanalaveLibrary2f_0341
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_DUSCLOPS, 50, 0, VAR_0x800C
    Message 15
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_02D0:
    Message 15
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_02DB:
    Message 10
    CloseMessage
    ApplyMovement 1, CanalaveLibrary2f_Movement_03A0
    WaitMovement
    Message 11
    CloseMessage
    ApplyMovement 1, CanalaveLibrary2f_Movement_03A8
    WaitMovement
    Message 12
    CloseMessage
    ApplyMovement LOCALID_PLAYER, CanalaveLibrary2f_Movement_03B0
    ApplyMovement 1, CanalaveLibrary2f_Movement_03BC
    WaitMovement
    RemoveObject 1
    SetVarFromValue VAR_ARCEUS_EVENT_STATE, 3
    ReleaseAll
    End
CanalaveLibrary2f_031E:
    Message 9
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, CanalaveLibrary2f_02DB
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, CanalaveLibrary2f_031E
    End
CanalaveLibrary2f_0341:
    Message 16
    WaitButton
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_034C:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, CanalaveLibrary2f_0341
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_PRIMEAPE, 50, 0, VAR_0x800C
    Message 15
    CloseMessage
    ReleaseAll
    End
CanalaveLibrary2f_Movement_0378:
    WalkOnSpotNormalEast 1
    EmoteExclamationMark 1
    WalkNormalEast 1
    WalkNormalNorth 1
    WalkOnSpotNormalEast 1
    EndMovement

CanalaveLibrary2f_Movement_0390:
    WalkOnSpotNormalSouth 1
    WalkOnSpotNormalNorth 1
    WalkOnSpotNormalEast 1
    EndMovement

CanalaveLibrary2f_Movement_03A0:
    WalkOnSpotNormalWest 1
    EndMovement

CanalaveLibrary2f_Movement_03A8:
    WalkOnSpotNormalEast 1
    EndMovement

CanalaveLibrary2f_Movement_03B0:
    WalkNormalSouth 1
    WalkOnSpotNormalNorth 1
    EndMovement

CanalaveLibrary2f_Movement_03BC:
    Delay8 2
    WalkNormalEast 2
    EndMovement

