@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry ValleyWindworksOutside_Entry0
    ScriptEntry ValleyWindworksOutside_Entry1
    ScriptEntry ValleyWindworksOutside_Entry2
    ScriptEntry ValleyWindworksOutside_Entry3
    ScriptEntry ValleyWindworksOutside_Entry4
    ScriptEntry ValleyWindworksOutside_Entry5
    ScriptEntry ValleyWindworksOutside_Entry6
    ScriptEntry ValleyWindworksOutside_Entry7
    ScriptEntryEnd

ValleyWindworksOutside_Entry0:
    CompareVarToValue VAR_VALLEY_WINDWORKS_TEAM_GALACTIC_STATE, 2
    CallIf 1, ValleyWindworksOutside_0203
    CheckFlag FLAG_UNLOCKED_VALLEY_WINDWORKS_DOOR
    CallIf 1, ValleyWindworksOutside_020B
    CheckFlag FLAG_UNLOCKED_VALLEY_WINDWORKS_DOOR
    CallIf 0, ValleyWindworksOutside_0215
    CompareVarToValue VAR_VALLEY_WINDWORKS_STATE, 2
    GoToIf 0, ValleyWindworksOutside_021F
    @ Platinum Oxide (Ian, 2026-09-26): the balloon never shows. A Drifloon
    @ met by script before the second gym was too much with three
    @ immunities, so Drifloon is a wild encounter instead.
    GoTo ValleyWindworksOutside_021F
ValleyWindworksOutside_Entry1:
    CheckFlag FLAG_UNLOCKED_VALLEY_WINDWORKS_DOOR
    CallIf 1, ValleyWindworksOutside_020B
    CheckFlag FLAG_UNLOCKED_VALLEY_WINDWORKS_DOOR
    CallIf 0, ValleyWindworksOutside_0215
    CheckFlag FLAG_MAP_LOCAL_REMOVE_OBJECT
    GoToIf 1, ValleyWindworksOutside_022B
    End
ValleyWindworksOutside_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 0
    CloseMessage
    StartTrainerBattle 843, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, ValleyWindworksOutside_0239
    Message 1
    CloseMessage
    ApplyMovement 0, ValleyWindworksOutside_Movement_0282
    WaitMovement
    LoadDoorAnimation 7, 20, 19, 14, 77
    PlayDoorOpenAnimation 77
    WaitForAnimation 77
    ApplyMovement 0, ValleyWindworksOutside_Movement_028A
    WaitMovement
    PlayDoorCloseAnimation 77
    WaitForAnimation 77
    UnloadAnimation 77
    Message 4
    RemoveObject 0
    CloseMessage
    ReleaseAll
    End
ValleyWindworksOutside_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    CheckFlag FLAG_OBTAINED_FLOAROMA_MEADOW_WORKS_KEY
    GoToIf 1, ValleyWindworksOutside_023F
    Message 5
    WaitButton
    CloseMessage
    ReleaseAll
    End
ValleyWindworksOutside_Entry4:
    DrawSignpostInstantMessage 9, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
ValleyWindworksOutside_Entry5:
    End
ValleyWindworksOutside_Entry6:
    End
ValleyWindworksOutside_Entry7:
    LockAll
    ApplyMovement 6, ValleyWindworksOutside_Movement_0296
    ApplyMovement LOCALID_PLAYER, ValleyWindworksOutside_Movement_02AA
    WaitMovement
    Message 2
    CloseMessage
    ApplyMovement LOCALID_PLAYER, ValleyWindworksOutside_Movement_02BA
    ApplyMovement 6, ValleyWindworksOutside_Movement_02C6
    WaitMovement
    LoadDoorAnimation 7, 20, 19, 14, 77
    PlayDoorOpenAnimation 77
    WaitForAnimation 77
    ApplyMovement 6, ValleyWindworksOutside_Movement_02DA
    WaitMovement
    PlayDoorCloseAnimation 77
    WaitForAnimation 77
    UnloadAnimation 77
    WaitTime 120, VAR_0x800C
    LoadDoorAnimation 7, 20, 19, 14, 77
    PlayDoorOpenAnimation 77
    WaitForAnimation 77
    ApplyMovement 6, ValleyWindworksOutside_Movement_02EA
    WaitMovement
    PlayDoorCloseAnimation 77
    WaitForAnimation 77
    UnloadAnimation 77
    ApplyMovement 6, ValleyWindworksOutside_Movement_02F6
    WaitMovement
    Message 3
    CloseMessage
    ApplyMovement LOCALID_PLAYER, ValleyWindworksOutside_Movement_02FE
    ApplyMovement 6, ValleyWindworksOutside_Movement_030E
    WaitMovement
    RemoveObject 6
    SetVarFromValue VAR_VALLEY_WINDWORKS_LOOKER_STATE, 2
    ReleaseAll
    End
ValleyWindworksOutside_0203:
    SetVarFromValue VAR_VALLEY_WINDWORKS_TEAM_GALACTIC_STATE, 3
    Return
ValleyWindworksOutside_020B:
    SetBgEventPos 1, 243, 650
    Return
ValleyWindworksOutside_0215:
    SetWarpEventPos 0, 243, 650
    Return
ValleyWindworksOutside_021F:
    SetFlag FLAG_HIDE_VALLEY_WINDWORKS_OUTSIDE_DRIFLOON
    End
ValleyWindworksOutside_0225:
    ClearFlag FLAG_HIDE_VALLEY_WINDWORKS_OUTSIDE_DRIFLOON
    End
ValleyWindworksOutside_022B:
    SetFlag FLAG_HIDE_VALLEY_WINDWORKS_OUTSIDE_DRIFLOON
    RemoveObject 4
    ClearFlag FLAG_MAP_LOCAL_REMOVE_OBJECT
    End
ValleyWindworksOutside_0239:
    BlackOutFromBattle
    ReleaseAll
    End
ValleyWindworksOutside_023F:
    BufferItemName 0, ITEM_WORKS_KEY
    Message 6
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, ValleyWindworksOutside_027B
    SetFlag FLAG_UNLOCKED_VALLEY_WINDWORKS_DOOR
    Call ValleyWindworksOutside_020B
    SetWarpEventPos 0, 243, 654
    Message 7
    WaitButton
    CloseMessage
    ReleaseAll
    End
ValleyWindworksOutside_0275:
    BlackOutFromBattle
    ReleaseAll
    End
ValleyWindworksOutside_027B:
    CloseMessage
    ReleaseAll
    End
    .byte 0

ValleyWindworksOutside_Movement_0282:
    WalkOnSpotNormalNorth 1
    EndMovement

ValleyWindworksOutside_Movement_028A:
    WalkNormalNorth 1
    SetInvisible 1
    EndMovement

ValleyWindworksOutside_Movement_0296:
    EmoteExclamationMark 1
    Delay8 1
    WalkFastNorth 4
    WalkOnSpotFastEast 1
    EndMovement

ValleyWindworksOutside_Movement_02AA:
    Delay8 5
    Delay4 1
    WalkOnSpotNormalWest 1
    EndMovement

ValleyWindworksOutside_Movement_02BA:
    WalkNormalSouth 1
    WalkOnSpotNormalNorth 1
    EndMovement

ValleyWindworksOutside_Movement_02C6:
    Delay8 1
    Delay4 1
    WalkNormalEast 1
    WalkOnSpotNormalNorth 1
    EndMovement

ValleyWindworksOutside_Movement_02DA:
    WalkNormalNorth 1
    SetInvisible 1
    FaceSouth 1
    EndMovement

ValleyWindworksOutside_Movement_02EA:
    SetVisible 1
    WalkFastSouth 1
    EndMovement

ValleyWindworksOutside_Movement_02F6:
    WalkOnSpotFastSouth 1
    EndMovement

ValleyWindworksOutside_Movement_02FE:
    Delay8 1
    WalkOnSpotNormalWest 1
    WalkOnSpotNormalSouth 1
    EndMovement

ValleyWindworksOutside_Movement_030E:
    WalkFastWest 1
    WalkFastSouth 1
    WalkFastSouth 6
    WalkFastWest 9
    EndMovement

