@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry Route207_Entry0
    ScriptEntry Route207_Entry1
    ScriptEntry Route207_Entry2
    ScriptEntry Route207_Entry3
    ScriptEntry Route207_Entry4
    ScriptEntry Route207_Entry5
    ScriptEntry Route207_Entry6
    ScriptEntry Route207_Entry7
    ScriptEntry Route207_Entry8
    ScriptEntryEnd

Route207_Entry0:
    GetPlayerGender VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 1, Route207_0192
    CompareVarToValue VARS_START, 1
    GoToIf 1, Route207_019A
    End
Route207_Entry1:
    LockAll
    GetPlayerMapPos 32772, 32773
    SetObjectEventPos 18, 331, 32773
    Call Route207_01A2
    ApplyMovement 18, Route207_Movement_0504
    WaitMovement
    CallCommonScript 2040
    ApplyMovement 18, Route207_Movement_0510
    WaitMovement
    ApplyMovement LOCALID_PLAYER, Route207_Movement_0518
    WaitMovement
    GoTo Route207_01B0
Route207_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 8
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route207_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_RECEIVED_BICYCLE
    GoToIf 1, Route207_01C7
    Message 9
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route207_Entry4:
    DrawSignpostInstantMessage 11, 1, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
Route207_Entry5:
    DrawSignpostInstantMessage 12, 1, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
Route207_Entry6:
    DrawSignpostTextBox 3, 0
    SetSignpostCommand 3
    WaitForSignpostDone
    DrawSignpostScrollingMessage 13, VAR_0x800C
    CallCommonScript 2000
    End
Route207_Entry7:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A8C
    GoToIf 1, Route207_01D2
    CheckFlag FLAG_TRAVELED_WITH_MIRA
    GoToIf 1, Route207_01DD
    Message 14
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route207_Entry8:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A6A
    GoToIf 0, Route207_027E
    Message 20
    InitLocalTextListMenu 1, 1, 0, VAR_0x800C, 1
    AddListMenuEntry 21, 0, 255
    CheckFlag FLAG_UNK_0x0A69
    CallIf 1, Route207_0287
    CheckFlag FLAG_UNK_0x0A68
    CallIf 1, Route207_0291
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, Route207_029B
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, Route207_02CD
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, Route207_02FF
    GoTo Route207_0331
Route207_0192:
    SetVarFromValue OBJ_GFX_VARS_START, 97
    End
Route207_019A:
    SetVarFromValue OBJ_GFX_VARS_START, 0
    End
Route207_01A2:
    ClearFlag FLAG_HIDE_ROUTE_207_COUNTERPART
    AddObject 18
    LockObject 18
    Return
Route207_01B0:
    GetPlayerGender VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route207_0337
    GoTo Route207_0363
Route207_01C7:
    Message 10
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route207_01D2:
    Message 16
    WaitButton
    CloseMessage
    ReleaseAll
    End
Route207_01DD:
    Message 15
    WaitButton
    CloseMessage
    SetVarFromValue VAR_0x8004, 80
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 81
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 82
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 83
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 84
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 85
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 107
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 108
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetVarFromValue VAR_0x8004, 109
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    SetFlag FLAG_UNK_0x0A8C
    GoTo Route207_01D2
Route207_027E:
    Message 19
    CloseMessage
    ReleaseAll
    End
Route207_0287:
    AddListMenuEntry 22, 1, 255
    Return
Route207_0291:
    AddListMenuEntry 23, 2, 255
    Return
Route207_029B:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 211, 12, 36, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Route207_02CD:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 210, 42, 40, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Route207_02FF:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 215, 7, 6, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
Route207_0331:
    CloseMessage
    ReleaseAll
    End
Route207_0337:
    BufferPlayerName 0
    Message 0
    CloseMessage
    GetPlayerStarterSpecies VAR_0x800C
    CompareVarToValue VAR_0x800C, 387
    GoToIf 1, Route207_038F
    CompareVarToValue VAR_0x800C, 390
    GoToIf 1, Route207_03AC
    GoTo Route207_03C9
Route207_0363:
    BufferPlayerName 0
    Message 4
    CloseMessage
    GetPlayerStarterSpecies VAR_0x800C
    CompareVarToValue VAR_0x800C, 387
    GoToIf 1, Route207_03E6
    CompareVarToValue VAR_0x800C, 390
    GoToIf 1, Route207_0403
    GoTo Route207_0420
Route207_038F:
    StartTrainerBattle 799, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route207_043D
    GoTo Route207_0447
Route207_03AC:
    StartTrainerBattle 793, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route207_043D
    GoTo Route207_0447
Route207_03C9:
    StartTrainerBattle 794, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route207_043D
    GoTo Route207_0447
Route207_03E6:
    StartTrainerBattle 802, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route207_043D
    GoTo Route207_0485
Route207_0403:
    StartTrainerBattle 800, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route207_043D
    GoTo Route207_0485
Route207_0420:
    StartTrainerBattle 801, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, Route207_043D
    GoTo Route207_0485
Route207_043D:
    RemoveObject 18
    BlackOutFromBattle
    ReleaseAll
    End
Route207_0447:
    BufferPlayerName 0
    Message 17
    InitGlobalTextListMenu 30, 13, 0, VAR_0x800C, 0
    SetMenuXOriginSide 1
    AddListMenuEntry 137, 0, 255
    AddListMenuEntry 138, 1, 255
    ShowListMenu
    Message 1
    Call Route207_04C3
    Message 2
    Call Route207_04D5
    Message 3
    GoTo Route207_04E6
Route207_0485:
    BufferPlayerName 0
    Message 18
    InitGlobalTextListMenu 30, 13, 0, VAR_0x800C, 0
    SetMenuXOriginSide 1
    AddListMenuEntry 137, 0, 255
    AddListMenuEntry 138, 1, 255
    ShowListMenu
    Message 5
    Call Route207_04C3
    Message 6
    Call Route207_04D5
    Message 7
    GoTo Route207_04E6
Route207_04C3:
    SetVarFromValue VAR_0x8004, 231
    SetVarFromValue VAR_0x8005, 1
    CallCommonScript 2044
    Return
Route207_04D5:
    SetVarFromValue VAR_0x8004, 6
    CallCommonScript 2009
    BufferPoketchAppName 1, 6
    Return
Route207_04E6:
    CloseMessage
    ApplyMovement 18, Route207_Movement_0520
    WaitMovement
    RemoveObject 18
    CallCommonScript 2041
    SetVarFromValue VAR_ROUTE_207_COUNTERPART_TRIGGER_STATE, 1
    ReleaseAll
    End
Route207_Movement_0504:
    WalkNormalEast 3
    EmoteExclamationMark 1
    EndMovement

Route207_Movement_0510:
    WalkNormalEast 5
    EndMovement

Route207_Movement_0518:
    WalkOnSpotNormalWest 1
    EndMovement

Route207_Movement_0520:
    WalkNormalWest 8
    EndMovement

