@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry SolaceonTown_Entry0
    ScriptEntry SolaceonTown_Entry1
    ScriptEntry SolaceonTown_Entry2
    ScriptEntry SolaceonTown_Entry3
    ScriptEntry SolaceonTown_Entry4
    ScriptEntry SolaceonTown_Entry5
    ScriptEntry SolaceonTown_Entry6
    ScriptEntry SolaceonTown_Entry7
    ScriptEntry SolaceonTown_Entry8
    ScriptEntry SolaceonTown_Entry9
    ScriptEntry SolaceonTown_Entry10
    ScriptEntry SolaceonTown_Entry11
    ScriptEntry SolaceonTown_Entry12
    ScriptEntryEnd

SolaceonTown_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 3
    WaitButton
    CloseMessage
    ReleaseAll
    End
SolaceonTown_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckBadgeAcquired 4, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SolaceonTown_0236
    Message 4
    WaitButton
    CloseMessage
    ReleaseAll
    End
SolaceonTown_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 6
    WaitButton
    CloseMessage
    ReleaseAll
    End
SolaceonTown_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 7
    WaitButton
    CloseMessage
    ReleaseAll
    End
SolaceonTown_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 8
    WaitButton
    CloseMessage
    ReleaseAll
    End
SolaceonTown_Entry5:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckPoketchAppRegistered 9, VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, SolaceonTown_0241
    GetLocalDexSeenCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 50
    GoToIf 0, SolaceonTown_024C
    Message 10
    SetVarFromValue VAR_0x8004, 9
    CallCommonScript 2009
    WaitButton
    CloseMessage
    ReleaseAll
    End
SolaceonTown_Entry6:
    DrawSignpostInstantMessage 12, 0, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
SolaceonTown_Entry7:
    DrawSignpostInstantMessage 13, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
SolaceonTown_Entry8:
    DrawSignpostInstantMessage 14, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
SolaceonTown_Entry9:
    CheckDaycareHasEgg VARS_START
    CompareVarToValue VARS_START, 0
    GoToIf 5, SolaceonTown_0257
    End
SolaceonTown_Entry10:
    End
SolaceonTown_Entry11:
    LockAll
    ApplyMovement LOCALID_PLAYER, SolaceonTown_Movement_0326
    WaitMovement
    CallCommonScript 2042
    GetPlayerMapPos 32772, 32773
    SetObjectEventPos 18, 32772, 661
    ClearFlag FLAG_HIDE_SOLACEON_TOWN_RIVAL
    AddObject 18
    LockObject 18
    ApplyMovement LOCALID_PLAYER, SolaceonTown_Movement_0336
    ApplyMovement 18, SolaceonTown_Movement_033E
    WaitMovement
    Message 0
    CloseMessage
    ApplyMovement 18, SolaceonTown_Movement_0346
    WaitMovement
    BufferRivalName 0
    BufferPlayerName 1
    Message 1
    ApplyMovement 18, SolaceonTown_Movement_035E
    WaitMovement
    Message 2
    CloseMessage
    ApplyMovement 18, SolaceonTown_Movement_0366
    WaitMovement
    RemoveObject 18
    CallCommonScript 2043
    SetVarFromValue VAR_SOLACEON_TOWN_STATE, 1
    ReleaseAll
    End
SolaceonTown_Entry12:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A84
    GoToIf 0, SolaceonTown_025F
    Message 16
    InitLocalTextListMenu 1, 1, 0, VAR_0x800C, 1
    CheckFlag FLAG_UNK_0x0A85
    CallIf 1, SolaceonTown_026C
    CheckFlag FLAG_UNK_0x0A83
    CallIf 1, SolaceonTown_0276
    CheckFlag FLAG_UNK_0x0A81
    CallIf 1, SolaceonTown_0280
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, SolaceonTown_028A
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, SolaceonTown_02BC
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, SolaceonTown_02EE
    GoTo SolaceonTown_0320
SolaceonTown_0236:
    Message 5
    WaitButton
    CloseMessage
    ReleaseAll
    End
SolaceonTown_0241:
    Message 11
    WaitButton
    CloseMessage
    ReleaseAll
    End
SolaceonTown_024C:
    Message 9
    WaitButton
    CloseMessage
    ReleaseAll
    End
SolaceonTown_0257:
    SetObjectEventDir 3, 3
    End
SolaceonTown_025F:
    Message 15
    SetFlag FLAG_UNK_0x0A84
    CloseMessage
    ReleaseAll
    End
SolaceonTown_026C:
    AddListMenuEntry 17, 0, 255
    Return
SolaceonTown_0276:
    AddListMenuEntry 18, 1, 255
    Return
SolaceonTown_0280:
    AddListMenuEntry 19, 2, 255
    Return
SolaceonTown_028A:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 86, 465, 698, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SolaceonTown_02BC:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 132, 717, 612, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SolaceonTown_02EE:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 442, 472, 539, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
SolaceonTown_0320:
    CloseMessage
    ReleaseAll
    End
SolaceonTown_Movement_0326:
    Delay8 1
    EmoteExclamationMark 1
    Delay8 3
    EndMovement

SolaceonTown_Movement_0336:
    FaceNorth 1
    EndMovement

SolaceonTown_Movement_033E:
    WalkFastSouth 7
    EndMovement

SolaceonTown_Movement_0346:
    WalkOnSpotFastWest 1
    Delay8 1
    WalkOnSpotFastEast 1
    Delay8 1
    WalkOnSpotFastSouth 1
    EndMovement

SolaceonTown_Movement_035E:
    EmoteExclamationMark 1
    EndMovement

SolaceonTown_Movement_0366:
    WalkFastNorth 7
    EndMovement

