@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry UnusedJubilifeCitySouthHouse3f_Entry0
    ScriptEntry UnusedJubilifeCitySouthHouse3f_Entry1
    ScriptEntryEnd

UnusedJubilifeCitySouthHouse3f_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 0
    WaitButton
    CloseMessage
    ReleaseAll
    End
UnusedJubilifeCitySouthHouse3f_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 1
    InitLocalTextListMenu 1, 1, 0, VAR_0x800C, 1
    AddListMenuEntry 2, 0, 255
    AddListMenuEntry 3, 1, 255
    AddListMenuEntry 4, 2, 255
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, UnusedJubilifeCitySouthHouse3f_007D
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, UnusedJubilifeCitySouthHouse3f_00A9
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, UnusedJubilifeCitySouthHouse3f_00D5
    GoTo UnusedJubilifeCitySouthHouse3f_0101
UnusedJubilifeCitySouthHouse3f_007D:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, UnusedJubilifeCitySouthHouse3f_010C
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_GLAMEOW, 8, 0, VAR_0x800C
    Message 67
    CloseMessage
    ReleaseAll
    End
UnusedJubilifeCitySouthHouse3f_00A9:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, UnusedJubilifeCitySouthHouse3f_010C
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_SKITTY, 8, 0, VAR_0x800C
    Message 67
    CloseMessage
    ReleaseAll
    End
UnusedJubilifeCitySouthHouse3f_00D5:
    CloseMessage
    GetPartyCount VAR_0x800C
    CompareVarToValue VAR_0x800C, 6
    GoToIf 1, UnusedJubilifeCitySouthHouse3f_010C
    PlayFanfare SEQ_FANFA4_sseq
    WaitFanfare
    GivePokemon SPECIES_PURRLOIN, 8, 0, VAR_0x800C
    Message 67
    CloseMessage
    ReleaseAll
    End
UnusedJubilifeCitySouthHouse3f_0101:
    Message 5
    WaitButton
    CloseMessage
    ReleaseAll
    End
UnusedJubilifeCitySouthHouse3f_010C:
    Message 6
    WaitButton
    CloseMessage
    ReleaseAll
    End
    .balign 4, 0

