@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry StarkMountainRoom2_Entry0
    ScriptEntry StarkMountainRoom2_Entry1
    ScriptEntry StarkMountainRoom2_Entry2
    ScriptEntry StarkMountainRoom2_Entry3
    ScriptEntry StarkMountainRoom2_Entry4
    ScriptEntry StarkMountainRoom2_Entry5
    ScriptEntry StarkMountainRoom2_Entry6
    ScriptEntryEnd

StarkMountainRoom2_Entry0:
    LockAll
    SetPlayerBike 0
    CheckFlag FLAG_TALKED_TO_STARK_MOUNTAIN_ROOM_2_BUCK
    CallIf 0, StarkMountainRoom2_012B
    CheckFlag FLAG_TALKED_TO_STARK_MOUNTAIN_ROOM_2_BUCK
    CallIf 1, StarkMountainRoom2_0165
    BufferPlayerName 0
    PlayFanfare SEQ_GONIN_sseq
    Message 1
    WaitFanfare
    SetFlag FLAG_TALKED_TO_STARK_MOUNTAIN_ROOM_2_BUCK
    SetVarFromValue VAR_STARK_MOUNTAIN_ROOM_2_FOLLOWER_BUCK_STATE, 1
    Message 2
    WaitButton
    CloseMessage
    SetVarFromValue VAR_PARTNER_TRAINER_ID, 611
    SetHasPartner
    SetMovementType 14, 48
    ReleaseAll
    End
StarkMountainRoom2_Entry1:
    LockAll
    ApplyMovement 14, StarkMountainRoom2_Movement_0244
    ApplyMovement LOCALID_PLAYER, StarkMountainRoom2_Movement_024C
    WaitMovement
    Message 4
    CloseMessage
    SetVarFromValue VAR_STARK_MOUNTAIN_ROOM_2_FOLLOWER_BUCK_STATE, 0
    ClearHasPartner
    SetMovementType 14, 15
    ApplyMovement 14, StarkMountainRoom2_Movement_0254
    WaitMovement
    ReleaseAll
    End
StarkMountainRoom2_Entry2:
    LockAll
    ClearHasPartner
    SetMovementType 14, 15
    GetPlayerDir VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, StarkMountainRoom2_0188
    GoTo StarkMountainRoom2_01A0
StarkMountainRoom2_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 6
    WaitButton
    CloseMessage
    ReleaseAll
    End
StarkMountainRoom2_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 7
    WaitButton
    CloseMessage
    ReleaseAll
    End
StarkMountainRoom2_Entry5:
    CompareVarToValue VAR_STARK_MOUNTAIN_ROOM_2_FOLLOWER_BUCK_STATE, 2
    GoToIf 0, StarkMountainRoom2_01B8
    End
StarkMountainRoom2_Entry6:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A75
    GoToIf 0, StarkMountainRoom2_01C0
    CheckFlag FLAG_ARRESTED_CHARON_STARK_MOUNTAIN
    GoToIf 0, StarkMountainRoom2_01CD
    Message 8
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, StarkMountainRoom2_01D6
    GoTo StarkMountainRoom2_0208
StarkMountainRoom2_012B:
    SetObjectEventPos 14, 42, 78
    SetObjectEventDir 14, 0
    SetObjectEventMovementType 14, 14
    ClearFlag FLAG_HIDE_STARK_MOUNTAIN_ROOM_2_BUCK
    AddObject 14
    ApplyMovement 14, StarkMountainRoom2_Movement_025C
    WaitMovement
    ApplyMovement LOCALID_PLAYER, StarkMountainRoom2_Movement_0264
    WaitMovement
    BufferPlayerName 0
    Message 0
    CloseMessage
    Return
StarkMountainRoom2_0165:
    SetObjectEventPos 14, 42, 68
    SetObjectEventDir 14, 0
    SetObjectEventMovementType 14, 14
    ApplyMovement 14, StarkMountainRoom2_Movement_026C
    WaitMovement
    Message 3
    Return
StarkMountainRoom2_0188:
    ApplyMovement 14, StarkMountainRoom2_Movement_0274
    ApplyMovement LOCALID_PLAYER, StarkMountainRoom2_Movement_0280
    WaitMovement
    GoTo StarkMountainRoom2_020E
StarkMountainRoom2_01A0:
    ApplyMovement 14, StarkMountainRoom2_Movement_028C
    ApplyMovement LOCALID_PLAYER, StarkMountainRoom2_Movement_0280
    WaitMovement
    GoTo StarkMountainRoom2_020E
StarkMountainRoom2_01B8:
    SetVarFromValue VAR_STARK_MOUNTAIN_ROOM_2_FOLLOWER_BUCK_STATE, 0
    End
StarkMountainRoom2_01C0:
    Message 6
    SetFlag FLAG_UNK_0x0A75
    CloseMessage
    ReleaseAll
    End
StarkMountainRoom2_01CD:
    Message 7
    CloseMessage
    ReleaseAll
    End
StarkMountainRoom2_01D6:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 262, 750, 232, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
StarkMountainRoom2_0208:
    CloseMessage
    ReleaseAll
    End
StarkMountainRoom2_020E:
    ApplyMovement 14, StarkMountainRoom2_Movement_0294
    WaitMovement
    BufferPlayerName 0
    Message 5
    CloseMessage
    ApplyMovement 14, StarkMountainRoom2_Movement_02A4
    WaitMovement
    WaitSE SE_CONFIRM_sseq_3
    PlaySE SEQ_SE_DP_KAIDAN2_sseq
    RemoveObject 14
    WaitSE SEQ_SE_DP_KAIDAN2_sseq
    SetVarFromValue VAR_STARK_MOUNTAIN_ROOM_2_FOLLOWER_BUCK_STATE, 2
    ReleaseAll
    End
StarkMountainRoom2_Movement_0244:
    WalkOnSpotNormalSouth 1
    EndMovement

StarkMountainRoom2_Movement_024C:
    WalkOnSpotNormalNorth 1
    EndMovement

StarkMountainRoom2_Movement_0254:
    WalkNormalNorth 1
    EndMovement

StarkMountainRoom2_Movement_025C:
    WalkNormalNorth 8
    EndMovement

StarkMountainRoom2_Movement_0264:
    WalkOnSpotNormalSouth 1
    EndMovement

StarkMountainRoom2_Movement_026C:
    WalkOnSpotNormalSouth 1
    EndMovement

StarkMountainRoom2_Movement_0274:
    WalkNormalNorth 1
    WalkOnSpotNormalWest 1
    EndMovement

StarkMountainRoom2_Movement_0280:
    WalkNormalWest 1
    WalkOnSpotNormalEast 1
    EndMovement

StarkMountainRoom2_Movement_028C:
    WalkNormalWest 1
    EndMovement

StarkMountainRoom2_Movement_0294:
    WalkOnSpotNormalNorth 1
    Delay8 2
    WalkOnSpotNormalWest 1
    EndMovement

StarkMountainRoom2_Movement_02A4:
    WalkNormalNorth 1
    EndMovement

