@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry HearthomeCity_Entry0
    ScriptEntry HearthomeCity_Entry1
    ScriptEntry HearthomeCity_Entry2
    ScriptEntry HearthomeCity_Entry3
    ScriptEntry HearthomeCity_Entry4
    ScriptEntry HearthomeCity_Entry5
    ScriptEntry HearthomeCity_Entry6
    ScriptEntry HearthomeCity_Entry7
    ScriptEntry HearthomeCity_Entry8
    ScriptEntry HearthomeCity_Entry9
    ScriptEntry HearthomeCity_Entry10
    ScriptEntry HearthomeCity_Entry11
    ScriptEntry HearthomeCity_Entry12
    ScriptEntry HearthomeCity_Entry13
    ScriptEntry HearthomeCity_Entry14
    ScriptEntry HearthomeCity_Entry15
    ScriptEntry HearthomeCity_Entry16
    ScriptEntry HearthomeCity_Entry17
    ScriptEntry HearthomeCity_Entry18
    ScriptEntry HearthomeCity_Entry19
    ScriptEntry HearthomeCity_Entry20
    ScriptEntry HearthomeCity_Entry21
    ScriptEntry HearthomeCity_Entry22
    ScriptEntry HearthomeCity_Entry23
    ScriptEntry HearthomeCity_Entry24
    ScriptEntry HearthomeCity_Entry25
    ScriptEntry HearthomeCity_Entry26
    ScriptEntry HearthomeCity_Entry27
    ScriptEntry HearthomeCity_Entry28
    ScriptEntry HearthomeCity_Entry29
    ScriptEntry HearthomeCity_Entry30
    ScriptEntry HearthomeCity_Entry31
    ScriptEntry HearthomeCity_Entry32
    ScriptEntry HearthomeCity_Entry33
    ScriptEntryEnd

HearthomeCity_Entry0:
    End
HearthomeCity_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 6
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 7
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry3:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 23
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry4:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 8
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry5:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 9
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry6:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 11
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry7:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 13
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry8:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 21
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry9:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    WaitSE SE_CONFIRM_sseq_3
    PlayCry SPECIES_PACHIRISU, 0
    Message 22
    WaitCry
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry10:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag MAP_LOCAL_FLAGS_START
    GoToIf 1, HearthomeCity_0506
    Message 14
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, HearthomeCity_0511
    Message 15
    CloseMessage
    WaitTime 15, VAR_0x800C
    GetPlayerDir VAR_0x8004
    CompareVarToValue VAR_0x8004, 0
    GoToIf 1, HearthomeCity_051C
    CompareVarToValue VAR_0x8004, 1
    GoToIf 1, HearthomeCity_0534
    CompareVarToValue VAR_0x8004, 2
    GoToIf 1, HearthomeCity_054C
    CompareVarToValue VAR_0x8004, 3
    GoToIf 1, HearthomeCity_0564
    End
HearthomeCity_Entry11:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 19
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry12:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 12
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry13:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 20
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry14:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 24
    Message 25
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_GLOBE
    GoToIf 0, HearthomeCity_057C
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_GYM_STATUE
    GoToIf 0, HearthomeCity_057C
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_CUTE_CUP
    GoToIf 0, HearthomeCity_057C
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_COOL_CUP
    GoToIf 0, HearthomeCity_057C
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_BEAUTY_CUP
    GoToIf 0, HearthomeCity_057C
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_TOUGH_CUP
    GoToIf 0, HearthomeCity_057C
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_CLEVER_CUP
    GoToIf 0, HearthomeCity_057C
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_BLUE_CRYSTAL
    GoToIf 0, HearthomeCity_057C
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_PINK_CRYSTAL
    GoToIf 0, HearthomeCity_057C
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_RED_CRYSTAL
    GoToIf 0, HearthomeCity_057C
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_YELLOW_CRYSTAL
    GoToIf 0, HearthomeCity_057C
    SetFlag FLAG_RECEIVED_ALL_HEARTHOME_CITY_GOODS
    GoTo HearthomeCity_05C4
HearthomeCity_Entry15:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 10
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry16:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 47
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry17:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    Message 48
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry18:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 49
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry19:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 50
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry20:
    LockAll
    ApplyMovement LOCALID_PLAYER, HearthomeCity_Movement_0B34
    WaitMovement
    GetPlayerMapPos 32772, 32773
    CompareVarToValue VAR_0x8005, 725
    GoToIf 1, HearthomeCity_05CF
    CompareVarToValue VAR_0x8005, 726
    GoToIf 1, HearthomeCity_05E5
    CompareVarToValue VAR_0x8005, 727
    GoToIf 1, HearthomeCity_05FB
    CompareVarToValue VAR_0x8005, 728
    GoToIf 1, HearthomeCity_0611
    CompareVarToValue VAR_0x8005, 729
    GoToIf 1, HearthomeCity_0627
    End
HearthomeCity_Entry21:
    DrawSignpostInstantMessage 52, 0, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
HearthomeCity_Entry22:
    DrawSignpostTextBox 3, 0
    SetSignpostCommand 3
    WaitForSignpostDone
    DrawSignpostScrollingMessage 53, VAR_0x800C
    CallCommonScript 2000
    End
HearthomeCity_Entry23:
    DrawSignpostInstantMessage 54, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
HearthomeCity_Entry24:
    DrawSignpostInstantMessage 55, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
HearthomeCity_Entry25:
    DrawSignpostInstantMessage 56, 1, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
HearthomeCity_Entry26:
    DrawSignpostInstantMessage 57, 1, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
HearthomeCity_Entry27:
    DrawSignpostInstantMessage 58, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
HearthomeCity_Entry28:
    DrawSignpostInstantMessage 59, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
HearthomeCity_Entry29:
    DrawSignpostInstantMessage 60, 2, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
HearthomeCity_Entry30:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 3
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry31:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 51
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Entry32:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 61
    ShowYesNoMenu VAR_0x800C
    CompareVarToValue VAR_0x800C, 1
    GoToIf 1, HearthomeCity_063D
    GetPartyCount VAR_0x8001
    CountPartyMonsBelowLevelThreshold VAR_0x8002, 32
    SubVar VAR_0x8001, VAR_0x8002
    CompareVarToValue VAR_0x8001, 0
    GoToIf 2, HearthomeCity_0648
    Message 63
    CloseMessage
    Call HearthomeCity_0653
    End
HearthomeCity_Entry33:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    CheckFlag FLAG_UNK_0x0A85
    GoToIf 0, HearthomeCity_0670
    Message 67
    InitLocalTextListMenu 1, 1, 0, VAR_0x800C, 1
    CheckFlag FLAG_UNK_0x0A88
    CallIf 1, HearthomeCity_067D
    CheckFlag FLAG_UNK_0x0A86
    CallIf 1, HearthomeCity_0687
    CheckFlag FLAG_UNK_0x0A84
    CallIf 1, HearthomeCity_0691
    CheckFlag FLAG_UNK_0x0A82
    CallIf 1, HearthomeCity_069B
    CheckFlag FLAG_UNK_0x0A81
    CallIf 1, HearthomeCity_06A5
    ShowListMenu
    SetVarFromVar VAR_0x8008, VAR_0x800C
    CompareVarToValue VAR_0x8008, 0
    GoToIf 1, HearthomeCity_06AF
    CompareVarToValue VAR_0x8008, 1
    GoToIf 1, HearthomeCity_06E1
    CompareVarToValue VAR_0x8008, 2
    GoToIf 1, HearthomeCity_0713
    CompareVarToValue VAR_0x8008, 3
    GoToIf 1, HearthomeCity_0745
    CompareVarToValue VAR_0x8008, 4
    GoToIf 1, HearthomeCity_0777
    GoTo HearthomeCity_07A9
HearthomeCity_0506:
    Message 17
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_0511:
    Message 18
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_051C:
    ApplyMovement 0, HearthomeCity_Movement_0B3C
    ApplyMovement LOCALID_PLAYER, HearthomeCity_Movement_0B54
    WaitMovement
    GoTo HearthomeCity_07AF
HearthomeCity_0534:
    ApplyMovement 0, HearthomeCity_Movement_0B3C
    ApplyMovement LOCALID_PLAYER, HearthomeCity_Movement_0B6C
    WaitMovement
    GoTo HearthomeCity_07AF
HearthomeCity_054C:
    ApplyMovement 0, HearthomeCity_Movement_0B3C
    ApplyMovement LOCALID_PLAYER, HearthomeCity_Movement_0B84
    WaitMovement
    GoTo HearthomeCity_07AF
HearthomeCity_0564:
    ApplyMovement 0, HearthomeCity_Movement_0B9C
    ApplyMovement LOCALID_PLAYER, HearthomeCity_Movement_0BC0
    WaitMovement
    GoTo HearthomeCity_07AF
HearthomeCity_057C:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_GLOBE
    GoToIf 1, HearthomeCity_07BE
    CheckFlag FLAG_CONNECTED_TO_WIFI
    GoToIf 0, HearthomeCity_07BE
    Message 33
    SetVarFromValue VAR_0x8004, 46
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_GLOBE
    CloseMessage
    ReleaseAll
    End
HearthomeCity_05C4:
    Message 27
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_05CF:
    SetObjectEventPos 32, 471, 725
    SetObjectEventPos 31, 471, 725
    GoTo HearthomeCity_0817
HearthomeCity_05E5:
    SetObjectEventPos 32, 471, 726
    SetObjectEventPos 31, 471, 726
    GoTo HearthomeCity_0817
HearthomeCity_05FB:
    SetObjectEventPos 32, 471, 727
    SetObjectEventPos 31, 471, 727
    GoTo HearthomeCity_0817
HearthomeCity_0611:
    SetObjectEventPos 32, 471, 728
    SetObjectEventPos 31, 471, 728
    GoTo HearthomeCity_0817
HearthomeCity_0627:
    SetObjectEventPos 32, 471, 729
    SetObjectEventPos 31, 471, 729
    GoTo HearthomeCity_0817
HearthomeCity_063D:
    Message 62
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_0648:
    Message 65
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_0653:
    StartTrainerBattle 210, 0
    CheckWonBattle VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_0872
    GoTo HearthomeCity_0878
HearthomeCity_0670:
    Message 66
    SetFlag FLAG_UNK_0x0A85
    CloseMessage
    ReleaseAll
    End
HearthomeCity_067D:
    AddListMenuEntry 68, 0, 255
    Return
HearthomeCity_0687:
    AddListMenuEntry 69, 1, 255
    Return
HearthomeCity_0691:
    AddListMenuEntry 70, 2, 255
    Return
HearthomeCity_069B:
    AddListMenuEntry 71, 3, 255
    Return
HearthomeCity_06A5:
    AddListMenuEntry 72, 4, 255
    Return
HearthomeCity_06AF:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 45, 303, 757, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
HearthomeCity_06E1:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 65, 305, 531, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
HearthomeCity_0713:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 433, 566, 657, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
HearthomeCity_0745:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 120, 600, 816, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
HearthomeCity_0777:
    CloseMessage
    PlayCry SPECIES_ABRA, 0
    WaitCry
    FadeScreen 6, 1, 0, 0
    WaitFadeScreen
    Warp 442, 472, 539, 1
    FadeScreen 6, 1, 1, 0
    WaitFadeScreen
    ReleaseAll
    End
HearthomeCity_07A9:
    CloseMessage
    ReleaseAll
    End
HearthomeCity_07AF:
    SetFlag MAP_LOCAL_FLAGS_START
    Message 16
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_07BE:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_GYM_STATUE
    GoToIf 1, HearthomeCity_0883
    CountBadgesAcquired VAR_0x800C
    CompareVarToValue VAR_0x800C, 8
    GoToIf 0, HearthomeCity_0883
    Message 34
    SetVarFromValue VAR_0x8004, 47
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_GYM_STATUE
    CloseMessage
    ReleaseAll
    End
HearthomeCity_080C:
    Message 30
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_0817:
    ClearFlag FLAG_HIDE_HEARTHOME_CITY_KEIRA
    ClearFlag FLAG_HIDE_HEARTHOME_CITY_BUNEARY
    AddObject 32
    AddObject 31
    ApplyMovement 31, HearthomeCity_Movement_0BE0
    WaitMovement
    PlayCry SPECIES_BUNEARY, 0
    WaitCry
    ApplyMovement 32, HearthomeCity_Movement_0BE8
    WaitMovement
    Message 0
    Message 1
    PlayCry SPECIES_BUNEARY, 0
    WaitCry
    RemoveObject 31
    Message 2
    CloseMessage
    ApplyMovement 32, HearthomeCity_Movement_0BF0
    WaitMovement
    RemoveObject 32
    SetVarFromValue VAR_HEARTHOME_CITY_STATE, 1
    ReleaseAll
    End
HearthomeCity_0872:
    BlackOutFromBattle
    ReleaseAll
    End
HearthomeCity_0878:
    Message 64
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_0883:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_CUTE_CUP
    GoToIf 1, HearthomeCity_08CB
    CheckFlag FLAG_CONTEST_MASTER_CUTE
    GoToIf 0, HearthomeCity_08CB
    Message 35
    SetVarFromValue VAR_0x8004, 72
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_CUTE_CUP
    CloseMessage
    ReleaseAll
    End
HearthomeCity_08CB:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_COOL_CUP
    GoToIf 1, HearthomeCity_0913
    CheckFlag FLAG_CONTEST_MASTER_COOL
    GoToIf 0, HearthomeCity_0913
    Message 36
    SetVarFromValue VAR_0x8004, 73
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_COOL_CUP
    CloseMessage
    ReleaseAll
    End
HearthomeCity_0913:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_BEAUTY_CUP
    GoToIf 1, HearthomeCity_095B
    CheckFlag FLAG_CONTEST_MASTER_BEAUTY
    GoToIf 0, HearthomeCity_095B
    Message 37
    SetVarFromValue VAR_0x8004, 74
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_BEAUTY_CUP
    CloseMessage
    ReleaseAll
    End
HearthomeCity_095B:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_TOUGH_CUP
    GoToIf 1, HearthomeCity_09A3
    CheckFlag FLAG_CONTEST_MASTER_TOUGH
    GoToIf 0, HearthomeCity_09A3
    Message 38
    SetVarFromValue VAR_0x8004, 75
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_TOUGH_CUP
    CloseMessage
    ReleaseAll
    End
HearthomeCity_09A3:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_CLEVER_CUP
    GoToIf 1, HearthomeCity_09EB
    CheckFlag FLAG_CONTEST_MASTER_SMART
    GoToIf 0, HearthomeCity_09EB
    Message 39
    SetVarFromValue VAR_0x8004, 76
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_CLEVER_CUP
    CloseMessage
    ReleaseAll
    End
HearthomeCity_09EB:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_BLUE_CRYSTAL
    GoToIf 1, HearthomeCity_0A39
    GetUndergroundTalkCounter VAR_0x800C
    CompareVarToValue VAR_0x800C, 100
    GoToIf 0, HearthomeCity_0A39
    Message 40
    SetVarFromValue VAR_0x8004, 77
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_BLUE_CRYSTAL
    CloseMessage
    ReleaseAll
    End
HearthomeCity_0A39:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_PINK_CRYSTAL
    GoToIf 1, HearthomeCity_0A87
    GetUndergroundItemsGivenAway VAR_0x800C
    CompareVarToValue VAR_0x800C, 100
    GoToIf 0, HearthomeCity_0A87
    Message 41
    SetVarFromValue VAR_0x8004, 78
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_PINK_CRYSTAL
    CloseMessage
    ReleaseAll
    End
HearthomeCity_0A87:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_RED_CRYSTAL
    GoToIf 1, HearthomeCity_0AD5
    GetUndergroundFossilsUnearthed VAR_0x800C
    CompareVarToValue VAR_0x800C, 100
    GoToIf 0, HearthomeCity_0AD5
    Message 42
    SetVarFromValue VAR_0x8004, 79
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_RED_CRYSTAL
    CloseMessage
    ReleaseAll
    End
HearthomeCity_0AD5:
    CheckFlag FLAG_RECEIVED_HEARTHOME_CITY_YELLOW_CRYSTAL
    GoToIf 1, HearthomeCity_0B23
    GetUndergroundTrapsSet VAR_0x800C
    CompareVarToValue VAR_0x800C, 100
    GoToIf 0, HearthomeCity_0B23
    Message 43
    SetVarFromValue VAR_0x8004, 80
    SetVarFromValue VAR_0x8005, 1
    CheckHasRoomForGoodsInPC 32772, 32773, VAR_0x800C
    CompareVarToValue VAR_0x800C, 0
    GoToIf 1, HearthomeCity_080C
    CallCommonScript 2012
    SetFlag FLAG_RECEIVED_HEARTHOME_CITY_YELLOW_CRYSTAL
    CloseMessage
    ReleaseAll
    End
HearthomeCity_0B23:
    GoTo HearthomeCity_0B29
HearthomeCity_0B29:
    Message 32
    WaitButton
    CloseMessage
    ReleaseAll
    End
HearthomeCity_Movement_0B34:
    EmoteExclamationMark 1
    EndMovement

HearthomeCity_Movement_0B3C:
    WalkNormalWest 20
    WalkNormalNorth 13
    WalkNormalEast 12
    WalkNormalNorth 4
    WalkOnSpotNormalSouth 1
    EndMovement

HearthomeCity_Movement_0B54:
    WalkNormalNorth 1
    WalkNormalWest 20
    WalkNormalNorth 13
    WalkNormalEast 12
    WalkNormalNorth 3
    EndMovement

HearthomeCity_Movement_0B6C:
    WalkNormalSouth 1
    WalkNormalWest 20
    WalkNormalNorth 13
    WalkNormalEast 12
    WalkNormalNorth 3
    EndMovement

HearthomeCity_Movement_0B84:
    WalkNormalWest 1
    WalkNormalWest 20
    WalkNormalNorth 13
    WalkNormalEast 12
    WalkNormalNorth 3
    EndMovement

HearthomeCity_Movement_0B9C:
    WalkNormalNorth 1
    WalkNormalWest 2
    WalkNormalSouth 1
    WalkNormalWest 18
    WalkNormalNorth 13
    WalkNormalEast 12
    WalkNormalNorth 4
    WalkOnSpotNormalSouth 1
    EndMovement

HearthomeCity_Movement_0BC0:
    Delay8 2
    Delay4 1
    WalkOnSpotNormalWest 1
    WalkNormalWest 19
    WalkNormalNorth 13
    WalkNormalEast 12
    WalkNormalNorth 3
    EndMovement

HearthomeCity_Movement_0BE0:
    WalkFastWest 9
    EndMovement

HearthomeCity_Movement_0BE8:
    WalkFastWest 8
    EndMovement

HearthomeCity_Movement_0BF0:
    WalkNormalEast 8
    EndMovement

