@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry Route228_Entry0
    ScriptEntry Route228_Entry1
    ScriptEntry Route228_Entry2
    ScriptEntry Route228_Entry3
    ScriptEntryEnd

Route228_Entry0:
    DrawSignpostInstantMessage 0, 1, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
Route228_Entry1:
    DrawSignpostInstantMessage 1, 1, 0, 32780
    SetSignpostCommand 3
    WaitForSignpostDone
    GetSignpostInput VAR_0x800C
    CallCommonScript 2000
    End
Route228_Entry2:
    CompareVarToValue VAR_ROCK_PEAK_RUINS_STATE, 290
    CallIf 5, Route228_00BB
    CheckPartyHasSpecies VAR_MAP_LOCAL_0x01, SPECIES_RELICANTH
    CheckPartyHasSpecies VAR_MAP_LOCAL_0x02, SPECIES_WAILORD
    CheckFlag FLAG_GALACTIC_LEFT_LAKE_VALOR
    GoToIf 0, Route228_00C3
    CompareVarToValue VAR_MAP_LOCAL_0x01, 0
    GoToIf 1, Route228_00C3
    CompareVarToValue VAR_MAP_LOCAL_0x02, 0
    GoToIf 1, Route228_00C3
    GoTo Route228_00CD
Route228_Entry3:
    CheckPartyHasSpecies VAR_MAP_LOCAL_0x01, SPECIES_RELICANTH
    CheckPartyHasSpecies VAR_MAP_LOCAL_0x02, SPECIES_WAILORD
    CheckFlag FLAG_GALACTIC_LEFT_LAKE_VALOR
    GoToIf 0, Route228_00C3
    CompareVarToValue VAR_MAP_LOCAL_0x01, 0
    GoToIf 1, Route228_00C3
    CompareVarToValue VAR_MAP_LOCAL_0x02, 0
    GoToIf 1, Route228_00C3
    GoTo Route228_00CD
Route228_00BB:
    SetVarFromValue VAR_ROCK_PEAK_RUINS_STATE, 0
    Return
Route228_00C3:
    SetWarpEventPos 5, 783, 339
    End
Route228_00CD:
    SetWarpEventPos 4, 783, 339
    End
    .balign 4, 0

