@ Generated by tools/oxide/bulk_scripts.py from the base ROM's bytecode.
@ Byte-exact but machine-shaped: labels are offsets and operands are mostly
@ numbers. Rewrite in the repo's idiom when this map gets proper attention.
#include "macros/scrcmd.inc"


    ScriptEntry PastoriaCityNorthHouse_Entry0
    ScriptEntry PastoriaCityNorthHouse_Entry1
    ScriptEntry PastoriaCityNorthHouse_Entry2
    ScriptEntryEnd

@ Oxide: the clown's gift that stood here moved to the Restaurant on Route
@ 213 (Ian, 2026-09-25), so that it counts as the Restaurant's capture and not
@ Pastoria City's. Its script, flag and pool went with it (scripts_restaurant.s).

PastoriaCityNorthHouse_Entry0:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 0
    WaitButton
    CloseMessage
    ReleaseAll
    End
PastoriaCityNorthHouse_Entry1:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    WaitSE SE_CONFIRM_sseq_3
    PlayCry SPECIES_PSYDUCK, 0
    Message 1
    WaitCry
    WaitButton
    CloseMessage
    ReleaseAll
    End
PastoriaCityNorthHouse_Entry2:
    PlaySE SE_CONFIRM_sseq_3
    LockAll
    FacePlayer
    Message 2
    WaitButton
    CloseMessage
    ReleaseAll
    End
